### ISSUE TITLE
Work Item Description: Ability to add a checklist

### ISSUE THREAD

**Issue by Preeticp** [openshiftio/openshift.io#1030]
As an user I would like to have the ability to add a checklist for tasks/a task list in the Description for my Work Item.

**Comment by qodfathr** [comment]
@Preeticp thank you for this suggestion. A checklist in a work item is actually an anti-goal of the Planner. That's how some other systems behave (e.g. Trello; GitHub) because those systems fail to properly support true parent/child relationships. In the OpenShift.io Planner, rather than a checklist in a work item, the work item would be linked to a number of children, each representing one of the elements of the checklist. This permits the individual items to be managed separately for maximum flexibility and impact.

It would be important for people to be able to visualize this, and this is the reason for the hierarchical view in the Planner.

I'm going to close as No Plan to Implement, but please do evaluate the hierarchical nature of work items as the Planner continues to get updates weekly, and please offer suggestions on how to make that experience better.

**Comment by Preeticp** [comment]
> In the OpenShift.io Planner, rather than a checklist in a work item, the work item would be linked to a number of children, each representing one of the elements of the checklist. This permits the individual items to be managed separately for maximum flexibility and impact.
Sounds good. Thanks for the explanation, that helps.
> I'm going to close as No Plan to Implement, but please do evaluate the hierarchical nature of work items as the Planner continues to get updates weekly, and please offer suggestions on how to make that experience better.
Sure, I will do that.
