### ISSUE TITLE
new projects created via the create quickstarts don't have their pipelines triggered

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/openshift.io#1065]
currently you need to manually start the pipeline

**Comment by ldimaggi** [comment]
Related to https://github.com/openshiftio/openshift.io/issues/788

**Comment by ldimaggi** [comment]
Screnshot from failing test:
http://artifacts.ci.centos.org/devtools/e2e/420_testoct51507220037588_pipeline_promote_fail.png

**Comment by rawlingsj** [comment]
This will be because I disabled the sync plugin from auto triggering builds on a scan. We can change it to trigger if no other builds exist but that means whenever anyone initially uses the GitHub org scan in Jenkins it will trigger master. For our fabric8 repos as an example that would be a new release, not sure if we want that? 

I guess we should do that for now until we think of a better way as we don’t want forge to trigger the job after creation now that it’s decoupled via the configmap sync.

**Comment by jstrachan** [comment]
we could switch to triggering the job in Forge; the only downside is that Jenkins may not be running yet; so the folder sync might not have run yet. However if syncing doesn't trigger builds am not sure thats an issue anyway?

**Comment by ldimaggi** [comment]
_James R: '...We can change it to trigger if no other builds exist but that means whenever anyone initially uses the GitHub org scan in Jenkins it will trigger master...'_ 

Is the concern here that any new build/pipeline will cause all builds to be rebuilt?

**Comment by jstrachan** [comment]
its more the other way around - the concern is organisation scans should not trigger new releases

**Comment by jstrachan** [comment]
fixed now in prod
