### ISSUE TITLE
Bad work item title for new analytics work items

### ISSUE THREAD

**Issue by cctrieloff** [openshiftio/openshift.io#1071]
Work item that "Create Work Item" as title -- should be meaning full.

Might be nice if it also created the patch.

![analytcis](https://user-images.githubusercontent.com/13753654/31292327-fe9eb366-aaa0-11e7-986f-0fd6ad8c72eb.png)

**Comment by samuzzal-choudhury** [comment]
@arunkumars08 @invincibleJai Can one of you please look into this? Currently, the title appears as _Create Work Item_ for analytics work items. AFAIK, we do pass a valid title in the work item creation API call. Was there any recent changes in the API parameters which we missed incorporating?

**Comment by invincibleJai** [comment]
@samuzzal-choudhury We are looking into it.

**Comment by arunkumars08** [comment]
@samuzzal-choudhury @cctrieloff The fix for this is in this PR - https://github.com/fabric8-ui/fabric8-recommender/pull/353

As per this fix, it will show 'Alternate component for {name of the component}' for alternate recommendation and 'Add {name of the component} to your application stack' in case of companion recommendation

@invincibleJai Thanks for helping me with the fix.

**Comment by samuzzal-choudhury** [comment]
@arunkumars08 @invincibleJai thanks for the fix.

**Comment by adisakala** [comment]
where are we tracking "Might be nice if it also created the patch."? this one or separate issue? @samuzzal-choudhury

**Comment by invincibleJai** [comment]
@adisakala it is this one only Adi, as per my knowledge.

**Comment by joshuawilson** [comment]
Can we close this? I think the fix is in prod.
