### ISSUE TITLE
Able to figure out and sync the delta between OLAP and OLTP stores

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#1085]
S3 being OLAP and Graph layer on DynamoDB being OLTP, there is always a need to figure out the delta between these two data sources and able to initiate sync. between these data sources (only for the identified delta) would be key to provide very recent information to users of analytics platform.

**Comment by msrb** [comment]
We will start with a spike.

**Comment by msrb** [comment]
The problem:

There were times in the past when graph ingestion part of the pipeline was completely disabled, or we encountered bugs which prevented us from immediately ingesting data that just landed in S3 also to graph layer. Therefore we need to be able to ingest missing data to graph afterwards.

We can initiate graph sync even now, but since we can't tell what data are missing there, we either start from the beginning and attempt to sync everything (we risk SQS timeouts here), or we guess.

Note the assumption here is that this "out-of-pipeline" graph sync is something that should happen irregularly, only when we know that the pipeline was temporarily broken and there are likely data missing in graph.

Proposal:

This can be solved by many ways. We can't really afford to rewrite/redesign the whole pipeline (that will likely come in future), we need to tweak what we have now. One possible solution to this problem is to let data-importer ingest data into graph and if the data were successfully ingested (we trust gremlin here, 200 means success), then [tag](http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html) corresponding objects in S3 (could be for example `graph_sync_at: timestamp`). This means that if the pipeline is operational, but there was a bug somewhere, then data that did not land in graph won't be tagged and we can easily find it later. Similarly if graph subsystem was temporarily excluded from the pipeline from some reason.

Then we will need a way how to initiate sync of the missing packages. I think this functionality should live in data-importer. This component is not accessible from outside the cluster, but we could create dummy endpoint in jobs service that would call data-importer. I will leave the decision on implementer :)

**Comment by msrb** [comment]
We want to proceed to actual implementation in Sprint 142.

**Comment by tisnik** [comment]
Related to #1635 and #1636

**Comment by tuxdna** [comment]
After a discussion with the team, we need to come up with:

 * 1 ) code that does the sync between OLTP and OLAP
 * 2 ) location where this code will run, and with what strategy

(2) can be one of:

 * OpenShift Jobs
 * Jobs service
 * standalone script that is invoked periodically

I will be in a better position in another couple of days about the design for this sync mechanism.

**Comment by tuxdna** [comment]
We provide a list of EPV to the Data Model importer HTTP API, and this list of packages are imported into the Graph. However this API doesn't mark the imported packages back in either RDS or S3. So we have to add these markers. We can use S3 tags as proposed by @msrb .

For identifying the diff between Graph and S3, we have to enlist all the package-versions and then identify the packages missing from Graph DB.

Once we have added S3 tags as markers, we can find the list incrementally, and only update the graph with missing EPVs.

**Comment by tuxdna** [comment]
Only available boto3 APIs for Object tagging - https://github.com/boto/boto3/issues/915#issuecomment-267667390

 * https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_object_tagging
 * https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.get_object_tagging

Minio doesn't support Object tagging - https://github.com/minio/minio-go/issues/605

So all the development needs to be done against S3 only.

**Comment by tuxdna** [comment]
- [ ] https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/495
- [ ] https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/69

**Comment by joshuawilson** [comment]
I removed `user-story` as it had 2 `type` labels. It reads more like a `feature`.  It's up to you if you want to change it, but it should have only one `type`.

**Comment by krishnapaparaju** [comment]
@tuxdna @msrb Lets target Graph to be in complete sync for complete Maven and Node ecosystems.

**Comment by tuxdna** [comment]
Data Model importer API does not have a public route in production. So we need to add a JOBs API for invoking the sync mechanism.

Now working in creating a JOBs API invoke the sync on production.

**Comment by miteshvp** [comment]
@msrb @tuxdna - now since we have jobs API also available, is it possible to start the actual sync between graph and S3 in production starting with maven and then with node?
cc @krishnapaparaju

**Comment by tuxdna** [comment]
- [ ] Unable to make any API calls due to authorization failure   https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/244

**Comment by tuxdna** [comment]
Ready to invoke the sync: https://gist.github.com/tuxdna/4930d9f6c30f2cca8e2a77aeab77b8b7

**Comment by msrb** [comment]
@tuxdna Cool! :) Please go ahead and do so. Please start with Maven. Thanks 😉

**Comment by tuxdna** [comment]
We can not track ingestion in other task for Maven. Closing this.
