### ISSUE TITLE
[Complete Stack report]On hover of bottom item of the table, it expands too much

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1154]
on my space page, click "Show complete stack report"
![image](https://user-images.githubusercontent.com/1105127/31772062-9cce36b4-b4de-11e7-93c4-f7e5e69438b7.png)

click on "Additional components are often used by similar stacks" to display the second table:
![image](https://user-images.githubusercontent.com/1105127/31772094-bab462f2-b4de-11e7-8265-91c905cae05b.png)

hover on the line, it expands and a big part is hidden:
![image](https://user-images.githubusercontent.com/1105127/31772114-cf57e472-b4de-11e7-8be2-88a3eab5d36f.png)

if I scroll to bottom, I can see everything but seems a lot of space is used for nothing:
![image](https://user-images.githubusercontent.com/1105127/31772126-e06b95a6-b4de-11e7-9c47-2470ef0a49bf.png)

**Comment by apupier** [comment]
in fact even on the first table, it increases the size a lot for a lot of emptiness:
![image](https://user-images.githubusercontent.com/1105127/31772177-16c12c56-b4df-11e7-82ab-236c1c48978d.png)

**Comment by samuzzal-choudhury** [comment]
@apupier @joshuawilson the stack report UX revamp is in progress which will address this issue. We are tracking that in the work item https://github.com/openshiftio/openshift.io/issues/1277. The UX can be seen here: https://redhat.invisionapp.com/share/64E3OQ2NJ#.

Closing this issue to track the progress in the sprint 140 level work item https://github.com/openshiftio/openshift.io/issues/1277. Please let me know if you think otherwise.
