### ISSUE TITLE
[Che] Error message when creating a second workspace from Che dashboard should be improved until creation of several workspaces will be allowed

### ISSUE THREAD

**Issue by apupier** [openshiftio/openshift.io#1174]
Che dashboard is accessible through the top "left arrow":
![image](https://user-images.githubusercontent.com/1105127/31810642-d0eeabc4-b57c-11e7-9acc-939e3728960b.png)

then there is a "create workspace menu" but it is failing with this error:
![image](https://user-images.githubusercontent.com/1105127/31810653-df547fea-b57c-11e7-9355-688b986e7fd3.png)

**Comment by l0rd** [comment]
@apupier you are trying to start a workspace when one is already running. Thats' why it's failing. Having more than one workspace running is not supported in OSIO currently. However this message doesn't help but should be improved with new upstream version of Che (v5.19.0). We are currently working on rebasing rh-che (Che for osio) on that version.

**Comment by l0rd** [comment]
@apupier if you are ok I would change title to "Error message when creating a second workspace from dashboard should be improved"

**Comment by ibuziuk** [comment]
@apupier could you please provide more details (che-version / che-server logs / openshift events) ? As, @l0rd mentioned you are probably trying to create worksapce when one is already running and this is expected to fail due to quota limit issue:

![image](https://user-images.githubusercontent.com/1461122/31884078-4d2fa442-b7ec-11e7-8b9e-9437a404dd13.png)

However, there should not be the error message about the deployment not found - workspace pod would be deleted immediately once the quota is reached and only `Workspace is not running...` message should be shown. Basically, creating workspaces using dashboard is not smth. that would be exposed to the end-user, and currently it is just a workaround until workspace deletion is in place - https://github.com/openshiftio/openshift.io/issues/388

**Comment by apupier** [comment]
> @apupier could you please provide more details (che-version / che-server logs / openshift events) ?

che-version: 2.0.37
che-serv logs/openshift events: where are they? How to provide them?

**Comment by apupier** [comment]
> @apupier you are trying to start a workspace when one is already running. Thats' why it's failing. Having more than one workspace running is not supported in OSIO currently.

ouch, hope it will be implemented soon. Working on 2 microservices at the same time seems to me to be a very common use case

**Comment by apupier** [comment]
> @apupier if you are ok I would change title to "Error message when creating a second workspace from dashboard should be improved"

updated to "Error message when creating a second workspace from Che dashboard should be improved until creation of several workspaces will be allowed"

**Comment by ibuziuk** [comment]
This should be fixed once PR is merged - https://github.com/redhat-developer/rh-che/pull/496
User will not be able to start a new workspace if there is already one running via dashboard on osio

**Comment by ibuziuk** [comment]
Now user will not be able to start more than one workspace via dashboard
![image](https://user-images.githubusercontent.com/1461122/34736470-54873ae2-f573-11e7-8047-63d923675e37.png)
