### ISSUE TITLE
[2] Make it possible to deploy API and ingestion workers separately

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#1203]
# Description

Currently it's not possible to only update ingestion workers, or only API workers in production. Since the two types of workers don't share the same workload and are used for different purposes, it would be nice to be able to update just one type of worker, when situation calls for it.

# Acceptance criteria
- [x] it is possible to update only certain type of workers in production

**Comment by fridex** [comment]
Basically this is possible based on the configuration of saas-analytics YAML file where we wouldn't share hash with other workers. Nevertheless I don't find this to be a good idea:

1. Actually workers share workload - API workers send transitive dependencies to be analysed on ingestion workers - if this split would happen this compatibility layer needs to be maintained explicitly (which API workers and which ingestion workers are deployed)
2. If we decide to introduce such divergence also note that workers share resources where results are stored. Workers can easily write different results (different schema) of tasks to S3/graph database.
3. Most tests do not test such divergence and rely purely on API or ingestion workers, but not both. Many errors wouldn't be uncovered in our e2e and unit tests.
4. Mostly we deploy new features or bugfixes - I don't see why we shouldn't do it based on worker type.

**Comment by msrb** [comment]
Good summary 👍 

This is really about being able to do it, when necessary. I don't think we should start deploying different worker types separately, but sometimes situation may require it. Right know we only know that it's possible to do with different hashes in saas-analytics YAML, but we don't know what/where could go wrong. And what should person promoting such change to production check.

Adding to the list:
- DB migrations - only certain workers run it

**Comment by samuzzal-choudhury** [comment]
@fridex @msrb I have a got a different take on this. IMO, the responsibilities of API workers and Ingestion workers are properly demarcated and there should not be any problem of having two separate repositories if we decide to have a shared common worker library repo as a cleaner approach.

1. The only API resource that leverages on API worker ATM is /stack-analyses which does not invoke any of the ingestion flow to introduce any transitive or unknown dependencies. Please feel free to object if I overlooked anything. The logic in component-analyses that invokes the ingestion of unknown dependencies is in the server codebase.
2. Please understand that API worker is a consumer of graph database and not a manipulator. The only two workers that inserts into S3 bucket are BookkeeperTask and ManifestKeeperTask. But, both of those S3 buckets are isolated and in no way interfere with the ingestion process.
3. As far as my understanding goes, the current E2E test will rely only on the API flow and not the data ingestion. I suppose there is a separate set of tests for ingestion logic which I think is a better approach rather than combining those with the E2E tests. 
4. Having a common repo even with having separate deployment process is going to be more tedious especially when a manual intervention is involved and at a time where more and more new members are joining. IMHO, the separation of codebases is the key to get rid of that confusion.

All these comments are for a more robust analytics deployment on OSIO so that we all can have a good night's sleep very often. Any disagreements are more than welcome :-)

**Comment by fridex** [comment]
OK. I will leave this discussion up to you guys. Also with [flow migrations on redeployment](http://selinon.readthedocs.io/en/latest/migrations.html), please make sure that messages of different versions are consumable on one worker type so there will be no migration skew (see docs). This should be guaranteed with the current structure of flows now as I'm thinking about this from top of my head.

@msrb good point with database migrations - workers should use same schema. I'm not sure how sqlalchemy will behave if a model will differ from actual db schema - worth to rethink database migrations with this change or test this scenario.

@samuzzal-choudhury please correct me if I'm wrong, but isn't there an unknown path on component-analyses endpoint that triggers component flow? This is what I was referring to - stack analysis is done purely on api workers, that shouldn't be the case.

PR enabling this is already opened in https://github.com/openshiftio/saas-analytics/pull/162

**Comment by msrb** [comment]
Updating only certain type of workers is possible even today. However, it is not recommended. The deployments can be tightly coupled together, for example via database migrations. Therefore one needs to be very careful when doing so.
