### ISSUE TITLE
Reset environment creates zombie work items

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#1219]
1. Create a new space
2. Create some work items in that space -- add a description to get the full effect and change their states
3. Reset your environment
4. Create a new space, same name as step 1
5. Create some work items

I'm finding that WIs 1, 2 3, etc. from step 2 are being reincarnated in step 5.

**Comment by joshuawilson** [comment]
It might be related to https://github.com/openshiftio/openshift.io/issues/925

**Comment by joshuawilson** [comment]
@aslakknutsen @alexeykazakov how could we keep this kind of data? Maybe the reset only deletes the space but doesn't delete the WI and then same user and same space name allow them to get reconnected?

**Comment by alexeykazakov** [comment]
No, it should not be the case.. We do delete all space's work items when deleting the space. Maybe it's some UI cache? @godfathr can you share the link to the space with reincarnated WIs?

**Comment by alexeykazakov** [comment]
I can't reproduce it but what I found out is that because we use soft deletes in WIT, when we delete a space in WIT the cascade delete is not triggered and all Work Items from the deleted space are still present in WIT with deleted_at == null. They should not be listed in the new space though. But direct links to the old Work Items will work.

@kwk, @xcoulon something for you to investigate.

**Comment by joshuawilson** [comment]
that fits with what I thought was happening

**Comment by kwk** [comment]
I've assigned the issue to me. When deleting a space we currently leave all the WI's untouched (we not even soft-delete them). From the space controller I will probably soft-delete everything that links to a space  when that space gets deleted. This will make it more explicit and maintainable instead of setting up triggers. @aslakknutsen do you agree?

**Comment by aslakknutsen** [comment]
I get the WorkItem.Description from Number 1 in the deleted space when I attempt to create a new WorkItem in the new space. The first WorkItem in new space gets Description from deleted Space WorkItem.Number 1, the second gets Description from deleted space WorkItem.Number 2 etc etc...

It happens when you're on the Create screen (Full Detail view), And 'ok' the title. The inserted data and response from server is ok, but then UI reloads it self calling the 'named space / workitem number' end point and hits browser cache so "https://api.openshift.io/api/namedspaces/aslak/Test1219/workitems/1" redirects to the old workitem. The saved data is ok. You can only see the new WorkItems when on the backlog. If you preview a Workitem from the backlog it's ok, if you want to see the full details, UI reloads it self calling "https://api.openshift.io/api/namedspaces/aslak/Test1219/workitems/1" and hits the browser cache and is loading the old WorkItem.

The https://api.openshift.io/api/namedspaces/aslak/Test1219/workitems/1 endpoint is responding with 301 Perm moved, I think that should be changed to 307 Temp Redirect. I believe that should tell the browser not to use the Cache-Control from the redirect target as Cache-Control on the 'redirect url'..

**Comment by nimishamukherjee** [comment]
Tracking this on OSIO [1672](https://openshift.io/openshiftio/openshiftio/plan/detail/1672)

**Comment by kwk** [comment]
I've verified that [my fix](https://github.com/fabric8-services/fabric8-wit#1786) (as proposed by @aslakknutsen) is working on prod-preview. Will now port it over to prod to see if it works.

**Comment by kwk** [comment]
The issue is fixed in production as well.

**Comment by kwk** [comment]
When talking to @qodfathr he mentioned that there also seems to be an issue with the workitems shown on the dashboard. I'm double checking that now.

**Comment by kwk** [comment]
@qodfathr I could not verified what you described. Here's what I've tried:

1. Create a space `space2`
1. Create work item `feature1`
   1. specify name
   1. specify description
   1. assign to yourself
1. Reset environment
1. Click "Take be to dashboard" button
   1. Notice that `feature1` **doesn't** appear there
1. Create space `space2` again
  1. Notice, no `feature1` is appearing

**Comment by qodfathr** [comment]
I wonder if it's a local caching issue. I need to retest, but I think hitting refresh on the account home page / dashboard made the item disappear.

**Comment by kwk** [comment]
> I wonder if it's a local caching issue. I need to retest, but I think hitting refresh on the account home page / dashboard made the item disappear.

Yes @qodfathr , please do so and confirm here.
