### ISSUE TITLE
[2] Fix and enable all tests that check result of stack analysis

### ISSUE THREAD

**Issue by tisnik** [openshiftio/openshift.io#1241]
Currently, some tests that check result of stack analysis had to be commented because of changes made in the stack analysis API. Those tests - and especially its mock data - have to be updated and re-enabled again.

## Acceptance criteria

- [ ] all tests in selfcheck.feaure and stack_analyses*.feature are enabled
- [ ] all such tests will pass on CI

**Comment by joshuawilson** [comment]
I made this a P1 since we are running a live system that get's updated everyday. Tests are one of the main ways we know that it is good to merge. If we have commented out tests, that does not count as passing. Those should be turned on and the build should fail till they are fixed.

**Comment by samuzzal-choudhury** [comment]
@joshuawilson We run a minimal set of tests which is sufficient to verify the health of stack-analysis for different ecosystems.

@tisnik what are the tests that we are planning to add? I hope you remember that the integration tests in its full glory had slowed down Bayesian on staging environment completely because it bombards the system with many stack analyses requests and our PR checks were held hostage in that process :-)

**Comment by samuzzal-choudhury** [comment]
@tisnik changing the severity of this issue to P3 as we already have got a working set of minimal tests for stack analyses.

**Comment by joshuawilson** [comment]
@samuzzal-choudhury it's not a question of if you have some tests. This issue states that you have failing tests there turned off so the build would pass. That is why it should be highest priority.

**Comment by tisnik** [comment]
Fixed via https://github.com/fabric8-analytics/fabric8-analytics-common/pull/354
