### ISSUE TITLE
Che and Jenkins pods failing to start on prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1266]
The problem is that persistent volume claims (PVCs) are not being created. 

No logs are written - errors such as this are generated in the event list:
```
persistentvolumeclaim "che-data-volume" not found (repeated 7 times) 191 times in the last hour
```

[events.pdf](https://github.com/openshiftio/openshift.io/files/1435027/events.pdf)

**Comment by ldimaggi** [comment]
Note - I am seeing this problem with 2 separate user accounts.

**Comment by jfchevrette** [comment]
The PVs are all missing. I was unable to find out why because there are no related errors in the tenants events log. Presumably this problem occurred during the tenant initialization phase.

I was also able to create the PVs manually so it is not a quota issue or a storage backend issue.

Re-creating/initializing the tenant is probably the only way to fix this for now.

**Comment by rhopp** [comment]
If you are recreatign/initializing the tenants, please include user kkanova-osiotest1. We are seeing this too. Thanks.

**Comment by ldimaggi** [comment]
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/723

**Comment by jfchevrette** [comment]
The problem has been isolated to a misconfiguration of the StorageClasses on the preview cluster. We're looking into it.

**Comment by ldimaggi** [comment]
Solved - thanks - closing.
