### ISSUE TITLE
Codebase creation page - Filter search box results is wrong

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1346]
it always tells me 0 results regardless if it have matched results or not

**Comment by joshuawilson** [comment]
@ashumilova here is an issue for you to add to the refactor.

**Comment by ashumilova** [comment]
@joshuawilson ok. will do

**Comment by jiekang** [comment]
My understanding is @Rydekull  is referring to the codebases page in the openshift.io web ui where the results part of the filtering toolbar is wrong. See screenshot below for an example where Results is 0 instead of 1 (it's always 0 because of a bug in the code):

![codebase-results](https://user-images.githubusercontent.com/5430520/34534530-76befa1e-f08c-11e7-833d-2f8f98db5721.png)

If this is correct, I'd be happy to submit a fix for this.

**Comment by joshuawilson** [comment]
If you have the time, go for it.

**Comment by jiekang** [comment]
Closing as the fix has been merged.
