### ISSUE TITLE
Space information page

### ISSUE THREAD

**Issue by Rydekull** [openshiftio/openshift.io#1349]
When viewing your space its a bit unclear that the top menu is where you're supposed to find settings for that page. The UI-logic is a bit illogical. Especially since there are buttons and configurations at other places of the page.

When you are viewing a space, you also do not know who owns it by looking at the page. 

When viewing someone else's space, there are buttons to add work items, add to space etc. Despite not me being the owner of the space.

**Comment by joshuawilson** [comment]
@catrobson can you please add this to the Space design refactoring/upgrade.

**Comment by catrobson** [comment]
Thanks @Rydekull - I agree there is some confusion based on current design here.  We're already starting to think about how to improve many aspects of this, but your feedback is much appreciated to confirm our suspicions around how new users experience this.

**Comment by jiekang** [comment]
There has been developer work on disabling user actions of widgets when visiting a space you do not own so that issue is resolved.

It's still not clear who owns a space when visiting one. The only visible option at the moment is to check the URL. However, the new designs do cover this and are work in progress so I am closing this issue. Feel free to reopen if you think it's still valuable open.
