### ISSUE TITLE
Import repo wizard: UX revisited summary page

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#1365]
The summary page has been revisited to fit the multi-pojects import:
https://redhat.invisionapp.com/share/KDE940ZVQ#/screens/262045714

**Comment by joshuawilson** [comment]
@krishnapaparaju are you going to work this?

**Comment by catrobson** [comment]
We will be removing multi-repository adding from the import flow for the first revision because we do not support how to handle multiple repositories from an "application" standpoint.  The user will be importing one codebase to one pipeline for now.  I think this issue is now outdated and can be closed, and we'll update the launcher experience UI to handle multiple project import as we get to that stage. @qodfathr

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2058
