### ISSUE TITLE
fabric8.io pipelines stability

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1444]
The build pipelines, running on fabric8.io, go down too often and do not have enough support to keep them running for devs around the world.

**Comment by rawlingsj** [comment]
I'm assuming you mean Jenkins on GKE running the fabric8 pieplines?  Rather than the website fabric8.io?

Support for GKE is being picked up by the service delivery team (adding the SD team label) - BTW @joshuawilson a bit more information is required than this to help understand what's going on.  AFAICT this is related to a mattermost comment I saw that you had a 503 last night but then it rectified itself?

Anyways with SD supporting

**Comment by joshuawilson** [comment]
Thanks. Yeah, I saw several builds get stuck in the first stage and restarting didn't do anything. Usually that is when you go in and fix/restart something. 

Is the need to restart something you can fix? Or are we stuck with that issue?

**Comment by rajdavies** [comment]
Its not something we can automate unfortunately - going to close this
