### ISSUE TITLE
Provide audit history for all workitems

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#1468]
As a user, I want to view logs of all changes made to a workitem, so that I can establish accountability and track history.

The audit logs **must** capture the following:
- [ ] Date and time stamp
- [ ] User ID of the person making a change (all updated/writes must be captured)
- [ ] Details of the changes made to the workitem, clearly indicating old and new state

**Comment by bartoszmajsak** [comment]
Just my .2$ here - it seems to me like an architectural question rather than just a user story. We probably should think about events in the system which will let us not only capture changes like in this case, but also react on them (e.g. having 3rd party integrations through webhooks or any other mechanisms). Wit this audit log will be one of the consumers of events planner will emit.

**Comment by aslakknutsen** [comment]
I'll assume this is a UI story. The data is captured already (https://github.com/fabric8-services/fabric8-wit/blob/master/workitem/workitem_revision_repository.go) but needs to be exposed via a History API in some consumable format for UI.

**Comment by aslakknutsen** [comment]
@bartoszmajsak If this is more then UI yes agree. But data is being captured now and has been since day 1'ish as a temp solution until something more permanent comes in place.

**Comment by joshuawilson** [comment]
@catrobson @qodfathr do you want the history for work items to be a part of the planner or for the whole service? I can see it being used a lot in the planner but also having value external to it.

**Comment by qodfathr** [comment]
@joshuawilson let me answer it this way. I assume the audit is available via an API owned by the work item tracking service. This API, in turn, will be used by the Planner to display history details within a work item. But this should not prohibit some other part of the system from also displaying audit history. This is particularly true, because Planner does not even know about all of the work item types. (e.g., if the Pipeline system creates Pipeline WITs, no doubt it will also want to have an audit log display for those WIs.)

Does that help?

**Comment by joshuawilson** [comment]
That fits with my understanding, thanks.

So the Planner can build out a history UI for planner things.

**Comment by nimishamukherjee** [comment]
Audit history available on Prod.
