### ISSUE TITLE
Che status icon not displayed on production and prod-preview

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#1494]
Just spotted this today:

![screenshot from 2017-12-01 09-03-42](https://user-images.githubusercontent.com/642621/33486065-b190c10c-d676-11e7-8dc9-60650e917c9e.png)

But - Che is up and running:

![screenshot from 2017-12-01 09-04-00](https://user-images.githubusercontent.com/642621/33486072-b999a7ba-d676-11e7-9d2f-907fcbbe280f.png)

**Comment by ldimaggi** [comment]
Production:

![screenshot from 2017-12-01 09-06-35](https://user-images.githubusercontent.com/642621/33486138-fe0ea076-d676-11e7-8d9f-e39453034356.png)

**Comment by ibuziuk** [comment]
Closing since this is expected due to multi-tenant migration:

https://github.com/openshiftio/openshift.io/issues/1423

https://github.com/fabric8-ui/fabric8-ui/pull/2268

workshop document is also updated - https://docs.google.com/document/d/1KsV8oHRe7DYCVCMfVrB2yd3hU4iBi11YI5MyuXoozQw/edit#heading=h.w6vdcug5aer9
