### ISSUE TITLE
Research: Consider using ngIf for deployments card collapsible portion

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1516]
The deployments cards have a collapsible portion that is initially not shown. At the moment, these elements and their respective js code are executed though not initially shown. It is possible to use ngIf to not load these elements until the collapsible is actually expanded. The performance impact should be analyzed in order to decide whether or not to do this.

**Comment by c-koehler** [comment]
@jiekang here are the results:

---

Tried profiling by changing
`<pfng-chart-sparkline [config]="config" [chartData]="data"></pfng-chart-sparkline>`
to
`<pfng-chart-sparkline *ngIf="!collapsed" [config]="config" [chartData]="data"></pfng-chart-sparkline>`

These were the results:

**Eager loading:**
![eager-load](https://user-images.githubusercontent.com/33262856/33720924-7311c6c6-db33-11e7-8196-03dbdfe95dec.png)

**Lazy loading:**

![lazy-load](https://user-images.githubusercontent.com/33262856/33720936-7b0aba4a-db33-11e7-866a-dae8f075f4ae.png)

**Summary:**
When the page eager loads, it takes approximately 2000ms before it finishes rendering, whereas lazy loading by using `ngIf` takes approx 300ms.

Opening a tab with the chart introduces a noticeable warmup time (even without profiling, just from a UX perspective) which makes it feel a bit clunky, but maybe this can be remedied by not having it fade in? The profiling shows that each click on the lazy loaded one gives a 750ms load period for each image we show, whereas the eager loaded one is loaded very quickly, what looks like anywhere from 50-100ms per click. It's basically instant for user perception and feels pretty responsive.

How many do we plan to have on each page? If we ever go over 20, maybe eager-loading with pagination would be a viable strategy? My only worry is how bulky it feels when you click one of them.

I checked to see whether it was angular being laggy or if it's the chart itself, so I replaced the chart with something else, and it was instant when I clicked. I then tried opening and closing the tab multiple times, and it's instant to load after that, so it looks like the initialization phase of the chart is the part to blame.

The thing together that makes it probably feel worse than it is would be the fade in. The click itself has some noticeable lag to it, however after the delay of it loading, then there's the fade in which makes it look like it takes even longer to load. I wonder if it'd feel more acceptable if it just instantly appeared without the fade in? Though maybe this is native to patternfly and there's nothing we can do. The fade in isn't seen either when it's eager loaded. This won't stop the initial click from being perceptibly slow, and of course slow is relative since its ~750ms (and sometimes it feels faster once the first few components have been loaded) which maybe customers are okay with.

**Comment by jiekang** [comment]
Thanks for looking into this.

@c-koehler Can you verify whether or not the chart directive is reloaded if you collapse and expand a deployment card repeatedly? I think we should stick with eager loading for the time being. We will just have to make sure that the loading of the charts doesn't block anything else unnecessarily.

As an aside, there are definitely improvements that can be made to the patternfly sparkline chart implementation to make them load faster. However work on this would be in the patternfly-ng project and is low priority in my opinion.

**Comment by jiekang** [comment]
Also, the design will eventually have at minimum 4 charts per card. This is significantly different from the current iteration so we should look at this again once that's done.

**Comment by c-koehler** [comment]
@jiekang To repaste a link from an IRC discussion, [this](https://stackoverflow.com/questions/43034758/what-is-the-difference-between-ngif-and-hidden) indicates that it would recreate the chart every single time.

**Comment by jiekang** [comment]
@c-koehler I think using *ngIf would not be viable if it recreates the chart every time. If there's any way to delay loading but not have it recreate, that would be great.

When you get time, could you do the same profiling you did earlier with the latest work? It has more charts now... As well, if you can, I'd be interested in seeing CPU and Memory usage of the deployments page. I'm worried the page is 'bloated' in that manner; I suppose any optimizations here could be done in the farther future though.

**Comment by andrewazores** [comment]
I'm investigating the memory leak we seem to be experiencing, and putting an `<ng-container *ngIf="!collapsed">` around the contents of the collapsible div of the deployment cards seems to stabilize memory consumption while the cards are all collapsed. This does lead to a slightly noticeable fade/pop-in effect of card body contents when the cards are clicked, but the page performance is significantly improved.

I think using this technique (keeping card detail contents out of the DOM until really needed) is really the way forward, since doing otherwise entails keeping C3 charts in the background updating invisibly, which is what seems to cause our performance issues. The good news is that this simple technique keeps the card components still polling for live data from the service, which means that the sparkline chart will display up-to-date data when it is loaded and inserted into the DOM.

Bounding the chart data should help reduce the performance impact of the cards even further.

**Comment by jiekang** [comment]
I examined the Openshift collapsible cards and it looks like they use *ngIf as well. The elements do load very quickly though so I suppose we need to make sure our charts and elements load into initial state as fast as possible, delaying adding data to later. Or rather, just make sure we aren't delaying rendering waiting for initial data to come in and be processed.

**Comment by andrewazores** [comment]
I think we're already doing okay on that front - we just need to make sure that the component sets an initial data set for the chart, even if that data set is empty. This should allow the chart to render ASAP once its card is expanded, even if the first service update has not yet occurred and there is no data history built up in the card component.

Adding `transition: { duration: 0 } }` to the chart configs helps noticeably with the visual of the chart taking time to appear, but it does also mean that there is no animation when new chart data is added. Do the Openshift charts have data update animations? How many charts do they display per view?

**Comment by c-koehler** [comment]
@jiekang @andrewazores After checking out the patternfly chart data limiter (PR coming, everything is working but doing a cleanup) and running the chart data limiter, I'm no longer getting any memory leaks, which is good.

The way I tested it was to run it without my change, and noticed the RAM just kept leaking 10 megs/sec, then I applied my patch and the memory didn't go anywhere.

Hopefully this means the memory issue is solved.

**Comment by andrewazores** [comment]
@c-koehler what was the maximum length of the data sets with your patch? It makes sense that this would stop the leaking (since it's probably not truly a leak after all - just unbounded chart data), but I still think that using ngIf to remove the charts from the DOM when they aren't visible will lead to a much better page performance, especially on slower clients.

**Comment by c-koehler** [comment]
@andrewazores @jiekang Here is the report:

Viewing the deployments page with 6 cards (where right now we have 2 sparkline's each) will consume enough memory to have chrome crash after 9-10 minutes of usage on my machine. `htop` reports it using 10 megs/sec for 12 charts. Chrome dev-tools reports less but it still grows, the charts show an unbounded growth

Having the sparkline charts be reset by having `ngIf` destroy them will halt the unbounded growth, and in some cases return the memory (but not all of it). For the most part, this tends to have it stop at whatever memory it is using and grow no further. The memory itself is not returned completely though... it looks like it does garbage collect some stuff but whenever you close and open it, there's still a lot of memory that is consumed (cached?) in the browser.

Further, using `ngIf` to hide the charts... page responsiveness goes from "chugging" to normal browsing speed. The charts themselves after 15 minutes start to have transparency issues (meaning: lags while loading a lot and only draws part of the transition from 0% opacity to something like 20% opacity, but halts there instead of proceeding to 100%).

After looking into the browser heap (by memory snapshots when it's using 3-4 gigs of memory) it seems like a lot of closures were consuming a ton of memory, along with arrays.

Note that the current limit of 15 minutes that we have on the sparkline does in fact work if you can allocate ~4 gigs of ram for it (which is dangerously close to the chrome crashing limit of what appears to be 4.2 gigs), of which I cannot do a memory analysis at that point without chrome breaking, so I have to do a memory analysis before 15 minutes to get any insight. This of course is with 6 cards and 2 sparklines each, this is probably doable if you have at most 2 cards.

Therefore `ngIf` is a great way to prevent the memory usage from spiralling out of control (especially if there's >= 6 cards) but it doesn't unfortunately relieve the memory burden directly when the charts are closed and ngIf destroys the sparkline.

**Comment by andrewazores** [comment]
Nice report, thanks.

If the memory is not fully returned when the card details are destroyed (collapsed and removed via ngIf), then that sounds like we are actually leaking something in the real sense. We'll have to investigate what exactly that is. I'd suspect some chart event handlers or something along those lines, but that's just a hunch.

For the meantime - and preferably, before we open this area up for general access (@joshuawilson), limiting the data to 15 minutes and using ngIf to remove hidden charts should be the minimum we do, IMO. Afterwards we can do a deeper dive into any leak that still remains when removing charts or other smaller optimizations.

Regarding the chart opacity issue - can you test this with `transition: { duration: 0 } }` added to the chart configs to disable animations?

**Comment by c-koehler** [comment]
@andrewazores 
```Did you try manually triggering a GC in your browser's devtools to be sure that it's really not able to reclaim the memory?```

Yes I tried the `Collect Garbage` button to see if I could reclaim any memory, sadly it didn't help reclaim anything.

```I assume this testing is being done with the default service poll rate of 5 seconds with mock data? ```

Yes, that should help a lot too.

```Regarding the chart opacity issue - can you test this with transition: { duration: 0 } } added to the chart configs to disable animations?```

Unfortunately the animation removal didn't help anywhere, instead of it displaying the "half transparent" version it will just (when the memory is heavily consumed) draw nothing and then the graph will come into existence 10 or so seconds later. The memory issue is something I'll bring up with the patternfly team and see if I can investigate anything since I'm really interested in why this is happening. Plus that might be able to directly help https://github.com/openshiftio/openshift.io/issues/1709 as there's a solution I have that would potentially gain benefit from solving the memory issue.

**Comment by jiekang** [comment]
@andrewazores @c-koehler With https://github.com/fabric8-ui/fabric8-ui/pull/2359 merged do you think this issue can be closed? Is there anything else under discussion here?

**Comment by andrewazores** [comment]
@jiekang I think that wraps it up.
