### ISSUE TITLE
"OSIO Getting Started" documents should be in adoc / md format

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/openshift.io#1559]
Currently "Getting Started"[1] document is stored as pdf. Since it is updated very frequently there are quite a few problems with this approach:

- repository is ballooning. The doc is ~ 20Mb and even minor change in it will add extra 20Mb to the repo size. Basically, after a few dozens of doc update checkouting the repo would be sufficiently slower
- difficult to edit
- difficult to review

IMO, it would be great to switch to adoc format:

- no problems with repository ballooning
- easy to edit 
- easy to review
- Github preview by default 
- easy to import to html / pdf etc via asciidoctor [2]

Great example of this approach is blog for JBoss Tools website [3] - https://github.com/jbosstools/jbosstools-website/tree/master/blog

[1] https://github.com/openshiftio/openshift.io/blob/master/src/assets/documents/osiogettingstarted.pdf
[2] http://asciidoctor.org/
[3] https://tools.jboss.org/blog/

**Comment by joshuawilson** [comment]
@qodfathr can you answer this one?

**Comment by rkratky** [comment]
@ibuziuk, the docs team has an Asciidoc-based docs repo already in place: https://github.com/fabric8io/fabric8-online-docs -- in that repo, CI/CD is already set up and running, PDF builds are automated, etc.

Right now, we're working hard to have the docs satisfy all that Todd needs from the Getting Started doc, so that we can ask Todd for a review and eventually switch to the Asciidoc-based ones. Shouldn't take long, hopefully.

**Comment by qodfathr** [comment]
Closing as this work is well underway and will be deployed in the not too distant future. Thanks for the feedback, @ibuziuk!
