### ISSUE TITLE
Redirect after update tenant

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#1566]
When a user clicks the `update tenant` button on the update profile page, they get no feedback. Please redirect them to the `_home` screen.

**Comment by joshuawilson** [comment]
@catrobson does this user flow work? OR should we do something different. This is really just a fix to a confusing flow to a button that hopefully will not stay.

@c-koehler since you have been working on redirects, can you take this on when you have time?

**Comment by c-koehler** [comment]
@joshuawilson Attached is a fix that redirects. It also contains a message, but I can remove that if we don't want the user to be notified. I added it since redirecting to the home page might look confusing or like a bug, which now it should both redirect and notify them.

I went looking through the WIT to see how it handles status responses. I don't have the local WIT working yet so I can't trace this to make sure, but it looks like the response comes from [this line of code](https://github.com/fabric8-services/fabric8-wit/blob/b0e3376363809d7e0ea311232a4a770f672010d4/controller/user_service.go#L29), which would mean that it always returns status code 200. For any future proofing I just made sure that it only returns 200 (in case maybe one day if there's something non-200, it won't silently fail).

**Comment by c-koehler** [comment]
Update: After clicking [Update Tenant] this is where you end up (and get the notification)
![success-msg](https://user-images.githubusercontent.com/33262856/33773497-1075921c-dc06-11e7-86d1-d618e4e82751.png)

**Comment by catrobson** [comment]
@joshuawilson @c-koehler Shouldn't we give them the toast notification on the profile page rather than redirecting them to _home?  How long does the action take before the user is shown the toast notification?  

I realize we don't want to invest a lot of time here so I'm also ok with just moving forward if you want to limit time on this further.  Sorry I missed this convo the first time around.

**Comment by c-koehler** [comment]
@catrobson @joshuawilson This can be done as well, I'm okay with making it delay for some amount of time (a few seconds? what do you think would be best?) before changing, adding it to my changes would take a few seconds at most.

It also would be easy to leave them on the current page as well with a message. I'm ready to change this to whatever you guys want if needed.

**Comment by catrobson** [comment]
Ideally I'd like to see us turn the "Update tenent" button into a spinner with text, and then a complete indicator that goes along with the toast notifications also showing when it is complete, all leaving the user on the update profile page rather than navigating them away from it.  Quick and dirty mockup of the 3 states of the button area:

![image](https://user-images.githubusercontent.com/3739227/33846721-0260e010-de76-11e7-963b-946755c07fd0.png)

**Comment by c-koehler** [comment]
@catrobson I've done the following updates, however can I get a comment on whether it should look like the following or not:

![tenant-update-waiting](https://user-images.githubusercontent.com/33262856/33900094-5fa28128-df3b-11e7-81ba-9d300252b6e9.png)

![tenant-update-good](https://user-images.githubusercontent.com/33262856/33900097-62433422-df3b-11e7-970c-b9d3884ffbe3.png)

![tenant-update-failed](https://user-images.githubusercontent.com/33262856/33900099-6582aad2-df3b-11e7-9200-f1e11682fb83.png)

_(note that these are rough examples, proof of concept that the underlying code works, and also would be styled better)_

Further, do we want to keep the updating tenant text? I'm not sure if I was supposed to replace the spinner/status text with the final result -- which was done in the images -- or if that is not the case and they're supposed to stay there? If so, then what would you like the text to say?

**Comment by catrobson** [comment]
@c-koehler 

Sorry that I wasn't totally clear about that! Could we do the status right under the update tenant button (and disable that button while the action is occurring), with these statuses below the button.  The spinner and 'updating tenant' would be replaced by success or failure message rather than staying present.

The placement then would be as follows (but with a disabled button while in spinning state):
![image](https://user-images.githubusercontent.com/3739227/33905011-3886d7f0-df4b-11e7-80a4-3b02b026399d.png)

Flow would be:
1. User clicks button
2. Button disables, spinner and 'updating tenant' message appear below button
3. Tenant update complete, either checkmark w/ success message or error w/ failure message shown below button in place of spinner and text.  At the same time the toast notification displays with a status update for success or failure.
4. The button is enabled again.  The user can navigate away from this page and come back, and no messages will be shown below the button.

Let me know if that works better or if you have any questions.  You can also reach out to me on mattermost (crobson)

**Comment by c-koehler** [comment]
@catrobson Here's an updated working example of the above:

![updating](https://user-images.githubusercontent.com/33262856/34696688-c271ceea-f49d-11e7-80f3-a821e05593eb.png)

![updated](https://user-images.githubusercontent.com/33262856/34696694-c3e98222-f49d-11e7-84ac-a0d38db00493.png)

![failed](https://user-images.githubusercontent.com/33262856/34696697-c622280a-f49d-11e7-9f6c-67af9c5e615f.png)

If you want them updated at all let me know (in case we want some pixel alignment, I can pad things if needed).

**Comment by catrobson** [comment]
@c-koehler Can we give the Check and X a bit of right-hand padding before the text starts, a little bit more like updating tenant with the spinner for padding between the icon and the text?  Otherwise looks good!

**Comment by c-koehler** [comment]
@catrobson Is this padding okay?

![updated-padding](https://user-images.githubusercontent.com/33262856/34744463-4b74cf40-f55b-11e7-9e10-746bf6d93f45.png)

![failed-padding](https://user-images.githubusercontent.com/33262856/34744465-4cbab39c-f55b-11e7-86cb-b7ae8cd900f2.png)

**Comment by catrobson** [comment]
Yes, thanks @c-koehler!
