### ISSUE TITLE
Licenses were missing for some packages for some of the quickstarters.

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#1646]
Licenses for some packages for quickstarter application's are not present because of which the license analysis getting failed. Please refer screenshot  for more details.
![screenshot from 2017-12-12 23-41-25](https://user-images.githubusercontent.com/7105965/33930401-ca2cf4c4-e012-11e7-8bfa-b672e26c4769.png)
cc:@miteshvp

**Comment by sara-02** [comment]
@miteshvp the license values are also missing from the staging graph. 
Missing for all versions for `io.vertx:vertx-config-kubernetes-configmap` and `io.vertx:vertx-config-yaml`. Missing for version `1.7.22` for `org.sl4j:sl4j-api`

**Comment by miteshvp** [comment]
@sunilk747 @sara-02 - are these license missing on production cluster?

**Comment by sara-02** [comment]
@miteshvp the stack report was generated at prod, and the graph check was performed at staging graph. So yes, the licenses are missing on prod as well as on stage.

**Comment by msrb** [comment]
> Missing for version 1.7.22 for org.sl4j:sl4j-api

I just checked and we didn't have proper data for this component in S3. @sara-02, it should be fixed now. Sorry about that.

**Comment by GeorgeActon** [comment]
@miteshvp is this a bug 
 if so what severity 
 whatbis the underlying cause
 have we taken an action to fix it?

**Comment by msrb** [comment]
@GeorgeActon if license analysis is failing because some components are missing license information, then it's a bug in my opinion. There will always be stacks with unknown components in them (private dependencies and so on) and therefore with no license information.

@sunilk747 when you say that the license analysis failed, you mean user sees some error message, or simply we weren't able to determine what the stack level license is?

**Comment by sunilk747** [comment]
@miteshvp Yes, the user get's the final status as failure.

**Comment by msrb** [comment]
Thanks @sunilk747 

@miteshvp please feel free to change the severity level

**Comment by miteshvp** [comment]
@msrb - I guess problem is while ingesting, we are for some reasons not able to capture licenses and hence it is not available in graph. This results in no recommendations from license scoring service and hence the message failure.
@sunilk747 - we need to change the message from failure to `unknown` since we do not know the license information with some message. Please handle this from license scoring part. 
And this is not a Sev-1 issue to me so Michal we are good.
cc @GeorgeActon

**Comment by msrb** [comment]
> I guess problem is while ingesting, we are for some reasons not able to capture licenses and hence it is not available in graph. This results in no recommendations from license scoring service and hence the message failure.

Yeah, this was a problem for `slf4j-api`, the license task indeed failed for that package - that should be fixed already. But it's not the case for other two vertx components. Those components simply don't have any license headers in [source files](http://central.maven.org/maven2/io/vertx/vertx-config-kubernetes-configmap/3.4.2/vertx-config-kubernetes-configmap-3.4.2-sources.jar), nor in [pom.xml](http://central.maven.org/maven2/io/vertx/vertx-config-kubernetes-configmap/3.4.2/vertx-config-kubernetes-configmap-3.4.2.pom). So we don't know what the actual license is.

But my point was: we can expect real-world stacks to be full of components with unknown licensing information. And the system should be able to gracefully handle such situations (simply saying "can't determine the stack level license, because <reasons>" would be enough in my opinion).

**Comment by sara-02** [comment]
@msrb agreed. We did not know that system would return failure even if one of the package has missing license, because this scenario was never encountered. Will create a separate issue to track the changes on the License recommendation level.

**Comment by krishnapaparaju** [comment]
@sunilk747 @miteshvp please close this issue as package licenses are covered for OSIO quick starts.

**Comment by sunilk747** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/48 solves this issue.

**Comment by miteshvp** [comment]
Closing this issue.
