### ISSUE TITLE
CentOS CI and f8a

### ISSUE THREAD

**Issue by pkajaba** [openshiftio/openshift.io#1724]
fabric8-analytics team currently uses CentOS CI for CI/CD. It's great and stable service. However, problem is that there is no process established (or we are not aware of it) how to promote changes of CI/CD configuration.

The developer has to open PR in https://github.com/almighty/almighty-jobs and then waits until somebody from service delivery team merges it, which can take some time. So the purpose of this issue is to track and discuss possible solutions. 

My proposal would be to grant permission to push into almighty-jobs to at least one of f8a developer, so we can speed up this process.

@krishnapaparaju @tisnik

**Comment by joshuawilson** [comment]
Shouldn't this be a question for the SD team, since they own it?
cc @kbsingh @pbergene @jfchevrette @vpavlin

**Comment by pbergene** [comment]
Yeah, I don't have access to that myself and I don't think JF has. Need to try to sync with someone to see who actually has access to get an idea of the current situation and what is the intended process. That would be kb and vpavlin, both of who are on PTO, so this conversation will likely have to be resumed then.

**Comment by vpavlin** [comment]
People with access are Aslak, Konrad, KB, Mario, Alexey, Joshua and me. I am not aware of any existing rules about who should have access and who shouldn't. 

I'd say it makes sense for someone from f8a team to have push access - my suggestion would be @msrb  as he created most of the templates and jobs for f8a in there. 

@kbsingh any objections?

**Comment by pkajaba** [comment]
@vpavlin 's idea sounds good to me. @kbsingh what do you think?

**Comment by qodfathr** [comment]
Is this resolved, or is there more to discuss?

**Comment by msrb** [comment]
Not resolved yet.

I think the problem with devtools/CentOS CI is the shared JJB configuration in https://github.com/openshiftio/openshiftio-cico-jobs. Since all devtools teams share the single configuration file, we need to be very  careful while merging PRs. Bad PRs can break CI for everybody. So only very few people can merge PRs and thus modify CI configuration. It certainly feels like a bottleneck as it's often not possible to test CI changes locally, people just need to do their best, open a PR, find and bug somebody who can merge it, discover that there is a typo somewhere (after it gets merged), and do it all over again.

If nothing else, we should at least list all the people with commit rights who can merge PRs in the repository's README. I don't think most people know who can merge their PR.

Having team specific CI configuration files would allow us to relax the PR review process and more people could be granted commit rights. I am fine breaking fabric8-analytics CI as I can immediately fix it myself. I am not able to do the same for Eclipse Che CI, for example.

**Comment by kbsingh** [comment]
there is no clear way to enforce per-team scopes, I think we should use the testing mechanism listed in the readme file locally for anyone sending PR's. and use the validation in place now. 

Beyond that, +1 for listing the names of people who can merge there.

**Comment by mmclanerh** [comment]
closing, if people need merge access, list can be shipped as workaround.
