### ISSUE TITLE
Link to Web Console redirects back to openshift.io/_home

### ISSUE THREAD

**Issue by Katka92** [openshiftio/openshift.io#1799]
When trying to get to web console via link on page https://manage.openshift.com/ it does some redirects and ends on https://openshift.io/_home. Not sure, if it should end on openshift online dashboard page or on *-che namespace page. Can someone specify please?

**Comment by ibuziuk** [comment]
![image](https://user-images.githubusercontent.com/1461122/34712036-c0d260de-f521-11e7-873b-63f87b10e969.png)

@joshuawilson am I correct that `open web console` button should redirect user to prod openshift online cluster ?

**Comment by joshuawilson** [comment]
@Katka92 do you have an account on  https://openshift.io? Were you trying to access it or go someplace else?

If you can tell me what you want to do or happen and then what you observed, we can better help you.

**Comment by ibuziuk** [comment]
@joshuawilson for me when I click on "Open Web Console" it redirects me to  https://openshift.io/_home and I would expect to be redirected to prod openshift online (starter-us-east-2) dashboard

**Comment by joshuawilson** [comment]
But the page you posted has `OpenShift.io` on it as the target. Why would expect to go any place else?

**Comment by ibuziuk** [comment]
@joshuawilson but I was redirected to it from https://manage.openshift.com/ 
I guess this link was used by @Katka92 in order to access prod openshift online cluster before
The issue is labeled as `question` since I am not 100 % sure what is expected behavior, but for me the navigation looks broken and I would expect to be redirected to prod openshift online console, not to https://openshift.io/_home

**Comment by joshuawilson** [comment]
Yeah, I'm not sure either. That is why I was asking for clarification.

**Comment by camilamacedo86** [comment]
WHAT: Re-direct to fo to home page after the login is a bad experience
WHERE: After the registration 
WHEN: Click on the button "Open Web Console" has a redirect to an openshift.io page and a check if the user is logged or not, if yes has a new re-direct to the home page.
IMPACT: It shows as has an error and makes the user confused. Also, if the user has a low/poor internet connection it will show as an error since the redirect will take too long to be done. 
BEHAVIOUR CHECKED AT: 10/jan/2018

**Comment by joshuawilson** [comment]
He currently working on updating the registration process to streamline it. 
cc @catrobson

**Comment by alexeykazakov** [comment]
https://manage.openshift.com/ is part of OpenShift Online Registration app. OSIO doesn't control this. I'm not sure why it now pointing to openshift.io instead of OSO Web console (cc: @luciddreamz) but maybe it's actually the right thing to do for now? Users can damage their OSO namespaces if they go to the console before logging into OSIO after approval. So, maybe having links to the console in openshif.io only (currently the link is available in Create->Environment) is better until we fix OSIO user permissions in OSO so they can't create namespaces/project directly in OSO (and exceed quota)?

**Comment by qodfathr** [comment]
Agreed that this needs improving, and improvements are coming.

I think the real confusion stems from this. Depending upon what you've signed up for under the account you are currently logged in as, you can see two *subtly* different things in the UI, which do *radically* different things.

If you only have an OpenShift Online account, you'll see something like (note that it says *Starter:*):

![image](https://user-images.githubusercontent.com/16322190/34795586-c8a2289e-f620-11e7-8ce3-0d0e813f5937.png)

and the Open Web Console button opens the *OpenShift Online Console*.

If you have an OpenShift.io account, you'll see something like (note that it says *OpenShift.io:*):

![image](https://user-images.githubusercontent.com/16322190/34795617-e3a8c26a-f620-11e7-8083-b3b93a2ea1df.png)

and the Open Web Console button opens the *OpenShift.io console / application*. I believe that's where the confusion lies -- if you were expecting to see the OpenShift Online console, especially because you have another account and it does, in fact, go to the OpenShift Online console, I can certainly understand why you'd be surprised/confused by the current behavior.

It does not help that (1) the two dialogs/tiles look almost exactly the same, (2) the both have a by-line of "For individual learning and experimenting," and (3) the both have a button labeled "Open Web Console."

In fairness to the team, this is really a consequence of us liberally and purposely reusing existing code and capabilities to advance through the pre-beta phase of OpenShift.io as quickly as possible. Most of these kinds of fit-and-finish issues should be addressed before the full service launch.

At least the two icons are (slightly) different. :)

**Comment by luciddreamz** [comment]
A few things here:

   1. Plan Name: This should have simply said "OpenShift.io" rather than
   "OpenShift.io: US East (Ohio)" - this is now updated in production.
   2. By-line: The by-line is DEFINITELY incorrect and I'll get that fixed
   ASAP. This should be something like "End-to-end cloud-native development."
   3. Open Web Console: This link goes to the web console of whatever
   service the card is for. In the case of OpenShift.io, this is the
   OpenShift.io web console.
   4. Icon: Hopefully we'll have better icons here at some point. We're
   currently using PatternFly's icon set. This should barely matter to any of
   us at this point given other priorities.

Oh, and OpenShift.io doesn't block OpenShift Online Starter anymore. I
mentioned this in a different thread.

Here's one of my accounts with subscriptions to all the currently available
plans/services (with the by-line corrected for .io, coming soon to prod):

​

​


Jacob Lucky
jlucky@redhat.com

**Comment by luciddreamz** [comment]
A few things here:

1. Plan Name: This should have simply said "OpenShift.io" rather than "OpenShift.io: US East (Ohio)" - this is now updated in production.
2. By-line: The by-line is DEFINITELY incorrect and I'll get that fixed  ASAP. This should be something like "End-to-end cloud-native development."
3. Open Web Console: This link goes to the web console of whatever  service the card is for. In the case of OpenShift.io, this is the  OpenShift.io web console.
4. Icon: Hopefully we'll have better icons here at some point. We're  currently using PatternFly's icon set. This should barely matter to any of us at this point given other priorities.

Oh, and OpenShift.io doesn't block OpenShift Online Starter anymore. I mentioned this in a different thread.

Here's one of my accounts with subscriptions to all the currently available plans/services (with the by-line corrected for .io, coming soon to prod):

<img width="1392" alt="screen shot 2018-01-10 at 4 34 21 pm" src="https://user-images.githubusercontent.com/928421/34797279-e7a6637c-f625-11e7-8ae7-9f93e613a042.png">

**Comment by luciddreamz** [comment]
Question - does anyone actually want this link to go to your OpenShift Online account directly, circumventing OpenShift.io? I was under the impression that you wanted to control the experience and linking over to the OpenShift Online web console related to the OpenShift.io account a bit more at the moment.

**Comment by joshuawilson** [comment]
I think the current behavior of linking to OSIO is correct.

**Comment by qodfathr** [comment]
Technically, an OSIO user has both, so I'd suggest that two tiles should be displayed, but I defer to @catrobson.

**Comment by alexeykazakov** [comment]
I would like to note again. Allowing users to access OSO Web console for OSIO cluster(s) is error prone. Users can access it without logging into OSIO after approval and create projects so OSIO will fail because it can't exceed quota. Until we fix this via proper user permissions I think we should keep OSO console links in OSIO only and management.openshift.io should link to OSIO.

**Comment by qodfathr** [comment]
@luciddreamz are you tracking an issue anywhere to fix the by-line for the OpenShift.io tile?

@alexeykazakov given the current state of things, I agree that we should not include a tile to get to the OSO linked to OSIO. (In other words, keep things they way they are today).

Going back to the original question of this issue -- I feel it has been addressed. We are basically seeing intended behavior, although we have a couple of TO DOs to clean stuff up. We'll track those in separate issues.

**Comment by luciddreamz** [comment]
@qodfathr The change (https://github.com/openshift/online-registration/pull/902/files) is currently in stage and will go out with our next release to prod, which should be this week.
