### ISSUE TITLE
[RFE] [UX] New Item - Enter Title - Improvements

### ISSUE THREAD

**Issue by hhovsepy** [openshiftio/openshift.io#1811]
Currently when adding a New Item by clicking "+ Create" button, the input of "Enter Title" seems like not mandatory input.

[Proposal] Improve it to have by default in edit mode with cursor on it and a sign "*" of required field.

**Comment by michaelkleinhenz** [comment]
Yes, we also encountered that issue. 

This will be different in the H train version anyway. The create button on the top will be removed. If you want to create a non-child WI, you use the quick add on top, add a title, then click "Create and Open" which takes you to the full detail dialog. In this scenario, the title will always be mandatory.

Also, this removes the somewhat ugly "select type" screen because you will need to select the type from the quick add.
