### ISSUE TITLE
Item Move to backlog - Remains on board

### ISSUE THREAD

**Issue by hhovsepy** [openshiftio/openshift.io#1825]
Task remains on board after "Move to backlog".
It is possible to to clock on Move several times and it logs success each time but does not move.

![screenshot from 2018-01-10 13-15-18](https://user-images.githubusercontent.com/604313/34772669-1a0a02aa-f609-11e7-8ed1-11845e9146a9.png)

**Comment by qodfathr** [comment]
I'm not sure this is a bug, but this is also reflecting an area of Planner which is changing, so the whole issue may be resolved when the new changes are releases. In any event, the reason why this does not look like a bug to me is because, on the left hand side, you have selected 'All', which means, quite simply, 'all work items'. Moving a work item 'to the backlog' simply means removing it from any iteration. But it's still a member of 'all'.

This would be a bug if, instead, you were focused on, for example, Sprint 1, you selected "move to backlog," and then it still remained on screen.

**Comment by qodfathr** [comment]
With the new Planner UI now rolling out, I do not believe this issue still applies as it is against the old UI. I'm closing, but feel free to either reopen or create a new issue if there is a concern.
