### ISSUE TITLE
Overlap on profile page when there are space with long names

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#1886]
![screenshot from 2018-01-15 20-17-08](https://user-images.githubusercontent.com/4716987/34942084-408cfd0c-fa31-11e7-956c-d1069ae52ce7.png)

**Comment by qodfathr** [comment]
This is part of a larger issue that resizing the browser down past certain widths causes various layout problems in OSIO. For example, on this page, if you make it even smaller, eventually (depending upon the size of the source image), your profile image can appear massive.

Related to #1443 ; there needs to be a Responsive UI epic.

**Comment by joshuawilson** [comment]
cc @mindreeper2420

**Comment by mindreeper2420** [comment]
@qodfathr @joshuawilson agreed - there needs to be an Epic for continuing to update responsiveness. There was a UX story on updating responsiveness of the Dashboards, but not other pages.

The User Profile page has updated designs, so that should be taken into account whenever this page is updated to fix responsive issues.

**Comment by aptmac** [comment]
The dropdown sizes to be the width of the longest space name, what if it's width were to be constrained? e.g., here it is with width: 50%
![fixed-size-dropdown](https://user-images.githubusercontent.com/10425301/39272366-b3b82e98-48a9-11e8-82fa-d20e8c401dfb.png)

**Comment by qodfathr** [comment]
Constrained with a tooltip and a horizontal scroll bar (for accessibility) perhaps?

**Comment by aptmac** [comment]
resolved in https://github.com/fabric8-ui/fabric8-ui/pull/2968
