### ISSUE TITLE
Check CSS scope for Deployments page

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#1888]
Angular 4 encapsulates views to their component s.t. a parent component's css does not affect child component's.

The Deployments page components should be checked for css that doesn't apply because of this. Whenever possible, the css should be moved to the component it applies to. If this isn't possible (e.g. donut charts have css applying to c3js classes), the component should use ViewEncapsulation.None, or some other technique so that the css applies.

**Comment by joshuawilson** [comment]
We need to discuss this with @mindreeper2420 @dlabrecq and @dgutride as the use of ViewEncapsultation has been an on going topic.

**Comment by mindreeper2420** [comment]
Dan, Dana and I recently discussed proper specificity and capturing components inside a naming convention that defines the component (something like `f8deployments-`). One of the major reasons View encapsulation is off is due to the need for overwrites and specificity issues.

Happy to have this discussion again, but it would probably best with all parties on a call.

**Comment by jiekang** [comment]
@mindreeper2420 To clarify the conclusion of the discussion, is the suggested path to use ViewEncapsulation.None in situations where we need to apply styles to child components?

**Comment by jiekang** [comment]
Closing this issue in favor of issues with specific tasks. For the most part, the deployments page is okay. Css scope has been updated in the donut charts: https://github.com/openshiftio/openshift.io/issues/1939
