### ISSUE TITLE
Getting jenkins deployment and namespace locked for users on OSIO

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#1900]
Currently users are able to modify Jenkins deployment and namespace and change everything.

It has been requested from the SD team that we would need to have this locked so users would not be able to modify this anymore.

This story would include : 

* Investigate and document how the current Jenkins deployment on OSIO, what is the workfow how it get created with which rights.

* What do we need to have to have the jenkins deployment and namespace locked so the user would not be able to modify it.

* Write integration tests to make sure this is locked on https://github.com/fabric8-jenkins/godog-jenkins

 @kbsingh @pbergene @rupalibehera @aslakknutsen  let me know if i have missing something on this story.

## Parent Fundamental
#2171 OpenShift.io is secure

**Comment by chmouel** [comment]
@sthaha i just have assigned you, hopefully we can talk about it sometime tomorrow at our meeting

**Comment by sthaha** [comment]
@chmouel  by
> Currently users are able to modify Jenkins deployment and namespace and change everything.

By namespace do you mean that the users are able to modify the openshift `<user>-jenkins` **project**? And by modify do you mean delete pvc, stop the jenkins service etc? 

Should they even have access to the openshift projects where all the supporting services / infrastructure are run -  like jenkins, che, planner on openshift?

**Comment by kbsingh** [comment]
@sthaha that is correct. We want to get to a point where we can isolate these pieces, they are not there now. Just re-iterating the ask at the moment is to scope up what work is needed to get there. Once we have that, we can then work back to schedule and prioritise the tasks.

**Comment by joshuawilson** [comment]
I don't think we want to create name specific labels as they will just pile up. We have `train/next` and have talked about changing that to `train/future`.

**Comment by maxandersen** [comment]
I don't see how name specific labels pile up. `train/next` require you to move labels constantly and you loose history anyway. with train/heather we have the same and can just delete the label when not relevant anymore.

**Comment by chmouel** [comment]
What about we use the ml and not this PR to discuss this? (labeling) 

  I merely applied what was in an email recommendation happy to change it to whatever you guys recommend it

**Comment by joshuawilson** [comment]
The Milestones won't work because you can have an issue in only one at a time, so it could not go in the sprint.

Let's use @maxandersen idea, we should be moving to Planner soon enough and it won't matter then.

**Comment by chmouel** [comment]
soon is a strong word :)

**Comment by joshuawilson** [comment]
haha, ok. How about, I have come to agree with Max. I will use it the same way.

**Comment by sthaha** [comment]
### Status Update

This is where we are with the task of locking down jenkins namespace. This is also a brain dump of how the roles and jenkins auth currently works.

Currently the `<user>-jenkins` namepace is configured to allow user to `view` and `edit` (rolebinding). The `edit` role allows them to fiddle around with jenkins deployment and hence removing the `edit` role would lock down the permission user has on this namespace and this is exactly what the [`commit`][commit] tries to do but it turns out that the [jenkins authentication and authorization plugin][plugin] maps these [roles to permissions][roles-perms] on jenkins and removing `edit` role leads to user losing permission to start a build and prevents them from deploying to prod. 
 
Please note that my knowledge may be incomplete (not the original implementer) so feel free to poke holes 

####  Solution - 1

After (@aslakknutsen and I) discussed with the author of the plugin - Gabe, the suggested approach was let `init-tenant` service after creating the namespaces
1.Create a ServiceAccount in `<user>-run` namespace say `jenkins`
2. Copy the secrets associated with the jenkins serviceaccount (created above) to `<user>-jenkins` namespace
3. mount the secret to say `/run/secrets/jenkins `
4. Configure or preconfigure (during s2i)  the plugin to read from the secret mounted in step 3

To me this seems a bit convoluted to me. Please comment if you think there is an easier way to do this (may be by sharing secrets between namespaces??) 

#### Solution - 2

Explore the option to replace the OSO login with Auth provided by OSIO. 


[commit]: https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/63/commits/106f6405d79ccb55afaf9d3ce959dac2544b1b68
[plugin]: https://github.com/jenkinsci/openshift-login-plugin
[roles-perms]: https://github.com/jenkinsci/openshift-login-plugin#openshift-role-to-jenkins-permission-mapping

**Comment by sthaha** [comment]
### status update 

We (@sbose78, Kishan and I) tried implementing the long term solution which is to switch to fabric8-auth for jenkins using the [`openid connect`][openid-plugin] but encountered issues with the plugin failing to authenticate and even with saving the configuration. 

I then tried the simpler solution-2 to edit the openshift-login-plugin to enable user with `view` role to have the [same permissions][edits] as the `edit` role. This worked pretty well. Now with this change you can remove the `edit` role from the user preventing from them fiddling with the jenkins namespace yet allow  triggering builds on jenkins. 

Please note that a bit more work need to be roll this out to production.

We also need to work on the long term solution which is to switch to `fabric8-auth` once it starts supporting authorisation as well. Until then we would have to maintain the fork of this plugin.


[openid-plugin]: https://github.com/jenkinsci/oic-auth-plugin
[edits]: https://github.com/sthaha/openshift-login-plugin/commit/9b7b0d69c53f43fc648c72b51f6bb7f6ecab02b1

**Comment by kbsingh** [comment]
does the auth team have an action item that reflects this ask from your side @sthaha ? if so, can we get that linked in here as well please.

Well done on the execution so far.

**Comment by sbose78** [comment]
@sthaha  I would need some well defined authorization requirements - that way we can ensure that the authorization needs are taken care of in our current design which is being implemented. I can rope in Todd + UX for validation once we have it.

**Comment by sthaha** [comment]
@sbose78 is there an example of a well defined auth requirement that you can point me to?

**Comment by sthaha** [comment]
@aslakknutsen @kbsingh FYI: all required PRs [149][1] [63][2] that implement solution 2 have been merged. I think we can start deploying the new jenkins. 

Please also note that deploying this will not remove any existing `edit` roles so those would need to be removed manually. 

[1]: https://github.com/fabric8io/openshift-jenkins-s2i-config/pull/149
[2]: https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/63

**Comment by rupalibehera** [comment]
NOTE: whenever the tenant wide update is done this would reflect then. As @sthaha said above the existing edit roles for the tenant will have to be removed manually. 
cc : @pbergene @chmouel

**Comment by rupalibehera** [comment]
From the `SaaS Changes 2018-03-07 16:00` email this has gone to production https://github.com/fabric8-services/fabric8-tenant/commit/f8ee8bb. 
The Manual edit roles removal is pending from SD side.

**Comment by pbergene** [comment]
Lovely, thanks!

**Comment by pradeepto** [comment]
@sthaha @pbergene What is pending in this issue?  If not, can we close this issue?

**Comment by pbergene** [comment]
There's only the removal of the edit rights remaining I think? As I understand the new tenant init should set up tenants without them?  If it's only the case of the removal left and you're giving me the +1 to proceed with that then we can close this and track the remaining task on the housekeeping issue.

**Comment by maxandersen** [comment]
is this still open ? 

@pbergene what housekeeping issue are you referring to ?

**Comment by pbergene** [comment]
Jenkins namespace is locked down so can be closed, -run and -stage envs still remain for build.  Status of che is last I heard waiting for SA logic in tenant services.

HK issue is 844
