### ISSUE TITLE
Work items presented in "My Work Items" on _home Dashboard link to wrong Space

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1920]
Link result in 404: https://openshift.io/aslak/openshiftio/plan/detail/4fd647fc-84c3-4929-a5f5-95cac8dfe999

The issue is from the openshiftio/openshiftio space.

Seems to be missing the correct Space and using UUID instead of Number

![screenshot from 2018-01-18 16-40-33](https://user-images.githubusercontent.com/132158/35106377-5884be24-fc6e-11e7-92ca-13400e3d23e0.png)

**Comment by joshuawilson** [comment]
@michaelkleinhenz are you aware of this?

**Comment by joshuawilson** [comment]
This may be related to #1928

**Comment by michaelkleinhenz** [comment]
No, looks like the component rendering the links there is outdated. The component is assembling the link in a wrong way:

platform/home/work-item-widget/work-item-widget.component.html:
´´´
<a [routerLink]="['/', loggedInUser.attributes.username, currentSpace.attributes.name, 'plan', 'detail', workItem.id]"
´´´
..it is always using the logged in user instead of the current space owner. Also the WI id is used instead of the name.

**Comment by michaelkleinhenz** [comment]
I think the WI service (or even the JSONAPI) should provide a ready made UI link for use by external UIs. Assembling the link is not a trivial task and may also change. Created a userstory for this here: https://openshift.io/openshiftio/openshiftio/plan/detail/1839

**Comment by nimishamukherjee** [comment]
@aslakknutsen this has been fixed on prod. Work items are displayed based on a selected space.
