### ISSUE TITLE
Create Area should set focus on the Name input field

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#1999]
![screenshot from 2018-01-24 02-44-45](https://user-images.githubusercontent.com/132158/35310250-c770808e-00b0-11e8-89df-724f9653c40f.png)

**Comment by chrislessard** [comment]
I've made a number of attempts to solve this, and believe we're going to need to do something about the ngx-modal dependency that this section of the code base depends on. It's source can be found [here](https://github.com/pleerock/ngx-modal) and you can see as by the README that it has been deprecated for some time. 

There are two components at play here, [areas-component](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/settings/areas/areas.component.ts) and [create-area-dialogue](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts). The later is rendered into view via ngx-modal, but is initialised when the page loads, so its not possible to set focus through it's ngOnInit or ngAfterViewInit. In other words, its not possible to solve this program until the modal has been shown, which presents another problem. 

I've tried hooking into ngx-modal through its onOpen input property, but at the time that onOpen is evaluated, the inner create-area-dialogue isn't actually defined yet. @jiekang and I were a bit confused by this, since it didn't appear to be the case that create-area-dialogue's onInit was being called before the modal was opened - it's most likely because ngx-modal surrounds its contents with an ngIf in it's template, leading to weird nesting that's causing Angular to load components in a strange fashion. Even if that could be resolved, however, there's an asynchronous call in the modal's open call [https://github.com/pleerock/ngx-modal/blob/master/src/Modal.ts#L145](url) that will cause problems and override the focus we are trying to give to the input, most of the time. 

I don't think it's a good idea to hang onto this dependency, at the very least we should probably consider forking and making a small change that resolves this sort of issue. Or, alternatively, we could use a PatternFly modal in this particular case instead. Thoughts ?

**Comment by chrislessard** [comment]
@qodfathr a fix for this was merged. Can this issue be closed ?

**Comment by jiekang** [comment]
I'm sure you can close this at your discretion. If it turns out to still be an issue, it's easy to reopen.
