### ISSUE TITLE
Two values come through every time the deployments poll for memory data

### ISSUE THREAD

**Issue by c-koehler** [openshiftio/openshift.io#2037]
When getting the MemoryStat (and possibly cpu/network too, haven't checked) it will poll twice, or the observable fires twice. If you place a `console.log()` statement inside the subscription for `getDeploymentNetworkStat` you will see its fired twice.

It should only be firing once.

An example of a timeline would be (with the polling rate of 30 seconds, which may be 60 seconds now):

MemoryStat emitted at 0 seconds
MemoryStat emitted at 30 seconds
MemoryStat emitted at 30.2 seconds
MemoryStat emitted at 60 seconds
MemoryStat emitted at 60.2 seconds
...etc

It should instead look like:

MemoryStat emitted at 0 seconds
MemoryStat emitted at 30 seconds
MemoryStat emitted at 60 seconds
...etc

## Impacts
- [ ] #287

**Comment by qodfathr** [comment]
Is this impacting the proper display of data to the user? If not, I might argue for SEV3 vs SEV2.

**Comment by c-koehler** [comment]
@qodfathr The user will get proper data and the charts will look normal for the most part, they might not notice it either since it will likely emit the same data twice and just create a horizontal bar.

**Comment by andrewazores** [comment]
Pretty sure this is happening because of the `combineLatest` here:

https://github.com/fabric8-ui/fabric8-ui/blob/93c0327037011e2327b63eace36470429cd3018f/src/app/space/create/deployments/services/deployments.service.ts#L216

What's happening is that this Observable needs data from two different sources - the per-environment quota, and the per-deployment timeseries stats. Each of those sources independently updates because they come from separate and independent HTTP requests to different paths. Because the CPU and Memory timeseries Observables need to return results to UI components which join data from both sources into one data structure, and those sources are both asynchronous, the Observable ends up emitting an event with the latest stats and the latest quota whenever either one updates.

If you check the Network tab in your browser's debug tools I believe you'll see that each request is only going out once per poll cycle, so it's not a backend DDoS sort of issue.

It will have some very minor effect on the display of data to the end user, but likely not noticeable on the chart and never actually incorrect.

There may be some other Observable joining operator that is more suitable than `combineLatest`. Alternatively, a `distinctUntilChanged` on the quota stream should also mitigate this issue.
