### ISSUE TITLE
Bayesian Stack Report: does not update during pipeline runs

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#207]
https://screencast.com/t/gATQgadjjBV
shows 2 deps but there are 3, I added one, a bad one
https://github.com/burrsutter/vertxbasic23/blob/master/pom.xml#L44
and no recommendations are offered, even with the bad dep added to my pom.xml 
Note: this dep is flagged in Che, just not during the pipeline run

**Comment by burrsutter** [comment]
Che while editing pom.xml 
https://screencast.com/t/6fuHDG0L9

**Comment by burrsutter** [comment]
A gist of the Jenkins output
https://gist.github.com/burrsutter/44cfcf4249e4b951afd772c27a71969e
this run failed, I will restart Jenkins and try again

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-recommender#242

**Comment by samuzzal-choudhury** [comment]
@burrsutter because of the scope "import", the dependency logback-core 1.1.10, the stack analysis could not detect the appropriate reference stack and hence no recommendations were generated. 

Removing the scope should get you the recommendation that you are looking for.

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/17740190/26924102-f027f092-4c61-11e7-8e5e-75c5fabf0471.png">

Recommendation in space dashboard:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/17740190/26924149-2df344f8-4c62-11e7-9c9b-519c2281ab5e.png">

**Comment by burrsutter** [comment]
Import removal was the trick...now just make the Che and build/pipeline experience the same, I should not get a warning/recommendation in one but not the other - at least on the same exact thing in the pom.xml

**Comment by samuzzal-choudhury** [comment]
@burrsutter can we close this issue?

**Comment by joshuawilson** [comment]
Closing this issue as it appears resolved. @burrsutter please reopen if needed.
