### ISSUE TITLE
Operational control

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2071]
An organization can provide, on a user-by-user or role-by-role basis, operational control within OpenShift.io, so that only users may only perform the operations to which they are authorized.

## Parent Scenario
#2068

**Comment by maxandersen** [comment]
would be good to define the boundaries of openshift.io here - i.e. to clarify how these operational controls is expected to map over to operational systems (i.e. openshift online or other) if at all.

I assume they don't (as the user/security models don't map/work across multiple clusters) but since app/deployment controls literally are exposed in openshift.io we do need to be clear on wether those operations in the UI are considered part of what is managed.

**Comment by qodfathr** [comment]
@maxandersen agreed. This is really just scoping stuff that's functionally inside of OpenShift.io itself. As an analog, a lot of people use GitHub and deploy to AWS. If you have an org and private repos in GitHub, an admin has some level of control over the org and repos. But GitHub provides no controls over access to AWS. Same kind of thing here.

**Comment by qodfathr** [comment]
Moved to OpenShift.io: https://openshift.io/openshiftio/openshiftio/plan/detail/2037
