### ISSUE TITLE
Anonymous user should see features as `released` ie: Production only

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2091]
# Description
As a user not logged-in on OSiO I should be able to see features as if my user consent is set to "production only: ie: `released`.
* If a feature is toggled off completely bu the PM => not visible in the menu.
* If a feature is beta/experimental => visible with banner asking me to log-in to accept experimental feature.
* if a feature is released =>visible without banner
# List of tasks:
- [x] toggles-services should not reply by `401` when user not logged-in but return a response where `user-enabled` is nil
- [x] UI should handle `user-enabled` nil
- [ ] `toggles-service` should verify the token if any exists in the HTTP requests (https://github.com/fabric8-services/fabric8-toggles-service/pull/35)

## Associated defects
- [ ] #1501 Can not see things like planner when not logged in

## Parent Fundamental
#2036 OpenShift.io should be Testable in Production

**Comment by maxandersen** [comment]
does this not mean that features like viewing workitems are hidden for anonymous users ?  

I would expect we at least have the ability to allow read-only views to essential features (even if experimental).

**Comment by corinnekrych** [comment]
@maxandersen yes atm with the latest PR on toggles-service, no `401` is returned for anonymous user but as we don't have the user the `user-enabled` field is false therefore the ui don't know which user consent where on and propose the user-consent page. If we want a special case for anonymous users `toggles-service` ned to return the information whether or not the user is logged. cc @xcoulon 
@qodfathr do we want a special behaviour for anonymous user or just the same behaviour than viewing `Released`?

**Comment by xcoulon** [comment]
well, I understand @maxandersen's concern about anonymous users not being able to use a feature without login, but I think that if we return user-enabled: true for anonymous users, then we'd reverse the usage of toggles: instead of enabling a feature for a logged-in user, we'd enable all unreleased features unless users log in and update their profiles, which may seem wrong. Besides: when planner is finally "released" and we're not in wait-list mode anymore (and thus, ready to accept open-source projects and any user), this question will be obsolete, IMO. In the mean time, I think we should wait for @qodfathr's decision on this.

**Comment by qodfathr** [comment]
Yes, this means the Planner is hidden from anonymous users. All the more reason to get it into a released state. I really think this is a point-in-time issue. Once we've got all of the base features promoted to the released state, this concern will predominately go away.

**Comment by qodfathr** [comment]
When I go to https://openshift.io/openshiftio/openshiftio/plan, I see work items when I am not logged in.  Although it was hard for me to notice, there was this banner text:
![image](https://user-images.githubusercontent.com/16322190/36113006-60f3efbe-0ff9-11e8-961b-9b933ac83cb7.png)
1. I should not be able to see the planner at all
2. I'm really not sure what that banner text is trying to tell me. Or, more accurately, I think I know the intent, but the wording is very awkward.

Also, when I then click on the Create tab, I'm immediately redirected to the marketing home page.

I'm not reopening this issue yet, because I do not know if these problems are directly related to this issue, or are new issues in other parts of the system. FWIW, this feels like something the platform should be handling transparently across OSIO.

**Comment by corinnekrych** [comment]
@qodfathr pls retry, UI was not deployed on PROD. this is now fixed cc @joshuawilson

**Comment by corinnekrych** [comment]
@qodfathr as per the `create` route it has always redirected to login as this menu give access to writable actions. If we need to change that behavior pls log a separate issue.
