### ISSUE TITLE
In the Deployment page, a status of running is displayed before the app is actually reachable

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2113]
When an app is deployed, its status is displayed as running when the app's deployed pod is running, but this is before the app itself is actually reachable.

![screenshot from 2018-01-30 10-26-15](https://user-images.githubusercontent.com/642621/35575792-4f81a148-05ab-11e8-9c6e-d18411a10502.png)

**Comment by jiekang** [comment]
Currently, the status only reflects the status of the Pod and even then, isn't entirely complete. It's behavior will be updated as more API gets merged into fabric8-wit

Application status is application specific and could present some issues in displaying something useful. In practice, Openshift allows users to attach readiness or liveness probes to their application. The most basic is an http endpoint which Openshift makes requests to in order to determine application status.

It would be possible to augment the status to also draw from the readiness or liveness probes (if available).

**Comment by qodfathr** [comment]
#508 is related, as this same issue was observed on Applications screen and Pipeline screen. (In #508, you'll find several other related issues covering those cases.)

**Comment by ldimaggi** [comment]
This is still an issue as of June 7, 2018.

**Comment by ldimaggi** [comment]
This is still an issue as of December 1.
