### ISSUE TITLE
Analytic reports for Wildfly Swarm boosters are empty

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2126]
See attached screenhot:

![screenshot from 2018-01-31 09-43-58](https://user-images.githubusercontent.com/642621/35629894-c9561e0a-066d-11e8-97a4-d400ee76e430.png)

**Comment by krishnapaparaju** [comment]
Thanks Len. Work related to supporting WF Swarm is being tracked as adding a 'feature' here at #2090

**Comment by GeorgeActon** [comment]
@krishnapaparaju this is actually failing fairly gracefully but we should probably rethink the comments we display in a scenario like this. 
For example the usage outlier comment should robablyindicate no data available instead of all your components work well together

**Comment by GeorgeActon** [comment]
@sivaavkd Please follow up on this.

**Comment by sivaavkd** [comment]
@sara-02 - since the original reported bug is a feature and being tracked as #2090 , let us track this issue to update the message for "usage outliers" card when we don't support an ecosystem.  If we dont have a text to show, we can ask @Preeticp

**Comment by sara-02** [comment]
@ldimaggi This is an error on the old UI, can you please check the new stack-report UI and let us know if your concerns are still valid or not?
Also, @GeorgeActon it is possible that even with Kronos being able to process wildlfy, we find no outliers. In that case we need 2 messages, one to display when there is no outlier because the system cannot understand the dependencies in the first place. Other is when the system does understand the dependencies, but still no outliers were found.

**Comment by ldimaggi** [comment]
Verified in production - closing.
