### ISSUE TITLE
Show deployment quotas on cards instead of environment quotas

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2183]
The deployment cards currently show the environment quota limits alongside the charts for memory and CPU of the deployment. Instead, these should show the quota that the deployment itself is taking from the environment quota.

E.g. the stage environment has a 1 GB (1024 MB) Memory limit. An application with two pods deployed is taking up 512 MB of the limit, 256 MB per pod. The deployment card currently shows actual usage versus environment quota, 128 MB of 1024 MB, but should instead show actual usage versus pod summation quota, 128 MB of 512 MB.

This would provide users the information to answer: How much of the environment's quota is my application taking?

**Comment by joshuawilson** [comment]
I think it might be useful to show the total someplace on the screen.
@catrobson can you have someone look at this?

**Comment by andrewazores** [comment]
The bottom "Resource Usage" panel shows cards with the totals for each environment still, but the bug is that each individual deployment card shows those same numbers as its own upper limit. So if you're on OSO Starter and have 1GB of memory in your Stage environment, the Stage card will tell you you have 1GB of memory, and a health-check-example deployed in Stage with 1 pod will tell you that that deployment is using say 150MB of 1GB. Instead, the card for health-check-example in Stage should read 150MB of 512MB, since that's all that's actually available to that deployment and its single pod.

**Comment by andrewazores** [comment]
![screenshot-20180208091030](https://user-images.githubusercontent.com/3787464/35977056-0e1f97ee-0cb0-11e8-974b-5c3d9485ebcd.png)

Here's an example showing the current state. The Environment card shows that 512/1024MB of memory are used, but the individual deployment with one pod is showing 149.8/1024MB. The deployment should be 149.8/512MB.

**Comment by mceledonia** [comment]
If I am understanding correctly it sounds like it would be more helpful to have the deployment cards contain the usage versus pod summation quota, instead of the current design of usage versus environment quota as per @jiekang's request. This makes sense to me and keeping the total (per environment quota) contained at the bottom sounds like it will be enough to retain the usefulness of that info. Let's update the design to that, I can update the design visuals as well.

Is the bug you're mentioning @andrewazores a bug with the code, or a bug with the design? :) If the latter then let's fix it. Thanks for the heads up everyone.

@catrobson @joshuawilson

**Comment by jiekang** [comment]
@mceledonia That sounds correct to me. I think this came from the design;;;

**Comment by jiekang** [comment]
@stooke @ebaron I think we will need backend support for this. For each application, we need the quota assigned to the pods it has. E.g. the default for a pod deployed via quickstart is 1 core and 512 MB. If it's scaled to 2 pods, then it should be a summation, 2 cores and 1 GB. This can be added to the deployments attributes which currently has `name, pod_total, pods, version`

**Comment by ebaron** [comment]
@jiekang To get this information, we could sum the resource limits for each container in a pod, and then sum each pod in the deployment. 

This information is accessible from the Kubernetes pod API:
`{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        [...]
    },
    "spec": {
        "containers": [
            {
                [...]
                "resources": {
                    "limits": {
                        "cpu": "488m",
                        "memory": "250Mi"
                    },
                    "requests": {
                        "cpu": "29m",
                        "memory": "150Mi"
                    }
                },
                [...]
            },
            [...]
        ],
        [...]
    },
    "status": {
        [...]
    }
}
`

**Comment by jiekang** [comment]
@ebaron yes. I'm going to take a hand at implementing that if you don't mind :)

**Comment by jiekang** [comment]
Closing as frontend and backend changes have been merged.
