### ISSUE TITLE
Deployments charts are not aligned

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2199]
![charts](https://user-images.githubusercontent.com/5430520/35925567-0e69c830-0bf4-11e8-838c-1d9e2c5779b5.png)

As seen in the above picture, for whatever reason, the first points in the charts are misaligned between the CPU/Memory and the Network chart. This always occurs, regardless of how many points are in the chart.

**Comment by andrewazores** [comment]
![screenshot-20180208091410](https://user-images.githubusercontent.com/3787464/35977221-74bdaab8-0cb0-11e8-9664-92d238d76cb6.png)

The alignment does seem to fix itself after some number of data points are added to the charts, but it should be aligned correctly from the start.

**Comment by andrewazores** [comment]
![screenshot from 2018-02-08 09-42-35](https://user-images.githubusercontent.com/3787464/35978691-6eccbcd0-0cb4-11e8-892d-04a993c6a2d9.png)

Hmm. Looks like it's C3 drawing the chart that way, not anything about the styles we're applying...

**Comment by andrewazores** [comment]
It's not a proper solution to the problem, but I wonder if preloading 15 minutes of samples masks this scenario. @aptmac , do you still see this on your branch?

**Comment by aptmac** [comment]
@andrewazores Yeah it's still present on my branch. After digging a bit deeper, it looks like the c3-chart isn't filling it's allocated space.

Example: the cpu-chart has 253.66px width in this case..
![2018-02-08-113829_1916x1033_scrot](https://user-images.githubusercontent.com/10425301/35985449-ae58e710-0cc4-11e8-953e-8c6f2ce2bf96.png)

But the c3 chart only has a width of 248px.
![2018-02-08-113847_1916x1033_scrot](https://user-images.githubusercontent.com/10425301/35985457-b199ec12-0cc4-11e8-8505-cca227b15e83.png)

**Comment by andrewazores** [comment]
Still struggling with this one. Even now with the 15 minute preload merged, the sparkline charts look the same at initial load - a bit shorter on the left side than our line chart. After a few minutes so that some update events occur and the charts have redrawn a few times, the sparklines seem to fill in more to the left so the gap is not as noticeable. Just to be sure - you guys see that behaviour too, right?

**Comment by andrewazores** [comment]
Okay, it seems that the misalignment between the charts actually occurs because the network chart uses actual timestamps from the backend source, whereas the other two charts just count samples and use that for the X-axis. Replacing network sample timestamps with sample counts keeps the charts at the same apparent width, however, now they all slowly fill in that left margin after a few updates...

Something also seems to be up with the data trimming logic, after a few samples are added things look skewed and there aren't enough data points in the middle of the chart:

![screenshot from 2018-02-14 11-00-38](https://user-images.githubusercontent.com/3787464/36214061-66cd9e16-1176-11e8-9669-36ba143dd401.png)

**Comment by andrewazores** [comment]
Here's what it looks like on first load, before any updates have occurred and the charts begin filling the left margin.

![screenshot from 2018-02-14 11-02-14](https://user-images.githubusercontent.com/3787464/36214129-a0db1d86-1176-11e8-8bf2-99a5a29e719a.png)

**Comment by aptmac** [comment]
@andrewazores I'll work on a fix for that, there are a few things that are a bit off when the charts update as a result of my last patch. Like you mentioned one is that the cpu/mem charts aren't using timestamps at the moment, and instead just increment the counter. There's also the fifteen minutes observable isn't guaranteed to return before the polled data, so the order of data can get a bit messed up.

**Comment by andrewazores** [comment]
@aptmac - ah, I actually have a fix for the guaranteed request ordering ready to go. Do you want me to open a PR for that and then you can handle the data trimming and real timestamps issues separately?

I think we'll still have the "growing left" problem but at least then things will line up and contain correct data.

**Comment by aptmac** [comment]
@andrewazores That'd be great actually, I'll wait for your PR to go through.

**Comment by andrewazores** [comment]
@aptmac issue for the request ordering is here: https://github.com/openshiftio/openshift.io/issues/2267 , and a PR has been opened.

**Comment by andrewazores** [comment]
Okay, weird. Changing all three charts to use sample counts makes them all draw with the same width, and starting the counts at 0 rather than 1 fixes the left margin issue.

I think this might be a c3 X-axis thing - if the X axis is not explicitly set to timeseries and a data point exists with X coordindate 1, it'll be drawn offset from the invisible Y-axis line on the sparkline chart. This explains the left margin as well as the shrinking of the left margin as the number of samples increases.

@aptmac when you go ahead with the patch to propagate timestamps to consumers you might inadvertently fix this issue. If not, it should be as easy as configuring the charts to explicitly being timeseries: http://c3js.org/samples/timeseries.html

**Comment by aptmac** [comment]
Ah that's pretty neat. I can add in the axis option.

After using the proper time stamps for the xData, the charts seem to be lining up correctly.
![screenshot from 2018-02-14 15-11-26](https://user-images.githubusercontent.com/10425301/36225724-9049f9e2-1199-11e8-93d4-ecd0d123f3ac.png)

@andrewazores In terms of propagating the timestamps to the caller, at the moment I patched up the usages of cpustat/memstat to use TimestamedCpu/MemStat instead .. would that be okay? Or should I instead add the time attribute to cpustat/memstat and use it instead?

**Comment by andrewazores** [comment]
@aptmac nice, that looks good.

I think it's reasonable to add the timestamps directly into the Stat interface, since the Stat interface is already intended to only describe timeseries data. The Timestamped* wrapper class could reasonably be used as a replacement for all instances of what it wraps, so there isn't really a point in the base time-less type. The cases of a component displaying the data without timestamp (deployment graph label, resource usage bars) are free to just ignore the timestamp property.
