### ISSUE TITLE
Planner: arrow icon next to items that cannot be expanded

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#2288]
1. open any project with at least one item of type with no children, e.g. `Task`
2. hover over `>` icon - mouse cursor changes
3. click on `>` icon - nothing happens

Expected:
There would be no icon unless a `Task` can have subtasks

![peek 2018-02-16 14-48](https://user-images.githubusercontent.com/445100/36310494-7a7097b2-1328-11e8-8ffe-fa36cd0850d1.gif)

## Impacts
- [ ] #2162 Planner Backlog Management Experience placeholder

**Comment by SMahil** [comment]
@muruGanesan Sunil,
Please have a look on this issue

**Comment by muruGanesan** [comment]
@SMahil, this is similar to issue #2289. But, hover 'color' -or- 'cursor' change is based on the text (i.e. work-item) is clickable to bring quick preview. 
@ppitonak, the expected behavior is similar to issue #2289 - which subjected to our visual review. If we decide to retain the icon in the disabled state then, we might close this issue too.

**Comment by nimishamukherjee** [comment]
Closing this as UX has decided on not to change the icon.
https://github.com/openshiftio/openshift.io/issues/2289
