### ISSUE TITLE
deployments page kebob options both display at once

### ISSUE THREAD

**Issue by mishaone** [openshiftio/openshift.io#2309]
In the Deployments screen, I clicked the Stage kebob (three vertical dots) option and it displayed additional options as expected. I then moved to the Run kebob and clicked that as well, expecting that the Stage one would stop displaying options but the second one appeared as well. Now both display, which is a minor bug. See screenshot for illustration of the problem:

![double_menu](https://user-images.githubusercontent.com/926572/36409490-8b398ac2-1657-11e8-8617-a3d61de16193.png)

The first one closes when I click the appropriate kebob again, but then if I click it again, it displays again with no change to the other one already displaying.

**Comment by jiekang** [comment]
Investigation:

`deployment-card.component.html`:

```
          <div class="dropdown-kebab-pf dropdown" (click)="$event.stopPropagation()" dropdown>
```

The cards are expandable via clicking anywhere. Propagation is stopped when clicking on the kebab in order to prevent triggering of the expansion/collapse of the card. Unfortunately, this affects the ability to close other kebabs on the page when clicking them.

**Comment by jiekang** [comment]
Closing as fix has been merged.
