### ISSUE TITLE
[5] Scale the transfer of packages to graph database

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2315]
Currently S3 to graph sync is sequential and very slow. This needs to significantly improve to reach near term goals (supporting Node ecosystem). This transfer rate to graph would need to be not less than 200 packages per min.

cc @msrb

**Comment by tuxdna** [comment]
WIP:

 

- [ ] https://github.com/fabric8-analytics/fabric8-analytics-data-model/pull/109

**Comment by msrb** [comment]
Idea:

I think one way how to speed this up is to do the heavy lifting (data transformation and actual gremlin calls) in background workers. Currently everything is happening in the context of a http request. Requester would not wait for the package to be synced to graph as this change would make the whole process asynchronous.

**Comment by miteshvp** [comment]
@msrb - or use async http calls and rely on data importer to update the RDS accordingly once the sync is done.

**Comment by tuxdna** [comment]
@msrb With the required graph sync APIs having support for limit and offset, what I am looking at right now is to revamp the [SyncToGraph](https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/handlers/sync_to_graph.py#L10) worker to use data-model-importer graph sync APIs in a way that can be parallelized. So essentially such a worker will fire multiple requests to data-model-importer service.

Since we can scale data-model-importer service independently, we can increase the throughput of these requests. Perhaps as an extension we can do auto-scaling, but we will see that once we have a better system to experiment with.

**Comment by tuxdna** [comment]
This task is ready for review now:

 - SyncToGraph like  - https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/266

**Comment by tuxdna** [comment]
Deployed to production and in already in progress. https://github.com/openshiftio/saas-analytics/pull/275

**Comment by tuxdna** [comment]
We can close this issue now.
