### ISSUE TITLE
Stack report not showing up at dash board while a build is in progress

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2335]
Stack report at dashboard shows the stack report for the last build performed. However if a build is under progress, switching to 'Analyze' screen would not show the stack report of the 'last build performed'. I guess the logic is around looking for the currently 'in progress build' and shows this message. Please see the screenshot..
<img width="911" alt="screen shot 2018-02-22 at 7 09 20 pm" src="https://user-images.githubusercontent.com/15967765/36541569-5cd19338-1804-11e8-8b18-b6ba686594b2.png">

**Comment by sivaavkd** [comment]
@jyasveer - This is a Sev2 and I am able to reproduce this.  Please review.

**Comment by jyasveer** [comment]
@sivaavkd @krishnapaparaju yes we have to change the logic to get the latest completed stack report.  currently it is a web socket call which reads the latest build of a particular pipeline. if the latest build is in progress, we show the message as `no results found`.

**Comment by miteshvp** [comment]
@krishnapaparaju - isn't this an expected behavior where we try to pick the data from latest build triggered?
If yes, maybe we could change the message shown to the users from
`No results found` -> `Build under progress` .
If this is not an expected behavior then we may have to go and figure out a mechanism to pick last successful build data. 
I am reducing the severity to Sev-3 as it does not affect loss of service. I am also inclined to remove type/bug if its an expected behavior.
