### ISSUE TITLE
Access control for the che workspaces needed

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#236]
currently if you get the url to a che workspace you can access and use it even if you are not using it.

This needs fixing as you can see other users data but also go execute git and possibly also openshift operations as that other person as the workspace

ref: https://openshift.io/openshiftio/openshiftio/plan/detail/1119
https://issues.jboss.org/browse/CHE-291

**Comment by mbenitez1607** [comment]
JIRA issue: https://issues.jboss.org/browse/CHE-291 is now tracked in github: https://github.com/redhat-developer/rh-che/issues/139

**Comment by l0rd** [comment]
We have a first PR to address that on [rh-che repository](https://github.com/redhat-developer/rh-che/pull/173) but we haven't merge it to `master` yet because we need to solve some related issues:

-  [Can not open workspace from Codebases view (ERR_TOO_MANY_REDIRECTS)](https://github.com/redhat-developer/rh-che/issues/180)
- [KC authentication fails when username contains a dot](https://github.com/redhat-developer/rh-che/issues/183)
- [KC authentication fails silently when OSO token has expired](https://github.com/redhat-developer/rh-che/issues/184)

The `ERR_TOO_MANY_REDIRECTS` issue is a blocker: it makes Che workspaces almost unusable.

**Comment by l0rd** [comment]
cc @ibuziuk @davidfestal

**Comment by l0rd** [comment]
The first related issue (https://github.com/redhat-developer/rh-che/issues/180) has been fixed and deployed on OSIO. Not sure if we should close this issue. I would wait for the second related issue (https://github.com/redhat-developer/rh-che/issues/183) to be solved too. But we may remove the label `severity/blocker` to this issue.

**Comment by maxandersen** [comment]
I agree redhat-developer/rh-che#183 is a bug that should be fixed but I would suggest it does not block the kill list issue thus I'm going to mark this as closed.

In case we do find it is a blocker for killliist we can reopen this issue again.
