### ISSUE TITLE
Drop jenkins-mvn-local-repo PV from jenkins-slave

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#2368]
Most of the build jobs disk IO is spent on downloading, extracting and updating the maven dependencies. Right now that is done on a PV mounted at /root/.mvnrepository

On Gluster storage where IOPS performance is lower than EBS this hurts the build times a lot.

| VertX quickstart | EBS | Gluster | % |
|---|---|---|---|
| First build| x | 2.5x | ~250% slower |
| Subsequent builds  | y | 3.5y | ~350% slower |

*Note: Numbers assume EBS volumes are up and not getting stuck.*

Removing this PV means that the slave will have to re-download dependencies on every build. However in my tests this is still much faster than downloading to a Gluster PV. We would also take a hit on network IO as opposed to storage IO. Removing the PV will decrease the build times to around the same as EBS.

Ephemeral storage is limited to 3GB, which is larger than the 1GB PV we're using now.

This is also what Che workspace do at the moment when building/running an app (deps are pulled on ephemeral storage)

**Comment by joshuawilson** [comment]
what `type` is this?

**Comment by kbsingh** [comment]
ping @pradeepto @rupalibehera @jaseemabid  - service critical, maps back to #2314 - for now if we can get this tested and deployed, we are able to move forward. 

cc @stevengutz FYI

**Comment by pradeepto** [comment]
Thanks @kbsingh . 

@jaseemabid is looking into it.

**Comment by jaseemabid** [comment]
I've a small patch https://github.com/fabric8io/fabric8-pipeline-library/commit/4315aaadc50278475777da53eb339ba96cf649c8 removing the PV from the maven builder but I'm not sure if this will fix it all. 
Can you please take a look at it @hrishin @rupalibehera @sthaha and let me know how I can proceed?

**Comment by hrishin** [comment]
@jaseemabid @jfchevrette ideally we should not remove the PV's as it helps in improving the overall build process it could be experimental. 
This fix #2349 could help us to sustain the build performance to some extent without PV's, just by leveraging ephemeral storage. 
This observation is good for booster applications but what about having real application development scenarios where dependencies size could be much larger than what we have for the booster application.

Cant we have EBS backed storage rather Gluster backed in case?

**Comment by kbsingh** [comment]
@hrishin can you elaborate a bit more around what you mean ? we've demonstrated above how this is a definite improvement, but you seem to disagree ?

**Comment by kbsingh** [comment]
Can we get an update on this issue ( cc @stevengutz )

**Comment by jaseemabid** [comment]
1. Removed PV from pipeline library and made a PR
   https://github.com/fabric8io/fabric8-pipeline-library/pull/388

2. Started a vertx app and build on osio

3. First build didn't start for 45m or so
   https://console.starter-us-east-2.openshift.com/console/project/jabid/browse/pipelines/vertapp/vertapp-1?tab=detailshttps://console.starter-us-east-2.openshift.com/console/project/jabid/browse/pipelines/vertapp/vertapp-1?tab=details

4. Reset the env and started another build manually
   https://console.starter-us-east-2.openshift.com/console/project/jabid/browse/pipelines/vertapp/vertapp-2

5. Looks like the happy path failed.

   Expose controller crashed because it could not find some config and the
   deployment failed.

   https://jenkins.openshift.io/job/jaseemabid/job/vertapp/job/master/2/console

```
I0227 15:33:50.232084     628 config.go:20] No /etc/exposecontroller/config.yml file found.  Will try to figure out defaults
I0227 15:33:50.232128     628 exposecontroller.go:125] Running in : `jabid-stage`
W0227 15:33:50.306724     628 controller.go:478] Failed to load url https://openshift.default.svc/.well-known/oauth-authorization-server got: Get https://openshift.default.svc/.well-known/oauth-authorization-server: x509: certificate signed by unknown authority
E0227 15:33:50.307773     628 controller.go:186] Failed to list nodes to detect minishift: the server does not allow access to the requested resource (get nodes)
I0227 15:33:50.307797     628 controller.go:118] Using OAuth Authorize URL:
W0227 15:33:50.307807     628 controller.go:120] Please use $OAUTH_AUTHORIZE_URL to define the OAuth Authorize URL!
W0227 15:33:50.308693     628 controller.go:251] Could not find kubernetes service in the default namespace so we could not detect whether to use http or https as the apiserver protocol. Error: the server does not allow access to the requested resource (get services kubernetes)
I0227 15:33:50.308740     628 controller.go:534] starting expose controller
I0227 15:33:55.308929     628 controller.go:542] stopping expose controller
```

6. I'll have to debug this or find someone who knows what'a going on before I
   can make progress.

   Asked in ~openshiftio-saas
   https://chat.openshift.io/developers/pl/z3he7jspoir7xcq5fxgezyjuty

-----> I'm here now  <-------

7. Once #6 works, I'll start a new build with PV changes in
   https://github.com/jaseemabid/vertapp/commit/514adbd4d7316d0ffb78c7b588803a66d67c2b72

8. If #7 goes through, compare time taken at step 6 and 7. Report that and let
   everyone make their decision to merge it or not.

9. Reset the tenant image with Hrishi's image PR-v52e9dd8-1 from
   https://github.com/fabric8io/fabric8-pipeline-library/pull/387
   because my builds are failing.

**Comment by jfchevrette** [comment]
I don't understand why you are getting this error. `oc get nodes` will never work as tenants don't have admin privileges. Surely it must have failed elsewhere OR a prior check lead jenkins down the path of trying to detect minishift for some reason.

**Comment by jaseemabid** [comment]
@jfchevrette I believe I just went down the happy path, clicking the right buttons in the UI and filling text fields. I'll take a deeper look tomorrow morning.

**Comment by rupalibehera** [comment]
@jaseemabid reported he is blocked on this issue due `{"Errors":[{"code":"500","detail":"Could not find entry for cluster https://api.starter-us-east-2.openshift.com/"}]}` https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/180
He cannot test his changes on his tenant due to the above issue.

**Comment by adisakala** [comment]
Do we have an issue tracking the blocker?

**Comment by kbsingh** [comment]
i understand this is fixed in prod already ( the idler-proxy ) that was blocking Jaseem ( cc @hferentschik )

**Comment by stevengutz** [comment]
@rupalibehera @jaseemabid Is there an update on this.  It's still sitting open, so I assume we're still blocked.  Can you add a link to the work item that is blocking this?  The previous one (https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/180) seems to be closed now

**Comment by jaseemabid** [comment]
@stevengutz @kbsingh I can see the Idler page now, trying to bring up the Jenkins. I'll run a few builds to test this change and report findings.

**Comment by stevengutz** [comment]
@jaseemabid  Awesome news.  I know it's late for you, but this will be a big step toward helping the SD guys get back on track so your efforts are appreciated.  A beverage of choice on me when I'm there :-)

**Comment by jaseemabid** [comment]
I cannot test the changes since I've been unable to get a few builds work on prod consistently since last 4 days even after so many attempts. Right now, I'm blocked on https://github.com/openshiftio/openshift.io/issues/2397 :man_shrugging:

**Comment by jaseemabid** [comment]
Blocked by https://github.com/openshiftio/openshift.io/issues/2403 as well.

**Comment by chmouel** [comment]
Can we clarify this issue ?

> Blocked by #2403 as well.
Can you confirm this is not accurate anymore ? (as per offline convo)

From what I gather only https://github.com/jaseemabid/maven-builder/commit/3c1400630a847bd78bae1256ce6030c8995dc3a1 is needed and currently on process to get some before/after numbers before getting merged, right?

and what's difference with @hrishin 's https://github.com/fabric8io/fabric8-pipeline-library/pull/387/commits/c9e4203d4ec0447067ebbd107da474979a3ee29e, should it be abandoned?

**Comment by jaseemabid** [comment]
@chmouel No, I'm not blocked on this. 

@hrishin's approach was to change the k8s.secrets and we both agreed that its better to change the base image instead. This is in progress now.

**Comment by jfchevrette** [comment]
Tested with https://github.com/jfctest1/benchapp4/blob/master/Jenkinsfile#L2 (pv branch)

Build times are now consistently under 5 minutes even for the first build. (when using a good mirror)

**Comment by hrishin** [comment]
> hrishin's approach was to change the k8s.secrets and we both agreed that its better to change the base image instead. This is in progress now.

@jaseemabid no need to change the k8s.secretes unless path `/root/.mvnrepository` is not going to change.
