### ISSUE TITLE
Entering 'All spaces' view cause UI to go in loop

### ISSUE THREAD

**Issue by aslakknutsen** [openshiftio/openshift.io#2378]
https://www.youtube.com/watch?v=UzCL8xTLd2Q

**Comment by corinnekrych** [comment]
@dgutride spotted the issue: https://github.com/fabric8-ui/ngx-widgets/commit/5c51bede324e7f12623b4ea8ba1fa6f69f504811

see discussion https://chat.openshift.io/developers/pl/iym4634eotbrmcq5ir87u7acsw

Tested locally with ngx-widgets@2.3.6 => infinite loop
Tested locally with ngx-widgets@2.3.4 => much better!

@vikram-raj this issue is a regression of your fix in ngx-widgets.
I guess the issue is that onchange here: https://github.com/vikram-raj/ngx-widgets/blob/0b78dfef6d4e517d7d9119a8d404c92c61aca34d/src/app/infinitescroll/infinitescroll.directive.ts#L36 you trigger a change therefore the infinite loop
