### ISSUE TITLE
[4] User consent profile screens revisited

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#2402]
belongs to [Epic: feature flags](https://github.com/openshiftio/openshift.io/issues/1165)
# Description
As a developer I should be able to able to get more information when accepting a user-consent level in the profile update screen. See UX screen:
https://redhat.invisionapp.com/share/KAF97RBGB#/screens/276638410
# List of tasks:
- [ ] profile/settings has been redesigned according to https://redhat.invisionapp.com/share/E9FH915D3U7#/screens/282415826
- [ ] revisit profile|update screen as per design
- [ ] clarify where to send feedback -do we need a new endpoint?
- [ ] fabric8-toggles new endpoint to retrieve the list of all beta, exp, internal feature per app (in the unleash term) (https://github.com/openshiftio/openshift.io/issues/3316)

**Comment by corinnekrych** [comment]
@mceledonia where does the links `send feedback` and `link here` link to?

**Comment by catrobson** [comment]
@corinnekrych Let's remove the "send feedback' link for right now.  We plan to implement a feedback mechanism in the future, but we don't have it in OSIO today.

For "link here" - @mceledonia should that link to the page that the feature exists on?  Otherwise if it was meant to just contain more informational information I think we should remove that as well.
