### ISSUE TITLE
Make validation issue easier to see when importing existing code

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#2406]
When adding a codebase and pipeline via 'Import existing code' that already has been added with a pipeline in another space, the validation request fails at step 1B with BuildConfig already exists. However, the UI displays the issue in a location that can't be seen without scrolling down. [1] This isn't very obvious. At first I was going to submit an issue that there was no indication of what went wrong, but then I noticed the scrollbar and scrolled down. The box listing repositories could be made smaller to allow for the error space to always exist, or the entire dialog could be made larger.

[1]
![add-code-error-up](https://user-images.githubusercontent.com/5430520/36862619-60be5958-1d55-11e8-8090-1847bc4e4bf0.png)
![add-code-error](https://user-images.githubusercontent.com/5430520/36862627-6273b6e4-1d55-11e8-8892-03f272940214.png)

**Comment by aslakknutsen** [comment]
@joshuawilson @catrobson This isn't just a UX issue. I think the root cause needs to be addressed. 

The codebase backend only cares about uniqueness between Space and Repository. 'Build' here seems to uphold uniqueness between Account and Repository.

Does it make much sense to have multiple Builds of the same Repository on the same Account? Not really...

Does it make much sense to not allow to import a Repository in a Space because you have it in some other space? Not really...

**Comment by joshuawilson** [comment]
@aslakknutsen the request is to make validation easier to see. You are raising the issue based on the validation message. I do agree that we need to address that too.

**Comment by jiekang** [comment]
I believe this wizard no longer exists. Closing this issue.
