### ISSUE TITLE
User on cluster 2 (starter-us-east-2a) - seeing 401 errors in trying to create a new quickstart

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#2407]
A newly provisioned user (ldimaggi-osiotest4) on the starter-us-east-2a cluster - seeing 401 errors in trying to create a new quickstart:

![screenshot from 2018-03-01 14-20-04](https://user-images.githubusercontent.com/642621/36867350-dadc7c4e-1d62-11e8-8d45-ab5372cfa486.png)

```

From google chrome console log: (Token has been removed for this issue)

2f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/oapi/v1/projects:1 GET https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/oapi/v1/projects 401 (Unauthorized)
test1:1 Failed to load https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/oapi/v1/projects: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 401.
_scrollbars.less:6 Error retrieving list Namespaces: Response with status: 0  for URL: null
33_scrollbars.less:6 WebSocket connection to 'wss://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/oapi/v1/projects?watch=true&access_token=......' failed: HTTP Authentication failed; no valid credentials available
```

**Comment by alexeykazakov** [comment]
@gastaldi ?

**Comment by ldimaggi** [comment]
This is still a problem - BUT ONLY FOR THIS SPECIF USER ACCOUNT - other accounts are able to create quickstarts on the 2a cluster. 

![screenshot from 2018-03-05 11-32-56](https://user-images.githubusercontent.com/642621/36986929-22d1555c-2069-11e8-9152-86f237ea3fab.png)

**Comment by gastaldi** [comment]
@alexeykazakov @ldimaggi any 401 errors shown in the Wizard (before Finish is clicked) are returned by calls to either https://api.openshift.io/api/user or https://auth.openshift.io/api/user services

**Comment by gastaldi** [comment]
Sorry, what is not accurate exactly? The errors returned by the tenant service? I agree, it should be more intuitive

**Comment by alexeykazakov** [comment]
The statement that 401 shown in Wizard can come only from https://api.openshift.io/api/user or https://auth.openshift.io/api/user services is not accurate.

**Comment by ldimaggi** [comment]
Is there some way tp reset/reprovision the account?

**Comment by gastaldi** [comment]
Sorry again, but why is that not accurate? You just showed us that the
tenant service is returning 401, or am I missing something?

On Mar 13, 2018 15:11, "Alexey Kazakov" <notifications@github.com> wrote:

The statement that 401 shown in Wizard can come only from
https://api.openshift.io/api/user or https://auth.openshift.io/api/user
services is not accurate.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshiftio/openshift.io/issues/2407#issuecomment-372764860>,
or mute the thread

**Comment by alexeykazakov** [comment]
Tenant service failed. This what I said. But https://api.openshift.io/api/user returned 200 OK because there is no any Auth issues with this account.
I guess this is the OSO Proxy which returned 401 (came from OSO) to the wizard because the user was not provisioned correctly (see the tenant error).
You are realizing that Tenant, Auth, WIT and OSO Proxy are different services, right? :)

**Comment by gastaldi** [comment]
I thought that Tenant and WIT were the same services. Thanks for the
clarification :)

On Mar 13, 2018 15:26, "Alexey Kazakov" <notifications@github.com> wrote:

Tenant service failed. This what I said. But https://api.openshift.io/api/
user returned 200 OK because there is no any Auth issues with this account.
I guess this is the OSO Proxy which returned 401 (came from OSO) to the
wizard because the user was not provisioned correctly (see the tenant
error).
You are realizing that Tenant, Auth, WIT and OSO Proxy are different
services, right? :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshiftio/openshift.io/issues/2407#issuecomment-372769981>,
or mute the thread

**Comment by animuk** [comment]
degrading to sev-3 at the moment.
