### ISSUE TITLE
Scale Launcher to support 500 OSIO concurrent users [2]

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2439]
OSIO Launcher is a key component to drive 'Getting started experience'. 
Front end and backend components of Launcher would need to scale for at least 500 OSIO concurrent users with each user action at Launcher  would need to be under 1 second delay.

- [x] Document test results

- [x] Identify required resources and work with SD team

- [ ] Deploy required resources at production

**Comment by animuk** [comment]
Here is the Loadtesting Report.
https://docs.google.com/spreadsheets/d/1QL6WlCf3z2d5JLyCJ0JdSoMmnAZi4-LAzvrxvnoJl_g/edit?usp=sharing
Comments:
1. Apart from GIT Apis, other APIs preformed well under load testing for minimum 500 concurrent users.
2. GIT APIs are under performers because of dependency of external GIT REST APIs. Their average response time under load of 500 concurrent users varies from 9 secs to 33 secs . But , Please note The load test run should not be considered as real world scenarios because test beds are prepared for 5 unique GIT users whereas there could n no of uniques users in real life. So, scope of improving the response time is there.
3. Also, not all APIs are used at same rate for real world usage. So, I plan to do another set of load testing when all the integration with UI are done.
Closing it for the time being.

**Comment by animuk** [comment]
Started scalability testing with 6pods

**Comment by krishnapaparaju** [comment]
Latest results are here at https://docs.google.com/spreadsheets/d/1QL6WlCf3z2d5JLyCJ0JdSoMmnAZi4-LAzvrxvnoJl_g/

Summary: to support 500 concurrent OSIO users, would be deploying 3 replicas each with 1 vCPU and 1.5 G

**Comment by quintesse** [comment]
I still wonder what the exact script is that is being used for load testing. Because besides the issue mentioned by @animuk in 2) the point he makes in 3) is even more important. The fastest a user could probably run through the wizard, making the choices and typing in a project name would be, what, 15 seconds? But any user that reads their options and thinks about a project name will more realistically take a lot longer. That means that those 500 concurrent users will, worst case, hit the Git APIs once every 15 seconds, Testing anything more than that just puts an unrealistic burden on the GitHub servers (at which point 2) becomes an issue)

**Comment by krishnapaparaju** [comment]
@quintesse these results do not include any API which talk to Git APIs (indicated in the spreadsheet). 
Here is the repo. for Launcher related load testing scripts:   https://gitlab.cee.redhat.com/schoudhu/f8a-performance-tests/tree/master/launcher_perf_tests

@animuk any more updates / corrections you wanna add ?

**Comment by animuk** [comment]
Based on this, https://github.com/openshiftio/openshift.io/issues/2683, has been worked upon.
Closing this
