### ISSUE TITLE
Fix the workitem type-selector in quick-add

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#2442]
_with the ngrx changes..._

The workitem type-selector in quick-add is displaying 'Bug' as the first entry and 'Feature' as second. This happens while adding a child workitem in 'Experiences' context and also while adding as new WI in 'Requirements' context.

The list should look like:
-
  | - Feature
  | - Bug

**Comment by joshuawilson** [comment]
What `severity` is this?

**Comment by sanbornsen** [comment]
How do we order types like this? We use in the same order as it comes from the backend. @kwk any idea?

**Comment by kwk** [comment]
@sanbornsen If you go to https://api.prod-preview.openshift.io/api/spacetemplates/2e0698d8-753e-4cef-bb7c-f027634824a2/workitemtypegroups and see the `typeList` relationship you find that this is an array and it is ordered so that the first type in the array is the default type to use in the quick add. I'd say the UI is loading this typeList wrongly into the drop down.

![bildschirmfoto von 2018-03-06 10-10-57](https://user-images.githubusercontent.com/193408/37023614-cef9a5b0-2126-11e8-9ca7-098a5ed0112f.png)

According to the picture above, Feature (ID: **0a24d3c2-e0a6-4686-8051-ec0ea1915a28**) should show up first and then Bug (ID: **26787039-b68f-4e28-8814-c2f93be1ef4e**). To resolve WITs see this URL https://api.prod-preview.openshift.io/api/spaces/2e0698d8-753e-4cef-bb7c-f027634824a2/workitemtypes

![bildschirmfoto von 2018-03-06 10-15-40](https://user-images.githubusercontent.com/193408/37023847-74da31de-2127-11e8-945d-d5e2233f4ec7.png)

**Comment by sanbornsen** [comment]
@kwk that looks correct. I am sorry. I was so sure that I was not doing any reordering in UI, but anyway I'll fix this.

**Comment by vikram-raj** [comment]
This issue has been fixed in https://github.com/fabric8-ui/fabric8-planner/pull/2504

**Comment by nimishamukherjee** [comment]
@rgarg1 please check.

**Comment by rgarg1** [comment]
@nimishamukherjee @vikram-raj The issue can't be seen in prod.

**Comment by vikram-raj** [comment]
This issue has been fixed and in prod.
