### ISSUE TITLE
No builds are moving; "Jenkin's  doesn't have label maven...

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#250]

**Comment by joshuawilson** [comment]
@jstrachan @rawlingsj @kbsingh Any idea what is happening?

**Comment by joshuawilson** [comment]
Closing this duplicate.

**Comment by qodfathr** [comment]
If we close as dupe, shouldnt that include a link to the dupe?

**Comment by joshuawilson** [comment]
@qodfathr almost always, yes. But this appears to be more of a glitch then a duplicate that someone else made. Since they both have the same title and the other one has the description. Linking back to this one does not provide more insight or inform a different user. 

But since you asked for it;
duplicates #251
