### ISSUE TITLE
Gray overlay on canceling delete comment popup in detail page

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#2537]
Steps:
- Click on wi-detail-icon to open detail page
- Add a new comment
- Click on kebab menu delete to delete comment
- Pop is displayed 
- Gray overlay on canceling popup

![peek 2018-03-12 15-24](https://user-images.githubusercontent.com/34271052/37277058-98d4b38e-2609-11e8-9a0a-a7bb0802e279.gif)

**Comment by divyanshiGupta** [comment]
@Raunak1203 @nimishamukherjee this issue is present in prod as well.

**Comment by divyanshiGupta** [comment]
@Raunak1203 can you try to recreate it without the gif maker? I couldn't recreate it.

**Comment by divyanshiGupta** [comment]
And for me, this issue occurs in prod as well but only the first time when I follow the above steps

**Comment by Raunak1203** [comment]
yes @divyanshiGupta issue occurs only for the first time, later it works

**Comment by divyanshiGupta** [comment]
@Raunak1203 as I said before this issue doesn't occur always but sometimes and randomly. @debloper can you please take a look at it? You might better debug it since you implemented delete comment.

**Comment by debloper** [comment]
@divyanshiGupta on the surface it looks like the modal's lifecycle isn't being handled properly, but I haven't looked into the code yet. It seems like a regression because of some new changes elsewhere.

I'm on PTO, so unless this is very urgent+important, I'll take a look into it on next Monday. If it is indeed urgent+important, then please have someone else to look into it - this shouldn't be too hard to solve.

**Comment by divyanshiGupta** [comment]
@debloper no problem. This issue is hard to debug since it occurs only once. Once you are back we can talk about it and can try to debug and resolve it.

**Comment by divyanshiGupta** [comment]
@Raunak1203 can you verify if this issue is still in prod and prod-preview?

**Comment by Raunak1203** [comment]
@divyanshiGupta fixed with PR https://github.com/fabric8-ui/fabric8-planner/pull/2590
