### ISSUE TITLE
Environment usage should always be displayed on Deployments screen, even if there is no deployment

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#2682]
Here is a view of the deployment screen when I have no deployments:
![image](https://user-images.githubusercontent.com/16322190/37615534-f28c48ae-2b83-11e8-8537-e693a0f70901.png)

Note that nothing is showing up in Resource Usage.

The concern is this -- perhaps I cannot deploy anything because I am out of resources due to apps in another Space. But I have no way to see how many resources are being used in my environments, and I basically have to hunt through my other Spaces to find an actual deployment in order to see the resource usage.

I'd much rather see on *all* Deployment screens that current resource usage for each environment.

## Parent Experience
#287 Deployments Page

**Comment by andrewazores** [comment]
The API the Deployments page currently uses for populating the resource usage subview is tied to not just the name of each environment, but also to the Space context of the page. We'll need to remove the requirement for a spaceId from the API requests to get these cards to display even when the current space contains no deployments.

@ebaron or @stooke is there already a way to query the resource usage for an environment regardless of spaceId?

**Comment by stooke** [comment]
We have these APIs, they are supposed to give some simple information on 
CPU/memory quota and used.
Are they what you need?

There's a PR #1949 currently in the works to remove them.

/deployments/environments/{envName}
/deployments/environments/{envName}/applications/{appName}/pods

**Comment by ebaron** [comment]
@andrewazores @stooke We will need to change the API 
from: `/deployments/spaces/{spaceID}/environments`
to: `/deployments/environments`

This should be fairly simple to change.

**Comment by andrewazores** [comment]
@ebaron or actually, the spaceId doesn't necessarily need to be removed, so long as the responses on that endpoint are always the same for a given user account regardless of the spaceId. That would mean the spaceId is effectively unused, but it doesn't actually block the UI from doing what it needs to. I guess this is probably the case already?

**Comment by ebaron** [comment]
@andrewazores The space ID is only used for the 404 message when no environments are found. You could theoretically pass any value for the space ID and get the same data back. In the long run, it would probably be a good idea to correct the API though.

**Comment by andrewazores** [comment]
@qodfathr I don't think the current behaviour was actually specified in the UX designs for the Deployments page, it's just what got implemented since the designs didn't include a scenario with no deployments. It's still a question we can ask the UXD folks but my personal feeling is that this is more of a misjudgment and bug on the implementation side.

**Comment by joshuawilson** [comment]
cc @catrobson

**Comment by mceledonia** [comment]
@joshuawilson @qodfathr @andrewazores  @catrobson 

### For the resource totals at the bottom:

I agree with Todd, let's show the total across spaces. However, I have an additional proposal. To increase clarity of the information, we utilize a [stacked horizontal bar chart](http://www.patternfly.org/pattern-library/data-visualization/bar-chart/) that has one bar showing the current space's total utilization, and another bar that shows every other space's total utilization. 

Those would then together show the overall usage of every space, while still visualizing how much of that total the current space you're currently in is using.

I will provide a visual for this updated design to show what I mean asap.

### For the empty states

Stand by, I am going to create 2 versions:
1. No applications (no framework showing deployments/environments labels)
2. Applications with no deployments (keep framework with labels and applications listed)

**Comment by mceledonia** [comment]
Here's a visual example, let me know if you guys are on board and/or if this is plausible.

![deployments stacked bar chart](https://user-images.githubusercontent.com/30935938/37729949-bea47fc4-2d14-11e8-946e-c3f37723ba24.png)

**Comment by andrewazores** [comment]
From the frontend perspective this seems definitely doable, but it requires backend support to get the usage for "this space" vs "other spaces". @ebaron @stooke is that something you can provide?

**Comment by andrewazores** [comment]
FWIW this design makes a lot of sense to me personally. I think as a user it'd be confusing to go to the Deployments page and be shown that my environments are using up resources when I can see in the same view that I have no deployments at all.

What about users who many have very many spaces? "this space" vs "other spaces" is great if you just have a handful, say 2 or 3. But what if I have 10, and only have actual deployments in 2 of those but these take up 90% of my quota, and I want to find out which one is eating up all of my resources? With this design I think all I can do is cycle through all my spaces and come back to this view until I happen to find the right one. Is this a scenario we're concerned about? If so, perhaps showing *all* spaces in the stacked bar chart, rather than "this" and "sum of others" might be the most informative and useful?

**Comment by mceledonia** [comment]
@andrewazores That's a great use case and I didn't consider it initially. My only concern would be someone with an even larger number of spaces (50-100) where each space ends up just being a sliver of a couple pixels in the chart. What if we could do the initial proposal, then provide a pop out larger view like this to show each one? (standby for visual)

**Comment by ldimaggi** [comment]
+1  We have to show the usage on a per space basis. It will be a nuisance to navigate between spaces, even with only 2-3 spaces in use.

**Comment by catrobson** [comment]
@ldimaggi @andrewazores It feels like this is the type of information that would go to the 'resources' that I have page, or the 'resources' that my org has view at some point.  I agree with Michael that getting into slivers of usage with a bunch of spaces doesn't feel like the right thing to do in this view.  Remember, the main goal of this view is to understand THIS space's deployments and usage.  Trying to cram a second main goal of 'what is the usage of each space for my overall resource quota" into this view feels the the wrong place.  Maybe we can link into the user's resource overview from here where they could get this level of breakdown?  https://redhat.invisionapp.com/share/FWFGF7VXMB8#/screens/282415828. Today this isn't using graphs to represent each space's usage but we could consider adding that functionality to this view, which feels like the better location for it to me.

**Comment by mceledonia** [comment]
Would a zoomed-in modal like this be possible maybe from clicking one of the bottom cards? This is a quick/dirty version to show the idea

![deployments stacked bar chart 2](https://user-images.githubusercontent.com/30935938/37730968-5a6fc5ce-2d17-11e8-861c-8f4d7b4e7607.png)

**Comment by ldimaggi** [comment]
I think that we may have to have multiple views - the view for the current space, and maybe a separate view for all resources being consumed by all the user's spaces. In our own work, using accounts provisioned in the free tier, it's easy to create a situation where the current space has only (1) app created, but the user's overall resource consumption exceeds the user's quota.

**Comment by andrewazores** [comment]
@catrobson linking to that resource overview page makes sense and keeps the Deployments page relatively simple. That link plus making the resource usage cards display "this space" vs "other spaces" usage seems like a good combo IMO.

**Comment by ebaron** [comment]
> From the frontend perspective this seems definitely doable,  but it requires backend support to get the usage for "this space" vs  "other spaces". @ebaron @stooke is that something you can provide?

It can be done but it is non-trivial to do so, due to the way Kubernetes represents quotas. A quota is a ResourceQuota object just like a BuildConfig or DeploymentConfig object. It has a status field that represents the current usage for the project. There is no way to ask it for just usage corresponding to a particular space.

To figure out the quota used by a particular space we have to check each object associated with that space individually. The deployment-specific quota usage added in https://github.com/openshiftio/openshift.io/issues/2183 could help with this, but we would miss corner cases like if the user has a stuck pod belonging to an old deployment. A better solution might be to query pods with a matching space label, however this is currently unreliable (https://github.com/openshiftio/openshift.io/issues/2360). This is further complicated by adding object count quotas in addition to compute resources, e.g. number of services (https://github.com/openshiftio/openshift.io/issues/2086).

**Comment by jiekang** [comment]
As far as work goes, in the interim, it should be possible to display the current quota cards even if there are 0 deployments in the space. I propose a new issue be created to track the discussion of design and implementation for the better user experience showing which space is taking up what quota. This issue can be the parent or can be used to cover the task of displaying the current quota cards even if there are  0 deployments. Thoughts?

**Comment by joshuawilson** [comment]
This has been fixed. Please reopen if still an issue.
