### ISSUE TITLE
Stack Report is incomplete for code metrics

### ISSUE THREAD

**Issue by christian-posta** [openshiftio/openshift.io#275]
See this image:

<img width="1107" alt="oio-code-metrics" src="https://user-images.githubusercontent.com/53201/27392747-49560204-565c-11e7-86bf-5b79fc4a88de.png">

**Comment by christian-posta** [comment]
Here's the code from the git repo used in this project/codebase

https://github.com/christian-posta/basic-springboot

**Comment by joshuawilson** [comment]
This issue was moved to fabric8-ui/fabric8-recommender#245

**Comment by joshuawilson** [comment]
This issue is now being tracked at https://github.com/fabric8-ui/fabric8-recommender/issues/249

**Comment by samuzzal-choudhury** [comment]
Hi @christian-posta, thanks for reporting this bug. This was a strange behaviour and took us some time to figure out the root cause. The reason turned out to be non-existence of code metrics data in the backend for your dependencies. We admit that the results could have been presented in a user friendly way.

We are currently working on improving the UX of the stack reports screen and we will keep you posted on its availability in the production.

**Comment by arunkumars08** [comment]
This issue has been fixed and is in production. Please verify and close.
