### ISSUE TITLE
Change in text for starting OSIO launcher

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2832]
After internal feature is turned on at OSIO, Launcher (New app. creation + Import flow)  can started by clicking on 'New Import Experience'. This text would need to be changed to 'Try out new Launcher experience..'
<img width="569" alt="screen shot 2018-03-30 at 1 33 30 pm" src="https://user-images.githubusercontent.com/15967765/38130079-3a6d325c-341f-11e8-91be-dc2c569449d3.png">

**Comment by joshuawilson** [comment]
Since it will likely be this way for GA we need to get @qodfathr and @catrobson to approve.

**Comment by invincibleJai** [comment]
@joshuawilson thanks Joshua , what @krishnapaparaju  asked is just for text change of anchor  to make it more intuitive I guess. 

Here is PR for same https://github.com/fabric8-ui/fabric8-ui/pull/2696

**Comment by qodfathr** [comment]
Why wouldn't we use more end-user friendly text such as "Try our new Getting Started experience?" Given the fact that, in the user's mind, they are currently using a "getting started" experience based upon the words on the screen, in follows that the link is to try the new experience. "New Launcher Experience" is a bit odd, because the user isn't using the "old Launcher experience."

**Comment by joshuawilson** [comment]
@invincibleJai please update the message to follow @qodfathr wording.

**Comment by invincibleJai** [comment]
Thanks @qodfathr @joshuawilson .

Here is the PR with the change https://github.com/fabric8-ui/fabric8-ui/pull/2704

**Comment by invincibleJai** [comment]
Changes are in prod now. Closing this issue.
