### ISSUE TITLE
Not able to open deployed boosters from OSIO Launcher

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#2861]
Please see the screen shot comparing boosters launched from OSIO Launcher Vs. OSIO Wizard. Could not see links for reaching deployed applications at STAGE & RUN 

<img width="1400" alt="screen shot 2018-04-04 at 9 33 58 am" src="https://user-images.githubusercontent.com/15967765/38287970-4cf46920-37eb-11e8-994e-83e82f5a89b0.png">

**Comment by animuk** [comment]
Now, What I have found default artifact ID set in the UI as "booster-mission-runtime". If you do not change the default value every time, the same docker image at openshift is getting reloaded and override the earlier docker image. It seems that due to this, no new link is getting prepared in the openshift console and in the OSIO also, link is not showing. 

Earlier, the artifact ID was not editable in new launcher, but now, it is editable now. But @invincibleJai , what I suggest either you need to set the default value something unique with adding some random number or make it blank, so that user has to enter some values.

Please Note: in earlier legacy launcher, project name was set as a artifact Id, so that way, it becomes unique.

**Comment by animuk** [comment]
@krishnapaparaju  can I close this ? please let me know

**Comment by ldimaggi** [comment]
In other words, it is up to the user to define a unique identifier - the user cannot any longer accept the default. I'd recommend leaving this issue open until we alter the UI to require the user to supply a unique value - so users can avoid the problem described in this issue.

**Comment by invincibleJai** [comment]
@gastaldi @animuk currently artifact_id is editable and is formed based on user's selected mission, runtime i.e `booster-http-vertx` in Quickstart flow in Import flow it's always `booster-mission-runtime` by default , any suggestion how to make it unique at client side?

**Comment by gastaldi** [comment]
@invincibleJai append the user/space name to the artifactId?

**Comment by invincibleJai** [comment]
@gastaldi that won't help here i guess as same user can have more than one app in his space and as per @animuk it has to be unique

**Comment by invincibleJai** [comment]
had discussed with @gastaldi so the solution (for OSIO only) is to use the project name as the artifactId and it has to be unique. CC @animuk @jyasveer

**Comment by animuk** [comment]
closing this as this issue is not there.
