### ISSUE TITLE
Wireframes: Over Quota Experiences

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#2911]
### Description
**STORY**
When a user is likely to, or has hit quota on OpenSHift.io, there is little to no information given to the user about this throughout OpenShift.io. Consider a full experience for how to display quota problems throughout the OpenShift.io

**HISTORY**
APP CREATION
We had a design to warn the user and not allow them to add more deployments (applications) here: https://redhat.invisionapp.com/share/PMDCE3G94

We didn't carry this feature into the launcher since it wasn't supported by the backend, but there is a desire to have this added back so we can help users understand when they are adding too much to their openshift.io instance.

PIPELINES
Pipelines have a stage where the application is deployed to Staging environment or Production environment. It is thought that adding a new application should make it through the build pipeline without any issues, but these deployments steps may fail. More information is needed from QE and Development around how this works, and what points in the UI may help users understand the behaviors.

DEPLOYMENTS
The users would get various warnings in the deployments page based on quota, but understanding whether these are given at the right time, with the right information to help the user come to resolution is unknown.

Work with @ldimaggi @maxandersen @joshuawilson @aslakknutsen @dgutride to capture full implications and experience improvements we can make throughout the system on this.

### Parent Issue(s)
- #874 
- #2019

### Verification Criteria
- [x] Work with QE & Dev to capture quota limit system reactions (what happens and goes wrong when we hit quota?). Determine how we can warn or inform the user across different pages of the UI around these reactions, or prevent them entirely. (End result - google doc with all requirements/information discovered)
- [ ]  Design screen updates across OpenShift.io that show where we can warn or inform the user of quota limitations or results that occurred because of a quota limitation (ie. This deployment failed because you are already at your limit).
- [ ] Share screens on MatterMost & review with PM, QE, and Dev team for approval.
- [ ] Work with Stakeholders & Catherine to build stories across the dev teams who need to implement these UI improvements

**Comment by mceledonia** [comment]
[Notification-based quota warning design proposal](https://redhat.invisionapp.com/share/BHGPNUXCR9A)

The idea here is to use a notification based set of warnings for most instances where the user is nearing or max quota following an operation. The notification panel gets a facelift that combines it's functionality with a full list of resource usage data and also status information.

The initial overlay (fullscreen) based design still has a place at the beginning/end of creating an application flow. This is in order to give a more blatant warning that the user won't be able to deploy and give information around how to fix that, even though we still let them proceed with creating the application flow.
