### ISSUE TITLE
Links to Stage and Run applications are missing from the pipeline page

### ISSUE THREAD

**Issue by pmacik** [openshiftio/openshift.io#2920]
There used to be links to the deployed applications in Stage and Run in the pipeline pages and now they are gone.

**Comment by pmacik** [comment]
![image](https://user-images.githubusercontent.com/3263627/38426670-9473efaa-39b7-11e8-84f0-7924c6b9f320.png)

**Comment by ldimaggi** [comment]
Related to?
https://github.com/openshiftio/openshift.io/issues/1894
https://github.com/openshiftio/openshift.io/issues/456

**Comment by ldimaggi** [comment]
Seeing the same thing today in production:

![screenshot from 2018-04-08 10-46-54](https://user-images.githubusercontent.com/642621/38468887-4fe58a06-3b1a-11e8-805d-1b93010a2df3.png)

**Comment by jiekang** [comment]
I am pretty certain this is related to the issue described in #2985. The OSO deployment name is something unexpected and so whatever is trying to generate the link is unable to. In my testing of production, if Maven Artifact != Project name, this issue will occur. If the user sets Maven Artifact == Project name, this issue will not occur.

However, it looks like the ability to customize Maven Artifact and it's strange default is no longer present in upstream, so this issue may no longer occur once production is updated.

**Comment by invincibleJai** [comment]
@ldimaggi @pmacik am assuming this has been observed with "New Getting Started Experience" 

if yes, as per my understanding Quickstarts should work fine in prod-preview with links. Once changes have been promoted to prod it can be tested. 

Workaround for now in prod could be  using the same value as for "application name" and "maven artifact id" in summary screen. 

@animuk @ravsa ^^

**Comment by ldimaggi** [comment]
I am not sure about that workaround - how will users wanting to use only the new launcher do that?

**Comment by invincibleJai** [comment]
@ldimaggi in new launcher maven artifact id which appears in summary and the app name both are editable fields so if you provide same value it should work as expected.

in Legacy(existing) wizard am assuming it's working fine.

**Comment by invincibleJai** [comment]
Once changes promoted to prod. Workaround for new launcher experience won't be needed anymore.

with help of @joshuawilson will try to promote it asap

**Comment by ldimaggi** [comment]
I just tried that in production and it did not resolve the problem.

**Comment by invincibleJai** [comment]
ah, @ravsa @animuk can pls take a look at this. Having same value of artifact id and app name is not working for @ldimaggi

**Comment by jiekang** [comment]
@ldimaggi Hmm, when I create an application with the flow in Production and set 'Project name' and 'Maven artifact' to the same value, the deployment is correct and it works; Are you able to show us what was deployed in your OSO stage/run environment? E.g. screenshot of the OSO console with stage/run project open. The name of the deployment should match the name of the application if 'Project name' == 'Maven artifact'. Otherwise it doesn't match and things are 'broken'.

In my image below, 'Project name' is app-test-1 and 'Maven artifact' is default to booster-resthttp-vertx-[...]. This will be broken. If you set 'Maven artifact' to app-test-1, it will work.

As far as the longevity of the workaround, the wizard in 'upstream' no longer allows users to edit 'Maven artifact' and it is set to the 'Project name' so it should not be possible for this issue to occur once Prod is updated to latest in upstream.

![new-launcher](https://user-images.githubusercontent.com/5430520/38621794-9991b498-3d6f-11e8-8493-b98c6941219c.png)

**Comment by invincibleJai** [comment]
thanks @jiekang , @ldimaggi prod have been updated with recent changes. Now user need not bother about having same value for artifact_id and app name. It's been taken care in background.

**Comment by invincibleJai** [comment]
Changes are in prod. Closing it pls reopen if still see this.
