### ISSUE TITLE
[Usability] Logging in does not redirect to a clicked link URL

### ISSUE THREAD

**Issue by nickboldt** [openshiftio/openshift.io#2950]
Logging in to a planner board, I have to go through several steps:

* click link to eg., https://openshift.io/openshiftio/eclipse-che/plan?q=(space:7d747e1f-d66e-497c-b0f5-30dac9cc75bc%20$AND%20typegroup.name:Scenarios)&showTree=true

* opt in to experimental features

* wait as host name is resolved for SSO login

* log in

* end up on https://openshift.io/_home instead of the link above. This is lame -- why can't I be redirected to the link I asked for before logging in?

* click link above again, page now loads.

Note too that if I want to bookmark the page, the page title in Chrome is "Loading..." instead of something useful like "eclipse-che backlog board". Surely a better page title is possible so when bookmarking these crazy-long URLs they're more meaningful?

**Comment by joshuawilson** [comment]
I thought we just fixed the redirects from logged in. 
@nickboldt we had some cacching issues last week. Can you do a hard-refresh and try again?

**Comment by joshuawilson** [comment]
I think it should redirect.

Sorry I was thinking of this one. https://github.com/openshiftio/openshift.io/issues/2731

**Comment by aptmac** [comment]
I wrote a quick proof of concept [0] as to what this could look like, but it's waiting on a ui-related discussion [1] as to what it should look like.

The idea was have a feature-related service look at incoming URLs and hold on to the last route before an opt-in screen is hit. This way we can redirect the user after they change their opt-in level.

![feature-opt-in-wip](https://user-images.githubusercontent.com/10425301/44529387-fab31100-a6b9-11e8-9ce8-247274b06c4f.gif)

[0] https://github.com/aptmac/fabric8-ui/commit/33415d89199d3980581af1e5f77285b5f576067b
[1] https://github.com/openshiftio/openshift.io/issues/3296

**Comment by joshuawilson** [comment]
@aptmac if your fix still works, could you submit it as a PR?

**Comment by aptmac** [comment]
I rebased the branch [[0]](https://github.com/aptmac/fabric8-ui/tree/feature-opt-routing) so that it sits on top of current master, but it really was just a PoC hoping to get some discussion going .. the tests don't pass and the implementation is not very pretty (or robust). However, given proper designs this could probably be fixed up pretty easily. 

![opt-in](https://user-images.githubusercontent.com/10425301/47167423-7c937500-d2cc-11e8-99aa-ce1154e6e17a.png)

The more I think about it, I believe the best option would be if we could display the feature-opt in screen without changing the url to be `/_featureflag?showBanner=whatever`, so that when the feature-level is updated the user can just hit the back button on their browser and it would show the page with the updated permissions .. but that's just my 2 cents.

[0] https://github.com/aptmac/fabric8-ui/tree/feature-opt-routing

**Comment by joshuawilson** [comment]
@serenamarie125 @openshiftio/uxd-team can a designer please review

**Comment by christianvogt** [comment]
This is still present a very bad experience.
When the user isn't logged in, they get the opt-in banner page. Upon clicking the opt-in button, the user is brought to `https://openshift.io` instead of the login page. I think this is why they are returned home instead back into the app.

That being said unless we first fix https://github.com/openshiftio/openshift.io/issues/3296, we cannot properly return the user to the board view because the URL of the opt-in page has taken over.

**Comment by rohitkrai03** [comment]
This was fixed in https://github.com/fabric8-ui/fabric8-ui/pull/3472. Closing it.
