### ISSUE TITLE
click box on left navigation is super small and misleading

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#2970]
when selecting items on left navigation area it seems only the label/name is clickable and not the actual line.  That makes it really tedious to use as you have to hit the line very precisly.

Below I've marked the very small "Iris" with red which is the area that reacts on click but I would expect the full yellow area here being clickable to cause selection (maybe except the kebab)

![2018-04-10_09-08-08](https://user-images.githubusercontent.com/54129/38541245-c8d13d68-3c9e-11e8-9e58-4a644c20bbe0.png)

note, the cursor changes form to "clickable" on top of the whole yellow area but actually doing the click has no effect.

**Comment by debloper** [comment]
Although it's possible to activate click on the entire container, I'd imagine it's implemented this way (to click the title only) to avoid event bubbling behavior from the kebab menu button (which is a child element).

It's somewhat easier to change it so that the cursor changes only on hovering over the title, so it's not confusing anymore. Does that work for you?

**Comment by joshuawilson** [comment]
That would be much better.

**Comment by maxandersen** [comment]
changing the hand only makes it less weird (the UI will at least not be "lying").

But in general I believe it is bad/ineffective UX to have primary navigation points be so hard to click /cc @catrobson wdyt ?  

If kebab being a child of the container is a problem then lets fix that instead - could introudce a container to have the label in that takes up all width for example.

**Comment by debloper** [comment]
@catrobson can you please post a highlighted bounding box reference to show what you mean, just so that your point is taken beyond any possible confusion?

FWIW, the PR I submitted, makes the entire `.f8-itr__header` (the highlighted area) receptive to clicks and changes cursor accordingly. Should we make it so that `.f8-itr__header` element is stretched to fill up the empty spot upto the kebab menu?

![screenshot from 2018-04-10 15-13-33](https://user-images.githubusercontent.com/536060/38549655-254df80a-3cd2-11e8-825f-85a04f6ce6e3.png)
