### ISSUE TITLE
Click add-work-item lead to error page.

### ISSUE THREAD

**Issue by liangxia** [openshiftio/openshift.io#3021]
Click the '+' on the project page,
![screenshot from 2018-04-12 13-25-11](https://user-images.githubusercontent.com/4716987/38657873-1773f336-3e55-11e8-86ca-e2499b252c0b.png)

It show me a page like this,
![screenshot from 2018-04-12 13-25-41](https://user-images.githubusercontent.com/4716987/38657876-1857d380-3e55-11e8-9135-08294cca8082.png)

**Comment by ldimaggi** [comment]
I am not able to recreate this page - can you try again? Thanks!

**Comment by aptmac** [comment]
This particular issue should have been amended in https://github.com/fabric8-ui/fabric8-ui/pull/2738, @liangxia can you confirm?

Actually using the add work item controls is broken for me, but this behaviour should be fixed.

**Comment by liangxia** [comment]
From the workspace home, click on the "Create work item" button on the lower left-hand side of the "My Work Items" box.
![screenshot from 2018-04-18 10-08-04](https://user-images.githubusercontent.com/4716987/38907987-e24eee36-42f0-11e8-9f96-4132b532f6c9.png)

A page show up with "Choose a new work item type". But instead, click create on the top.
![screenshot from 2018-04-18 10-08-22](https://user-images.githubusercontent.com/4716987/38907988-e2884a28-42f0-11e8-9c84-6e581961878b.png)

Still show 404.
![screenshot from 2018-04-18 10-08-54](https://user-images.githubusercontent.com/4716987/38907989-e2c2a218-42f0-11e8-8d1e-3a44f9216665.png)

**Comment by aptmac** [comment]
Neat, thanks for the screenshots!

**Comment by aptmac** [comment]
@joshuawilson  @dlabrecq @dgutride  So I'm a bit stumped with this one, and could use some guidance more information if you happen to know.

Here's what I've gathered so far ..

What's happening is that the named outlet ('action') is incorporating the target url and creating a url that isn't recognized to our router. For example, from `/(action:add-work-item)` and going to the Create page, we end up with `/(create//action:add-work-item)/`, and this is because the named outlet stays open and doesn't close when traversing pages of the application [0]. Note the url that's displaying in the preview as I highlight the create button in the header.
![og-add-work-item](https://user-images.githubusercontent.com/10425301/39071974-f64d8858-44b6-11e8-9de5-b2468458505a.png)

There are two 'action's that we currently use (add-work-items) and (add-codebases), and these are found on the Analyze and Create/Codebases pages. This routing error only occurs on the Analyze page. The reason for this I believe is because the outlet's parent (Analyze) uses an empty string path which is not compatable with named-outlets [1]. However, when using the add-codebases action on the 'Create/Codebases' page, it has the parent route 'Create', and that's why we don't see the error there. In the image below, I'm on the codebases page and hovering over the 'Analyze' button in the header, the preview url will correctly route to the analyze page. 
![add-codebases-analyze](https://user-images.githubusercontent.com/10425301/39072058-4a39032a-44b7-11e8-8209-7e5e8dae050a.png)

To test, I wrote a quick PoC that changes the url for the Analyze page to be '{$spacename}/Analyze' [2], and the urls now work as expected.
![fix-with-non-empty-route](https://user-images.githubusercontent.com/10425301/39071998-0f895982-44b7-11e8-9744-6d2807497529.png)

Additionally, just a question about the named outlets: they were introduced in this commit [3], but there isn't much discussion as to why. From what I can tell, despite the many 'actions' that can be performed to open modals, create and import code, only this `add-codebases` and `add-work-items` use the named outlets. IIRC the 'import codebases' functionality is going to be reworked [4], and the work items 'overlay' isn't much of an overlay, it covers the entire page .. is it worth keeping the outlets for these? Would it make sense to remove the import codebases buttons (that trigger the 'action') at least, and make the add-work-items page it's own page (PoC at [5])? FWIW the add-codebases action can be a bit buggy with routing as it currently stands, if we intend on keeping the outlet then I'll file an issue for it. In the image below, I've triggered the add-codebases action on the codebases page, and then navigated to the Deployments page, note how the highlighting on the header hasn't updated (it still 'shows' that I'm on the codebases page).
![add-codebases-on-deployments](https://user-images.githubusercontent.com/10425301/39071881-a80573f4-44b6-11e8-9c19-bfd447839050.png)

[0] https://www.concretepage.com/angular-2/angular-2-4-named-router-outlet-popup-example
[1] https://www.bennadel.com/blog/3346-named-outlets-require-non-empty-parent-route-segment-paths-in-angular-4-4-4.htm
[2] https://github.com/aptmac/fabric8-ui/commit/3d27b5816a99fe114a9c0b832a43dfd710ea6e6d
[3] https://github.com/fabric8-ui/fabric8-ui/pull/444
[4] https://github.com/openshiftio/openshift.io/issues/3100#issuecomment-380884315
[5] https://github.com/aptmac/fabric8-ui/commit/706ddf71ac4459a988b50f3aef62e32ff315edb8

**Comment by joshuawilson** [comment]
I think we need to look at doing something else.  I think it might violate the URL pattern. 

@catrobson @maxandersen what is the requirement for the URL pattern?

**Comment by aptmac** [comment]
What's the reasoning behind using the `action` outlet for these two cases specifically? It just seems kind of peculiar that we have modals and forms that perform 'actions' but aren't using this same routing.

**Comment by maxandersen** [comment]
> I think we need to look at doing something else. I think it might violate the URL pattern.

platform and planner team was supposed to look into it - the most documented we have is https://docs.google.com/spreadsheets/u/1/d/1cNSDuek0v1EBPpdPlFwG_Y_yOlux86m9MYf9UrF82l4/edit?usp=drive_web&ouid=103249841199145518066 but we already know that is being broken.

**Comment by dlabrecq** [comment]
The action outlets is more useful for something like add-to-space and add-work-item so that task can be performed from any screen. At one time, we were also adding codebases from the home page? However, if the modal is only displayed on one page, then action outlets isn't necessary. The modal can be opened directly or with a broadcast event.

**Comment by joshuawilson** [comment]
What is the status of this?

**Comment by jiekang** [comment]
The discussion has led to the removal of this feature. Fix has been merged upstream. I will track this and close it when it reaches Production.

**Comment by joshuawilson** [comment]
pushed to prod, closing
