### ISSUE TITLE
UI Implementation:  Applications widget (8)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3151]
Implementation of the applications widget in the space dashboard as designed here:  https://redhat.invisionapp.com/share/F6FETDZBA2D#/283827734_NewSpaceDash1

Verification Criteria:
- [x] Feature built in UI and reviewed with @mceledonia 
- [x] Unit tests created for this code
- [x] PR submitted for applications widget with feature flag capabilities

**Comment by andrewazores** [comment]
@dlabrecq here's my branch where I've refactored the EnvironmentWidget so that it consumes the DeploymentApiService rather than the DeploymentsService. This is how we're intending for non-Deployments areas to consume data from the Deployments backend, so I hope it'll be a good reference for you here. https://github.com/andrewazores/fabric8-ui/commits/environment-widget

**Comment by dlabrecq** [comment]
Reviewed a demo with Michael Celedonia and created the PR below.
https://github.com/fabric8-ui/fabric8-ui/pull/2812

**Comment by dlabrecq** [comment]
Done and merged into fabric8-ui
