### ISSUE TITLE
Widget loading behavior in Space Dashboard (5)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3157]
### Description
If a widget is loading in a dashboard, the loading experience should be replaced with the widget loading experience that is documented in the new standards. That widget loading experience includes disabling the title of the widget, including a spinner, and a context specific loading message that gives the user a better sense of what is loading.

Analytics team would need to implement this for the Stack Report widget on the space dashboard.  All other widgets should currently be owned by the platform team.

Link to updated standards: https://redhat.invisionapp.com/share/JKGR07DRUC3
Link to design Github issue: #2870

### Parent Issue(s)
https://github.com/openshiftio/openshift.io/issues/3009

### Verification Criteria
- [ ] UI implementation created and reviewed with @lwrigh for Space Dashboard
- [ ] Unit tests created for loader
- [ ] PR submitted with new loading bar that follows designs

**Comment by dlabrecq** [comment]
Looking at the standard and see a couple potential issues. Using the work items card as an example, we basically have two states; items and no items. Until we obtain work items, we display have been displaying the empty state. 

We do this by subscribing to an Observable for a unique property, which simply means we wait until for that property to be updated in order to display work items in the page. If the Observable never updates, the spinner may be displayed indefinitely. We will need to experiment with this for each card -- it may be fine providing each Observable always returns something.

The other potential issue is with the progress bar upon the initial login. We really don't know the page size, nor much of the page has been loaded. I believe that's why we used an the existing indeterminate progress bar.

**Comment by lwrigh** [comment]
I see, I'm just worried about the widgets cycling through the different states when a user first comes upon them. It feels a bit shaky and uncertain. I would rather see the loading state then the loaded widget instead of the empty state first showing up and then the loaded state. We can definitely experiment and see if we can get it to that point though. 

In order to get more information about the page size that's loading, would something have to be added to the back end to retrieve that sort of information?  @dlabrecq

**Comment by dlabrecq** [comment]
That was more of a note for me to investigate. As long as the Observable returns something, it will be fine. If it doesn't, then the spinner could just sit there until there is an update elsewhere in the UI. This may not be a problem for the widgets on the home dashboard, but may be for others? For example, the list of codebases may show up until the user adds one. In that case, I worry about displaying a spinner indefinitely VS an empty list.

The progress bar is tricky because it's not just one request. The page itself makes additional requests to fetch data. I believe the initial page has already loaded, but the user is waiting for the page to render additional requests? Again, more investigation is needed to see what this page is doing. Another issue is that we still land on the old getting started page. Then, we navigate to the home page after running some code. If we remove that, the user may see the home page much earlier?

**Comment by lwrigh** [comment]
In the case of there being no content added to a widget it should probably just go from the loading state to the empty state if there is nothing to fill the widget with. 

Passing by the old getting started page and just heading to the home page once it has loaded makes sense to me.

**Comment by dlabrecq** [comment]
Created https://github.com/fabric8-ui/fabric8-ui/pull/2977
