### ISSUE TITLE
OSIO developer's name appears in Jenkins pod log

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#3174]
Just noticed this in a Jenkins pod log:

```
Apr 17, 2018 5:08:52 PM io.jenkins.blueocean.autofavorite.FavoritingScmListener onCheckout
INFO: Automatically favorited osiotestmachine/testapr171523984723571/master for erikjan.dewit
```

**Comment by piyush1594** [comment]
I think this is coming from https://github.com/jenkinsci/blueocean-autofavorite-plugin/blob/master/src/main/java/io/jenkins/blueocean/autofavorite/FavoritingScmListener.java#L133

@jaseemabid @rupalibehera What can be done for this?

**Comment by jaseemabid** [comment]
Can we just get rid of blueocean-autofavorite-plugin?

**Comment by piyush1594** [comment]
@jaseemabid @rupalibehera Is this not required? I really don't have idea.

**Comment by jaseemabid** [comment]
Reading the description of it, it seems like something we can live without. Since this Jenkins will usually run only a few jobs mirroring the name of the github repo or project, I don't think there is a need for a favourites feature. Each plugin reduced is huge savings in memory and potential bugs like these. WDYT @rupalibehera?

**Comment by rupalibehera** [comment]
related to this https://github.com/openshiftio/openshift.io/issues/2490 and as we voted to close this one, lets close this too. 
This is not a bug it is some feature of autofavourite plugin, closing this issue.
