### ISSUE TITLE
Pressing Enter should create a new space (2)

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3197]
Steps:

- Click create space
- Provide a space name. 
- Now Pressing enter should create a new space

**Comment by mindreeper2420** [comment]
I'd like to also add that `ESC` should also be a valid input on the Create Space overlays.

**Comment by mindreeper2420** [comment]
@dlabrecq I've added screenshots for the two spots that should have the capability to use `Enter` and `Esc`. I added the `Esc` functionality request, as if you can use the keyboard for moving forward, you should also be able to use it for cancelling the process.

**Comment by dlabrecq** [comment]
The problem with the "create application" screen is that the user must make a selection first. The submit (enter key) will only work if and only if the continue button is enabled. Although, it's unlikely the user will select that first, then add an application name.

The escape is more problematic because we don't do that anywhere else in fabric8-ui. I can make this work in the overlay screens, but when the application launcher is displayed, the escape key won't work there. That will have to be addressed in the ngx-launcher repo.

With this addition, the story is probably worth more than 2 points... Will need to create another story to tackle implementing the escape key for other modals.
