### ISSUE TITLE
Learn more button in What's opens general docs page

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3272]
1. go to dashboard
2. click "Learn more" button in What's New? section

result:
* page https://docs.openshift.io/ is loaded
* user won't find any information about new feature on this page
* it should point to the page/section of docs describing the feature

![osio_whats_new_1](https://user-images.githubusercontent.com/445100/39174023-c2455386-47a6-11e8-81c6-0b5e03593a0c.png)

**Comment by joshuawilson** [comment]
@rkratky maybe you can talk to @catrobson about this.

**Comment by joshuawilson** [comment]
You may also want to talk to @qodfathr about release notes.

**Comment by catrobson** [comment]
@mceledonia @dlabrecq @mindreeper2420 please look into this while you're working through fixes on dashboards.

**Comment by mindreeper2420** [comment]
This should not be under the 'Production' release and is in the process of being moved back to 'Experimental'. The plan was to inform docs that it was under the 'Experimental' level, so that it could be documented :)

I'm also working with Len/Pavol/Lucia to help them with getting their tests updated against this new dashboard.

**Comment by joshuawilson** [comment]
It is already under Internal and should not have been reported. We are working on educating people to only review/report on Released and Beta.

**Comment by mishaone** [comment]
Are we good to close this issue?

**Comment by joshuawilson** [comment]
Closing as this is not released yet.
