### ISSUE TITLE
Users should be blocked from exceeding resource quotas

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3344]
Parent: #2629

# User story

As a user, I would like to be stopped from performing actions which are guaranteed to fail due to insufficient resources, such as creating new applications or scaling up deployments.

The first two screens here are relevant for this story: https://redhat.invisionapp.com/share/CTGJ6F7V4K9#/screens

# Tasks

- [ ] [Launcher blocks creation when resource quota is reached](https://github.com/openshiftio/openshift.io/issues/3346)
- [x] [Deployment blocks scaling when resource quota is reached](https://github.com/openshiftio/openshift.io/issues/3345)

**Comment by andrewazores** [comment]
@joshuawilson I'm taking the Deployments task for this story, please forward or assign this to someone from Launcher who can take the other task.

**Comment by qodfathr** [comment]
Why is this a p0? The parent #2629 isn't a p0 (and shouldn't be). The user would have had to have been successful multiple times before hitting this issue, so I do not feel this qualifies as a p0. I'm not saying it's not important, but it's not a blocker for first use, either.

Blocking the Launcher (#3346) strikes me as an overreaction to this problem. It's kind of like there not being a parking space at work, so rather than driving to work and waiting for a space to open up, instead you just stay at home. :) The issue is not with the Launcher. There is no reason for the Launcher to not do it's thing -- the issue occurs during CD. And that's where the problem should be addressed, not at the Launcher.

Even with #3346, I could be in a position of completing the Launcher successfully, but, while waiting for CI to complete, one of my deployed apps suddenly uses a bunch more resources (perhaps due to servicing a request). My new app will fail to deploy at the point of CD. So the proposal in #3346 is, at best, a band-aid. Moreover, it does not feel "compatible" with the up coming Environments feature. When I have the ability to define multiple environments across other deployment services (OSO Pro, OSD, etc.), what would it mean for the Launcher to determine "you are out of resources"? I'd argue there is no proper answer to that question once we have Environments. And as Environments are part of I train, #3346 is going to be obsolete soon.

I'd vote to not solve this problem this way, and, instead, think about how to address the concern at the moment of CD.

**Comment by andrewazores** [comment]
#2629 *was* marked as a P0 but this label was removed because this the scope was very large, so this issue was created to track a solution for a smaller scope that can be implemented in time for Summit and the P0 label was transferred here instead.

The resources in question do not work the way you've outlined. When a pod is allocated, the resource quota is allocated with it and is static. The pod using resources within its quota does not affect the remaining quota for the environment. If you allocate one pod right now, 512MB of your 1GB memory allotment is reserved, even if that pod is not using 512MB of memory. Deployment of a second pod will never fail due to this first pod consuming resources. A second deployment, or second pod, will bring you to exactly 1GB/1GB allocation. A third deployment or pod is then guaranteed to fail because it will go over quota.

I'm not sure how you would address the concern at the moment of CD. If the user has no available resources at the time of opening the Launcher, what action is CD supposed to take to rectify this situation? There are no resources, so what action is there to do other than fail the deployment and notify the user after the fact? If this can be predicted, since it is already known what the utilization percentage for an environment is, why let the issue get to the point of a failing deployment rather than telling the user that there is no way it won't fail?

**Comment by joshuawilson** [comment]
@qodfathr it is as @andrewazores explains it. On the free tier you can only have 2 apps. You must either scale them down, delete them, or run Reset Environment to get a 3rd. The later has been the solution so far without many knowing the cause.

Additionally, if you delete the space the pod is still allocated and you can no longer access it from OSIO so you can't do anything to it.

**Comment by qodfathr** [comment]
@andrewazores 
> When a pod is allocated, the resource quota is allocated with it and is static.

When does that happen?

> so what action is there to do other than fail the deployment and notify the user after the fact

Well, it could **not** fail the *pipeline* itself, but instead pause it, inform the user, let the user take corrective action if they so choose, and then the user can resume the pipeline, repeating the deployment step. That's just one example solution; I can think of others. The point is this -- we need to holistically think  about the end-user experience and design the best solution. If we employ design thinking techniques and approaches, I'm confident we can come up with the correct solution which is in alignment with other service changes and features planned for both the near and longer term.

#2629 is properly not a p0, not due to its size but due to the fact that it's not meeting the current criteria for a p0. It is not a blocker.

@joshuawilson I agree that reset env has been "the solution," but I honestly feel that's because people are far too quick to jump into chat and suggest "reset env," rather than showing users how to actually scale down the pods themselves (even if it means jumping over to OSO). Reset env is a very big hammer being used against very small nails. Every time a user clicks Reset Env, we should consider that to be a failure.

If you delete a Space, you can still go to OSO and clean things up associated with it. It is not ideal, but it is a **much** smaller hammer. There is no reason to lose all of your other Spaces (including all of your work items) just because you need to scale down a single pod or delete a route.

@rkratky do we have documentation on how a user can do manual clean-up in OSO without having to resort to reset env?

**Comment by joshuawilson** [comment]
Based on @qodfathr statement/view removing P0.

**Comment by animuk** [comment]
I think, this qualifies sev3, as this is not breaking any user experience and considered as more of preventive measure.

**Comment by mishaone** [comment]
Docs will be adding a *before you start* section with warnings about recommended usage (online rather than pro), and advising users that they can only have two projects (using two pods) and then they must reset the environment because that's the OSO limit.

**Comment by joshuawilson** [comment]
@animuk how is this a SEV3 and not breaking UX? If the user doesn't know it, they will try to start a new app and think it all works while the build fails silently. Then they think the whole system is junk. If they then go and delete one of the apps, they can't even spin it down. Then they ask in an issue or on chat and someone tells them that they will need to wipe out everything with `reset environment`. This is a horrible user experience.
