### ISSUE TITLE
when not logged in you get 3 error notifications when visiting a space page

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3347]
goto https://openshift.io/openshiftio/openshiftio and don't be logged in.

Then when page loads you get this:
![2018-04-28_00-15-56](https://user-images.githubusercontent.com/54129/39387412-c1716776-4a79-11e8-911f-22558e1bbf49.png)

expected result is no errors/warnings of any kind as being logged out is what majority of people will be :)

**Comment by alexeykazakov** [comment]
```
Request URL: https://auth.openshift.io/api/users
Request Method: PATCH
Status Code: 401 Unauthorized
```
```
Request URL: https://api.openshift.io/api/user/services
Request Method: GET
Status Code: 401 Unauthorized
```

@joshuawilson looks like some recent changes in UI now tries to modify user profile (recent spaces) and call wit to get tenants for the user even if user is not logged-in.
This is a regression.

**Comment by alexeykazakov** [comment]
Might be related to https://github.com/fabric8-ui/fabric8-ui/pull/2764

**Comment by joshuawilson** [comment]
Yeah, I was concerned that the PR might have side-effects. 
@dgutride @jiekang @andrewazores can you please look into this.

**Comment by joshuawilson** [comment]
@qodfathr this impacts only logged-out users. Is this a P0?

**Comment by qodfathr** [comment]
@joshuawilson not today it isn't. Part of our upcoming permission model is supposed to model both authenticated users (users that have logged in but are otherwise not part of the Space) and anonymous users (users that have not logged in). I think it makes the most sense to address this is conjunction with that work -- it simply becomes a permission check for the current user against the desired information, and should work in all use cases.

**Comment by jiekang** [comment]
This is definitely because of https://github.com/fabric8-ui/fabric8-ui/pull/2764

However, this behavior is actually nearly equivalent to before, just verbose.

```
if (this.userService.currentLoggedInUser.attributes) {
-            let cluster = this.userService.currentLoggedInUser.attributes.cluster;
-            let console = cluster.replace('api', 'console');
-            _latestOAuthConfig.openshiftConsoleUrl = console + 'console';
-          }
```

was replaced by:

```
          this.userService.loggedInUser
            .first((user: User) => user.attributes !== null && user.attributes.cluster !== null)
            .subscribe(
              (user: User) => {
                let cluster = user.attributes.cluster;
                _latestOAuthConfig.openshiftConsoleUrl = cluster.replace('api', 'console') + 'console';
                _currentOAuthConfig.next(_latestOAuthConfig);
              },
              (error) => {
                this.errorHandler.handleError(error);
                this.logger.error(error);
                this.notifications.message({
                  type: NotificationType.DANGER,
                  header: 'Error: Configuration setup',
                  message: 'Could not acquire user credentials for oauthconfig setup'
                } as Notification);
                _currentOAuthConfig.next(_latestOAuthConfig);
              }
            );
```

In the logged out situation, previously the if statement would evaluate false. Now it attempts to acquire the logged in user, but errors and notifies of the issue. I'm surprised that the `UserService` from `ngx-login-client` would emit an error value for `loggedInUser` when we are not logged in. I would expect it not to emit anything in a logged out state and emit errors if there are issues when we are logged in.

**Comment by jiekang** [comment]
Okay on actual analysis, console outputs:

`_scrollbars.less:6 TypeError: Cannot read property 'cluster' of undefined`

So it looks like my `first()` predicate check needs to also skip 'undefined' attributes.

**Comment by jiekang** [comment]
The two 401 unauthorized errors come from other http requests from components on that page being verbose. If I were to guess it's probably the deployments API.

I think there needs to be some standardization of component logic regarding the permission model. As well, UX designs should encapsulate theses states as well: authenticated && authorized, authenticated && !authorized, !authenticated && !authorized.

**Comment by jiekang** [comment]
The console has 404 outputs from CreateWorkItemWidgetComponent and EnvironmentWidgetComponent. I'm haven't investigated what's outputting the error notifications.

**Comment by jiekang** [comment]
The oauthconfig issue has been resolved.

**Comment by joshuawilson** [comment]
Next we need to handle the 401 not authorized errors. I would think that we don't need to display this to the user. Shouldn't even report it as an error to the console or on Sentry.

We need to tell the user to log in when they try to do something but not a huge error message when they visit the page.

**Comment by qodfathr** [comment]
Let's make sure we get UXD's viewpoint on the proper behavior. I can imagine all sorts of possibilities.

1. Any action requiring the user to be logged in, when attempted, sends the user to the log in experience.
2. Any action requiring the user to be logged in is not presented in the UI at all.
3. The display of data requiring the user to be logged in is replaced with placeholder text (e.g. "Please log in to see this")
4. Any data which requires the user to be logged in is not displayed and the UI is reflowed as if that data does not exist. (e.g. don't even show the empty region where the data would have been)
5. In topnav or elsewhere, have an indication that there is more to see/do on this page, if you are logged in and authorized to see/do it.

etc.

cc: @catrobson

**Comment by catrobson** [comment]
@openshiftio/uxd-team 

Right now our strategy mostly aligns to Todd's outline about, and is that:
* The user should be able to navigate to most screens, regardless of their logged in status.  There are a few exceptions outlined here in the 'log in required' column: https://docs.google.com/spreadsheets/d/1cNSDuek0v1EBPpdPlFwG_Y_yOlux86m9MYf9UrF82l4/edit?usp=drive_web&ouid=110291179327641160262.  Going to these screens should not result in any toast notifications with errors as shown at the top. 
* Any data which requires the user to be logged in is not displayed and the UI is reflowed as if that data does not exist. (e.g. don't even show the empty region where the data would have been)
* If the result is that the page is empty due to this, an [empty state](http://www.patternfly.org/pattern-library/communication/empty-state/) should be shown that explains the log-in may be required to access information shown on this page with a button to log in.  Navigation should still be present as well allowing the user to navigate to other pages that may show content when logged out.

We've talked about Todd's bullet 5 - having an indication that they might want to log in since there is more they cannot see on the page - but haven't designed anything for this yet.  I'd like to see us accomplish the first set of items and we can improve with this final addition incrementally.

**Comment by joshuawilson** [comment]
We also have an interesting case when a whole page (like the Planner) is behind a feature flag. Currently it shows the page that tells them they need to change the settings. But they would need to be logged in to see it. Should this page be completely hidden from a non-logged in user?

**Comment by jiekang** [comment]
@dlabrecq Do you know if UXD is aware of the need to have designs for state around not logged in user?

E.g. When not logged in, the widgets on the space now are permanently in the 'Please wait while we load...' state. I think there should be a state of some kind that tells the user that the information is unavailable because they're not logged in.

**Comment by dlabrecq** [comment]
That particular issue is related to the subscriptions not returning a value. It's possible that we could have a different empty state for when the user is not logged in, but believe this needs to be fixed first.

https://github.com/openshiftio/openshift.io/issues/3705
