### ISSUE TITLE
cannot update profile email back to login email address

### ISSUE THREAD

**Issue by christianvogt** [openshiftio/openshift.io#3384]
When I log into openshift.io, I can do so using my redhat email address. However I have my profile set with my gmail email address. I tried to update my profile and assign my redhat email address but I encounter the following error 400:

> {"errors":[{"code":"bad_parameter","detail":"Bad value for parameter 'email' (expected: 'unique email') - ","status":"400","title":"Bad parameter error"}]}

My account is clearly linked to my redhat email address because I can use it for login but the system will not let me set it in my profile.

I have no issues setting my email address to some other arbitrary email address and then back to my gmail email address. I also tested changing out primary email address on another account and did not have any issues going back and forth between email addresses.

**Comment by alexeykazakov** [comment]
When you logging into OSIO you actually logging into developers.redhat.com (RHD)
Emails in RHD are not unique. You can have multiple accounts with the same email.
But emails in OSIO are unique. I guess this is what happened:
- You signed up as christianmvogt (with your RH email)
- You updated your email in OSIO to the gmail one (your RHD email for that account is still @redhat.com) - We can't sync emails (and other info) between RHD and OSIO accounts. This is a known issue.
- You signed up as christianvogt (it's a different RHD account but with the same RH email). You were  able to do it because in OSIO the email for this account is now @gmail.com

As result you now have two OSIO accounts with two different emails but you can login using the same RH email because in RHD both accounts have the same RH email.

The route issues here are:
- We don't sync emails between RHD & OSIO
- Emails are not unique in RHD but unique in OSIO

**Comment by christianvogt** [comment]
@alexeykazakov Thanks for the details explanation. I forgot about that other account. I had signed up to OSIO before joining RH and then created another account afterwards.

I was able to switch my RH email over to my primary account.

Is there any value in keeping this issue around? sync issue? Maybe it's already captured in other issues.

**Comment by alexeykazakov** [comment]
Yes, we have it already captured in https://github.com/fabric8-services/fabric8-auth/issues/33 (sync issue) and https://github.com/openshiftio/openshift.io/issues/2332 for RHD users with the same email issue (plus a houskeeping issue with more details).
So, I think we can close this one.
