### ISSUE TITLE
Investigation: Initial loader for OpenShift.io (3)

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3456]
Right now we have an indeterminate loader for the first load of OpenShift.io.  We'd like to investigate whether we could make this a determinate loader/progress bar, or if we can determine how to load into the application quickly enough that a loading state is no longer necessary.

Verification Criteria:
* Investigation into options, and results posted into this issue
* Discuss with @lwrigh to determine if any designs need to be updated given understanding

**Comment by dlabrecq** [comment]
After looking at the code, I confirmed there is nothing quantifiable to show here for a determinate progress bar. We're really not downloading anything, but waiting for a ready state (e.g., authentication, etc.). 

What would help here is to enable Angular's ahead-of-time (AOT) compilation. Instead of a progress bar, the user would start out viewing the page immediately while the various widgets load in the background. I believe work to enable AOT is planned, but it's a significant task to complete.

**Comment by dlabrecq** [comment]
Discussed with @lwrigh and we appear to be using Patternfly's animated progress bar shown here:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/progress-bars.html

However, there is also a spinner:
![screen shot 2018-05-07 at 10 54 36 am 2](https://user-images.githubusercontent.com/17481322/39708473-4d9d3fe6-51e5-11e8-8d78-9387ae3195c5.png)
According to the GitHub history, @mindreeper2420 added the progress bar and spinner on 7/14/17.

`"replace the OpenShift.io logo with a larger progress bar and including 'Loading...' text with spinner"`

Considering Adam added this, we may want to wait for AOT compilation to be enabled? The progress bar would then just go away.

**Comment by catrobson** [comment]
+1 that the next step should be AOT then.  Thanks for looking into this @dlabrecq.  @bdellasc we can close the Visual design story for the OSIO loader due to Dan's investigation.

**Comment by bdellasc** [comment]
@catrobson There are a couple of stories related to this...

I also found [this one](https://github.com/openshiftio/openshift.io/issues/3156) that you created. Reading through this - I think this is the story speaking specifically about the first time loader?

#3459 still feels like it's valid to me since it's looking across screens in the UI and a follow-up to Laura's #2870 ? Just wanted to verify before I actually close the one I created.

**Comment by catrobson** [comment]
@bdellasc I think all of Laura's remaining designs are now just spinners in screens that follow patternfly standards other than this first loading screen.  @lwrigh can you confirm and update your wireframes if needed given discussion?  I think you could remove the skeleton loader as discussed as a team and just go back to the empty state page loader for the deployments page case.  @mceledonia can weigh in on this again if needed.  If this is true, I don't think we need any visual design effort as we can just follow PF standards.

**Comment by catrobson** [comment]
#3156 could also be closed, it sounds like Adam already did a first pass
towards using PF on this which will hold us over until we have AOT.

**Comment by catrobson** [comment]
Closing this story.
