### ISSUE TITLE
basic/minimal woopra/segment events from che needed

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3479]
atm. che usage is invisible in woopra/segment - no usage data at all.

Can we get some basic things in like 

a) open of workspace from osio
b) a basic ping when pages accessed
..others ? like workspace started/stopped could be useful.

if hard part is to inject callbacks in eclipse che maybe do it at the level of kubernetes/openshift.io integration points - like "start/stop of workspace pods" ?

**Comment by slemeur** [comment]
see: https://github.com/redhat-developer/rh-che/issues/630

**Comment by joshuawilson** [comment]
Rahul Manchanda is the one to talk to about Woopra

**Comment by ibuziuk** [comment]
Closing since basic woopra reports are already available for che [1] e.g.:
- running / active workspaces
- workspaces started from factories
- stacks 
- factories
- programming languages used 

More complex telemetry events are planned to be added as part of the https://github.com/redhat-developer/rh-che/issues/765

[1] https://www.woopra.com/live/project/test.openshift.io/reports/analytics/ujyyyn0bw9
