### ISSUE TITLE
[BUG] Hide email from public profile

### ISSUE THREAD

**Issue by webknjaz** [openshiftio/openshift.io#3499]
Hello,

I've got "private" radio selected in my profile settings, however on the profile page `https://openshift.io/<user_login>` it effectively displays my email address (which I obviously want to hide from public)

**Comment by webknjaz** [comment]
Yes, I tested this in an Incognito tab

**Comment by alexeykazakov** [comment]
The private email works fine (for example you won't see email in my account - https://openshift.io/alexeykazakov). What you see is actually your username. Not your email. Some old OSIO (developers.redhat.com) accounts got auto-generated usernames during registration. And for some accounts the auto-generated usernames matched account emails. This bug is fixed now and users can chose their own username during registration.

Unfortunately we do not support username changes atm. The only way to get another username is to register a new user.
I'm closing this issue. Please reopen if you think you still can see the actual email. Not username.

**Comment by webknjaz** [comment]
Ah.. I see, thanks! You are right.
