### ISSUE TITLE
Support NodeJS Booster in che

### ISSUE THREAD

**Issue by sunilk747** [openshiftio/openshift.io#3510]
OSIO Users should be able able to build NodeJS boosters as a part of launcher flow and proceed with creating the project out of it.

Acceptance Criteria

- NodeJS Boosters should be able to do :

     -- Build in Che

     -- Run in Che

     -- Autocompile in Che

**Out of Scope:**
- N/A

**Comment by jarifibrahim** [comment]
To support Node boosters (let's say https://github.com/nodeshift-starters/nodejs-rest-http)  the following changes have to be made
1. The `nodejs` boosters have to be enabled in launcher backend, they're disabled right now. (https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master/nodejs)
2. The supported pipelines for `nodejs` have to be enabled. The UI doesn't show any pipelines related to node project. It shows only `maven` related pipelines currently. See https://github.com/openshiftio/openshift.io/issues/4154 

3. The launcher backend uses `nodejs-centos` stack to start the che workspace if the repository contains `package.json` file. This stack doesn't work out of the box for all nodejs boosters. We'll have to either make changes to the stack definition (https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json#L960) or modify the boosters so that they work with the same stack. 

    One of the issues with this stack is the command used to run `nodejs` applications in che. By default, run command is `cd ${current.project.path} && node app/app.js` and it won't work because the `app.js` file might not always be in the `app` directory. 

    The `nodejs-centos` stack also lacks command for autocompile, we'll have to add that too.

The step 3 can be executed independently via API calls. The easiest way is to create codebase via UI (use java as runtime and pipeline) and then using the following curl request to create a workspace with `nodejs-centos` stack 
```
curl -X POST -H "Authorization: Bearer $tkn" \
-d '{
    "data": {
        "attributes": {
            "stackId": "nodejs-centos",
            "type": "git",
            "url": "https://github.com/nodeshift-starters/nodejs-rest-http.git"
        },
        "type": "codebases"
        }
    }' \
"https://api.prod-preview.openshift.io/api/spaces/ef103b91-462a-42a8-91db-148413abeed0/codebases"
```
The resulting workspace created on che can run node applications after slight modification to the run command (it should be `cd ${current.project.path} && node app.js` instead of `cd ${current.project.path} && node app/app.js`

To support multi-container boosters we'll have to create new stacks with appropriate machine declarations.

cc @sbose78

**Comment by sbose78** [comment]
> The nodejs boosters have to be enabled in launcher backend, they're disabled right now. (https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master/nodejs)

Story tracked in the plan:
https://openshift.io/openshiftio/Openshift_io/plan/detail/1045

**Comment by sbose78** [comment]
> To support multi-container boosters we'll have to create new stacks with appropriate machine declarations.

Tracked:
https://openshift.io/openshiftio/Openshift_io/plan/detail/1034

**Comment by sbose78** [comment]
@jarifibrahim 

> This stack doesn't work out of the box for all nodejs boosters. 
Could you be more specific, please? 

That way we'll be able to decide if we would wanna change boosters or the stack, or both.
( https://openshift.io/openshiftio/Openshift_io/plan/detail/1033 )

> The nodejs-centos stack also lacks command for autocompile, we'll have to add that too.

OK. Let's track the task as part of https://openshift.io/openshiftio/Openshift_io/plan/detail/1033

**Comment by bartoszmajsak** [comment]
@jarifibrahim probably known by now, but:

> The nodejs boosters have to be enabled in launcher backend,

Is a matter of adding:

```yaml
metadata:
  app:
    osio:
      enabled: true
```

in the corresponding `yaml`s.

**Comment by ibuziuk** [comment]
@jarifibrahim @sbose78 do you think we can close this issue now ?

**Comment by jarifibrahim** [comment]
Yes. The Nodejs boosters work fine in Che. I'm closing the issue.
