### ISSUE TITLE
Deleting a Space from the all spaces view does not show any indication it is working

### ISSUE THREAD

**Issue by InfoSec812** [openshiftio/openshift.io#3536]
To reproduce:

1. Create a new space
2. Switch to "View all spaces"
3. Click the "Trash" icon
4. Confirm deletion

Expected: Some sort of visible indication that the delete operation is in progress

Actual: No visual indication until the delete is complete and the modal dialog disappears

Suggested resolution: Add a "spinner" to indicate the operation is in progress

**Comment by ldimaggi** [comment]
Note - After the user confirms the deletion - there is a ~5+ second delay until the space is deleted. During this time - there is no feedback to the user and nothing is written to the browser console log. Also, there is no feedback to the user after the deletion is complete:

![screenshot from 2018-05-21 14-53-59](https://user-images.githubusercontent.com/642621/40324678-365159c6-5d07-11e8-901e-6f299f900797.png)

![screenshot from 2018-05-21 14-55-13](https://user-images.githubusercontent.com/642621/40324677-363b46d6-5d07-11e8-8c7b-66e988247125.png)

**Comment by catrobson** [comment]
We need to add Search to find other spaces to the /_myspaces page so that we can remove this page from the application all together.  This is the longer term UXD plan for this page - retire it.

**Comment by lwrigh** [comment]
Here's a document capturing some UX recommendations for toast notifications across the board: https://docs.google.com/document/d/1Hf1WaKJBdZ-ouLD9IcrWoH8fiFyf6SUKgVJ6YjVJ_Mc/edit?usp=sharing 

One suggestion would be to add a "x" to all toast notifications so the user can dismiss it whenever they like instead of just waiting for it to time out. Here's a PatternFly example of what a toast notification with a "x" looks like: 

<img width="309" alt="screen shot 2018-05-25 at 1 02 28 pm" src="https://user-images.githubusercontent.com/20227374/40556807-0919b4ea-601c-11e8-96a4-7456cb8a5e5a.png">

**Comment by joshuawilson** [comment]
I'm waiting on @openshiftio/uxd-team to tell me what they want.

**Comment by joshuawilson** [comment]
@serenamarie125 do we need to do anything else on this?

**Comment by serenamarie125** [comment]
@joshuawilson I'm fine with this being closed for a number of reasons

1. i just tested this on the live instance, and the space is deleted immediately
1. this page is being removed as part of quick wins ( may have already been )
1. there are a number of other issues discussed here, but the description is about space deletion from the All Spaces page

**Comment by joshuawilson** [comment]
Thanks, closing.
