### ISSUE TITLE
Cannot see author of a comment in planner

### ISSUE THREAD

**Issue by psrna** [openshiftio/openshift.io#3609]
![screenshot 2018-05-22 15 27 59](https://user-images.githubusercontent.com/2078092/40365625-40557ff0-5dd5-11e8-82f8-bcf235420fba.png)

**Comment by sanbornsen** [comment]
Duplicate to https://github.com/openshiftio/openshift.io/issues/2940

**Comment by psrna** [comment]
@sanbornsen the issue you linked above is closed. But this is still a current problem. We need to reopen that one, or work on this one.

**Comment by sanbornsen** [comment]
@psrna this issue was linked to a commit. As the commit is merged into the master, the issue got closed automatically. I don't suggest you, to close this one, but wait for the production to be updated. It'll take some time.

This PR needs to go in in order to get the changes in `prod-preview` - https://github.com/fabric8-ui/fabric8-ui/pull/2932

**Comment by psrna** [comment]
@sanbornsen thx for clarification.

**Comment by nimishamukherjee** [comment]
Fix is in production.
