### ISSUE TITLE
What features should not be available when visiting another user's/space's deployments tab?

### ISSUE THREAD

**Issue by chrislessard** [openshiftio/openshift.io#3637]
If I visit another user's space's deployments page, i.e. by navigating to `/<username>/<spacename>/deployments` and no deployments are available, should I be allowed to click the "Add an application" link that currently display's there? What should happen if I do? What data should be displayed, about what deployments?

Here's a screenshot:

<img width="1440" alt="screen shot 2018-05-24 at 3 53 31 pm" src="https://user-images.githubusercontent.com/17230733/40510484-d84ee83c-5f6a-11e8-94b2-51e5c319c4ee.png">

Parent: https://github.com/openshiftio/openshift.io/issues/3638

**Comment by andrewazores** [comment]
https://github.com/openshiftio/openshift.io/issues/3660 also has some connection to this question.

**Comment by andrewazores** [comment]
https://github.com/openshiftio/openshift.io/issues/3660 is also connected to this question.

**Comment by joshuawilson** [comment]
@qodfathr @openshiftio/uxd-team can you weigh in on this?

**Comment by aptmac** [comment]
In the same vein as the first image, we questioned this as well with the empty-states page for when there are no deployments [0], because the help text asks you if you want to checkout your resource usage in your Settings page, or to check your pipelines page for upcoming deployments [1].

[0] https://github.com/fabric8-ui/fabric8-ui/pull/2935#discussion_r190551750
[1] https://user-images.githubusercontent.com/10425301/40444088-5688c87e-5e96-11e8-8df9-d326f3a97cae.png
