### ISSUE TITLE
Add work item and Add Iteration options are showing enabled for a non-collaborator

### ISSUE THREAD

**Issue by rgarg1** [openshiftio/openshift.io#3644]
For a non-collaborator, the fields to 'Add work item' and 'Add Iteration' are showing as enabled.

But when the user tries to create a new item, he's rightly blocked by the backend API.

The UI needs to be updated so that these fields _do not_ show as enabled for a non-collaborator.

Proof:
![noncollab add wi and iter](https://user-images.githubusercontent.com/28748448/40534176-c8601c44-6022-11e8-83b7-1a35c4b5991f.gif)

**Comment by rgarg1** [comment]
@Veethika WDYT?

**Comment by Veethika** [comment]
@rgarg1 the action items restricted for a non-collaborator should appear disabled already instead of giving an error message later and keeping the user wondering about what exactly went wrong.

@sunilmalagi @nimishamukherjee However, it could also be a good idea to have a warning at top of the page to communicate to the user that they cannot make changes to the space as they are not a collaborator. Let me know what you think?

**Comment by rgarg1** [comment]
Thanks @Veethika for the confirmation. Yeah, it would be a good idea to upfront let a non-collaborator know that they need permissions in order to edit.

**Comment by Veethika** [comment]
^Since the UX solution has been provided I'm removing myself. Please reassign if needed.

**Comment by christianvogt** [comment]
@Veethika why should it appear disabled vs hidden? If disabled, is there a message informing them how to enable the capability? ie contact a space admin to add them as a collaborator?

Looks like the add work item fields are disabled but adding an interation button is still enabled and fails with a error 403 when trying to create a new iteration.

**Comment by Veethika** [comment]
@christianvogt my concern was that there would be many actions that a collaborator wouldn't be authorized to perform, hiding each one of them might result in a change of a few layouts as well. 
Hiding is definitely a better option, but that could be well implemented once we are sure of the actions associated with each role.
IMO there could potentially be a larger exercise.

**Comment by christianvogt** [comment]
I agree that for now it's ok to stick with disabling the fields.

My general view is that if the user can perform an action on the page to enable the controls, they should be disabled. Otherwise they should be hidden.

I'd like UX to provide some general guidelines around this behavior and start to create their designs with this behavior in mind especially now that we have more roles and permissions based UI being implemented.

**Comment by serenamarie125** [comment]
@joshuawilson good points, and the UX proposal should be consistent across the product.

If a user cannot perform an action, it should not be shown (hidden).
If an action cannot be performed due to it's current state, it should be shown and disabled.

Going forward we need to have this generic guidance documented and incorporated into all designs going forward.

**Comment by serenamarie125** [comment]
Based on a conversation held on 2019-Jan-04 including Dev, PM and UX, the UX team will not be providing support for planner items. Removing the team/ux label and un-assigning UX folks. If priorities are changed in the future, please add the team/ux label
