### ISSUE TITLE
[5] Validate new Graph backend works as expected

### ISSUE THREAD

**Issue by yzainee** [openshiftio/openshift.io#3677]
Planner: [2157](https://openshift.io/openshiftio/openshiftio/plan/detail/2157)

Tasks:

- [x] Able to reuse titandb data wigh new janusgraph backend.

- [x] Indexes works as expected

- [x] Data importer works as expected

Description

As an openshift.io engineer, I need to validate new Graph backend works as expected by performing a small graph-sync job.

Size ?

Acceptance

    On pushing the images on dev-cluster, dynamodb tables gets successfully created.
    Run a small graph sync job to validate data model works as expected.

Assumptions

None.

**Comment by miteshvp** [comment]
@yzainee - this verification would have worked in case of not migrating old titandb based data onto new janusgraph. Since we want to migrate the data, the accepted verification should change to something like 
- able to reuse titandb data wigh new janusgraph backend. 
- indexes works as expected
- data importer works as expected

**Comment by yzainee** [comment]
Population of data is hurdled as the data importer deployment is getting failed

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/gremlin-docker/pull/42

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/gremlin-docker/pull/43

**Comment by yzainee** [comment]
https://github.com/fabric8-analytics/gremlin-docker/pull/48

**Comment by yzainee** [comment]
https://github.com/rhdt/EL-Dockerfiles/pull/63 This PR needs to be merged in order to get wget which can be used in the dockerfile.rhel file
