### ISSUE TITLE
[Planner] Quick add looks like search bar

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#3696]
Today, I added two new issues into planner, just because I wanted to search for an issue. 
Then I looked on all "closed" issues and it seems I'm not the only one who did this silly mistake.
It's probably because the place, where Quick Add is located, is the place where usually (in other systems like JIRA for example) is the search bar.
![searchbar](https://user-images.githubusercontent.com/1215011/40775514-8f36537a-64c8-11e8-8669-be9ceb518612.png)

**Comment by aptmac** [comment]
I've done this before as well, the add item bar seems really unintuitive. However, this issue is already open twice once as a feature request [0] and once as a bug [1], so I'll close this one as a duplicate and discussion can happen on the other issues.

[0] https://github.com/openshiftio/openshift.io/issues/3552
[1] https://github.com/openshiftio/openshift.io/issues/3595
