### ISSUE TITLE
adding link is really tedious as UI is not indicating it actually worked

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#3706]
Here is me trying to add a link to an existing issue and the combox is rendered weirdly but worst is that when selecting a workitem the UI is not updated to show I selected it. 

Turns out when clicking link it at least seem to do the right thing - can't be sure as when rendered in list the workitem number is no longer shown.

![2018-05-31_23-34-06](https://user-images.githubusercontent.com/54129/40809616-65a61d7a-652b-11e8-8185-dd4d7766954d.gif)

**Comment by rgarg1** [comment]
Good suggestions @Veethika. We also would need to display WI IDs in the list of existing links. Do we need a mock UI before we get executing on this? @nimishamukherjee

**Comment by nimishamukherjee** [comment]
@Veethika @sunilmalagi we need to come up with a layout option for linking which has a better readability.
The current layout is confusing.

Maybe something like
What would you like to link with "work item title [work item id]]
_work item dropdown_
How would you like to link the two
_relationships dropdown_

Another consideration would be, if we would like to introduce add of children on the detail page. If yes,
we can align linking work flow and work item child creation so that there is 1 - 1 correlation.

**Comment by Veethika** [comment]
@nimishamukherjee @rgarg1 we should allow adding children on the detail page, but it should be looked at in a different story altogether along with few other changes to the detail view. Does this sound fine? 
For now, we could limit this story to giving VD options for the linking action flow.

**Comment by nimishamukherjee** [comment]
Sounds good @Veethika

**Comment by sunilmalagi** [comment]
@Preeticp Can you please look at the wording link section, I will work on the visuals based on your inputs..

**Comment by sunilmalagi** [comment]
@maxandersen @nimishamukherjee Here is the visuals flow for the Linking section with required changes made, also got it reviewed with UX and Dev teams: https://redhat.invisionapp.com/share/BAN4UOBQHSN#/310977348_AddLink_01

**Comment by joshuawilson** [comment]
This is done and in production.
