### ISSUE TITLE
Animations Differ Between User Profile and Settings Navs

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/openshift.io#3724]
On the User Profile page, the navigation used to switch between "My Work Items" and "My Spaces" differs from that found under the Settings page.

Under User Profile, there is a noticeable jump when going between the two sections, as well as a different animation for the hover and active line under the link.

User Settings, the active line under each link is animated to fade and slide in from underneath the link text. On hover, there is no underline.

**User Profile**
![profile](https://user-images.githubusercontent.com/4032718/40863978-e42c8334-65bf-11e8-81ab-f99be1756f41.gif)

**Settings**
![settings](https://user-images.githubusercontent.com/4032718/40863950-cae11750-65bf-11e8-96f4-e76cda21aabb.gif)

**Comment by andrewazores** [comment]
What's the preferred behaviour?

**Comment by chrislessard** [comment]
Regarding the underline on hover : 

I've scrolled through my original PR, and it wasn't explicitly mentioned (https://github.com/fabric8-ui/fabric8-ui/pull/2711) : "Yes we should definitely include a hover state. I think if you make the text change color to the same blue color it changes to when it's selected, that should be great. That still separates it from the selected state because of the underline." I assumed this meant top get rid of the underline that occurs when you hover over a link.  

Does the cursor always change when you hover over a link ? If we have any colour blind users, they necessarily wouldn't be able to see the change to blue .. maybe in that case an underline would be a good idea.

**Comment by andrewazores** [comment]
"necessarily wouldn't" is bad phrasing there - more like "wouldn't necessarily". It would depend on the type of colour blindness the individual experiences. (I'm not sure that any of the forms of colour blindness result in difficulty distinguishing black from light blue, though) /pedant-mode

**Comment by chrislessard** [comment]
Ah, my bad :) 

Fair enough, i'm no expert either, it was just something that crossed my mind. @mceledonia since you were the one helping me with that PR, what do you make of this ?

**Comment by jiekang** [comment]
Agree with underline on hover and the animations on the Profile page are definitely fishy. I can't believe I didn't notice that when testing it myself :(

**Comment by andrewazores** [comment]
Taking a cursory look at this, it seems that the main "Create" tab navigation (Codebases/Pipelines/Deployments) and the Settings tab navigation look and feel the same, and Profile is different from these.

Create and Settings both use router links for navigation, where Profile has its own hand-rolled tab index solution rather than using a router outlet and child views. IMO Profile's tab system should be replaced with a router outlet, and this will probably also fix the look and feel. Adding the underlines can then probably be done application-wide since all of these router based tab navs should have the same styles applied.

**Comment by chrislessard** [comment]
@andrewazores "Profile's tab system should be replaced with a router outlet"

I second this as a good idea.
