### ISSUE TITLE
Handle logout scenarios for 401s without a jwt error

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#3736]
The PR https://github.com/fabric8-ui/ngx-login-client/pull/111 does not handle 2 corner cases

1. The backend returns a 401 in cases where the jwt is valid but the associated identityID does not exist in the system. In general, this scenario shouldn't happen.

2. For a deprovisioned user, the jwt is valid, but the backend returns a 401 for API calls which do 'writes'. Example if a deprovisoined user tries to create a space, 401 is returned. So the changes in this PR wouldn't trigger a logout anymore for a deprovisioned user.

This task is being tracked to work on handling the above scenarios.

**Comment by alexeykazakov** [comment]
I think we should just start returning `WWW-Authenticate: LOGIN` headers along with 401 response when we want the client to relogin user. This will require changes in all our backend services. So when the user access token is not valid our services should add `WWW-Authenticate: LOGIN` header to the response.
It's kinda related to https://github.com/openshiftio/openshift.io/issues/2118

**Comment by alexeykazakov** [comment]
Another use case is when the token is valid but Keycloak session was killed (because we had to kill all KC pods and restart them for example or because user logged out in a different browser tab). In this case our token refresh endpoint will return 401 without a jwt error. I suspect this is what happened in https://github.com/openshiftio/openshift.io/issues/3746
