### ISSUE TITLE
Visiting another users profile page breaks the inner navigation

### ISSUE THREAD

**Issue by jiekang** [openshiftio/openshift.io#3747]
Edit: Possibly an intermittent issue. May be some race condition around the asynchronously tracked variables; could be investigated if it can be triggered on user X page when logged in as user X too...

If you visit user Y profile page while logged in as user X, the inner navigation, (work items and spaces tabs) are broken.

Steps to reproduce:

1. Visit user Y profile page as user X, e.g. if not jkang, visit https://openshift.io/jkang@redhat.com
2. Click back and forth between the work items and spaces tabs.
3. See images below for an example
   - Expected: Switches between widgets
   - Actual: Widget is added to the page. As you click back and forth, more and more widgets appear.

![profile-1](https://user-images.githubusercontent.com/5430520/41056674-f450cdac-6992-11e8-8d45-8391f900159b.png)
![profile-2](https://user-images.githubusercontent.com/5430520/41056675-f5865732-6992-11e8-9e3c-33f4eebae86f.png)

**Comment by jiekang** [comment]
@rohitkrai03 If you have time could you take a look this? Triage and delegate as needed.

**Comment by aptmac** [comment]
fwiw this seems to be sporadic; I ran into it about 3 times in a row but haven't been able to recreate it since. When running locally I managed to get a glimpse of the logged error, it was complaining about a null `attributes` value for `loggedInUser.attributes` in the [work-items component](https://github.com/fabric8-ui/fabric8-ui/blob/0f8a284b99d14244cd3e38dfcdc2d1765aa6e437/src/app/profile/overview/work-items/work-items.component.html#L42) [0]

[0] https://github.com/fabric8-ui/fabric8-ui/blob/0f8a284b99d14244cd3e38dfcdc2d1765aa6e437/src/app/profile/overview/work-items/work-items.component.html#L42
