### ISSUE TITLE
Planner locks up and creates visual artifacts when expanding a tree while quick view is open

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#3785]
While using the planner these extra arrows appear and extra text. The more I click the more I get. 

To reproduce:
1. view a work item in quick-view
2. expand the tree in a different work item

I was able to resolve it by refreshing. But you lose whatever you were working on. 

![plan backlog openshift io](https://user-images.githubusercontent.com/1184371/41374043-17993e6a-6f20-11e8-91db-7a8065272dda.png)

**Comment by rgarg1** [comment]
I was able to reproduce this issue on openshiftio space, but not on any other space. It appears that lots of data is needed in order to encounter this issue.
Steps:
1. Open a random WI and add a couple of labels to it. Once added, remove both labels
2. Keeping the quick-preview window open, try expanding another tree. You should be able to see the issue

**Comment by vikram-raj** [comment]
This issue is fixed by PR https://github.com/fabric8-ui/fabric8-planner/pull/2688.

@rgarg1 Can you please verify.

**Comment by joshuawilson** [comment]
this is fixed in production
