### ISSUE TITLE
Search for my spaces doesn't work if there is a space between words

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3793]
Steps:
- Create a new space say "test space"
- Click on My space( from the drop-down left side of the header)
- Search space by name
- doesn't Work if there is a space b/w the words

searching by test works but searching by 'test space' doesn't work

**Comment by joshuawilson** [comment]
What does "b/w" mean?

**Comment by Raunak1203** [comment]
Sorry b/w- between
updated the title

**Comment by christianvogt** [comment]
When saving a 'space', all whitespace in the name are converted to underscores. They show up as a whitespace in the UI because the names are piped through the `spaceName` pipe which replaces all underscores with a space.

We cannot distinguish between the user entering whitespace or an underscope when creating a space due to the conversion. Then when it comes to filtering, we're trying to match a space against underscores which fails.

**Comment by christianvogt** [comment]
Github allows spaces in the repo name but tells you that the spaces will be converted to hyphens.
![image](https://user-images.githubusercontent.com/14068621/41724701-2212f7a6-753c-11e8-96e1-142fd9378e1f.png)

If the space name does not allow whitespace, we should indicate this and display the name as-is without any transformation. The current `spaceName` transformation is a cause for confusion because that's no longer the real name used for referring to the space.

My suggestion here is to remove all usage of `spaceName` pipe for the space display names. Furthermore disallow spaces in the creation of a 'space', or do like github and convert unsupported characters to a supported character and show the user the final name.

**Comment by alexeykazakov** [comment]
I agree with @christianvogt. We should stop using spaceName pipe and disallow spaces in space names in the new space dialog.

**Comment by andrewazores** [comment]
The spaceName pipe usage has been removed, but I'm not sure the status of space handling in the dialog.

**Comment by jiekang** [comment]
Thanks for the update, I forgot to clear this issue. Spaces are no longer allowed and the pipe has been removed.

Closing as resolved.
