### ISSUE TITLE
Pipeline: No service hubot  is running

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#3798]
1. create a project using pipeline with promote step
2. open Jenkins log

result:
* after project is successfully built and rolled out to stage, the following message appears in Jenkins log
```
Hubot sending to room fabric8_default => Would you like to promote version 1.0.2 to the next environment?

    to Proceed reply:  fabric8 jenkins proceed job ppitonak/e2e-0615-072415/master build 2
    to Abort reply:    fabric8 jenkins abort job ppitonak/e2e-0615-072415/master build 2

No service hubot  is running!!!
No service found!
```
* it should be either fixed or removed

**Comment by piyush1594** [comment]
@rupalibehera @jaseemabid Can we remove this? Is this something not relevant and required?

**Comment by jaseemabid** [comment]
@piyush1594 Yeah, we could go delete hubot references from pipeline library or make it an empty function so that existing Jenkinsfiles won't break.

**Comment by piyush1594** [comment]
@jaseemabid Is this something from here https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/approve.groovy#L14

**Comment by jaseemabid** [comment]
Yeah, I see a few more references to the same function. 

1. This doesn't break anything and is just an annoying line in the logs. Since we usually have 40 java stack traces along with this, this is something tiny that can be ignored. We could make it a SEV3 or 4. Joshua probably just added a SEV2 label to all issues that didn't have a severity so that someone will take a look at it appropriately. 

2. Changing this could break stuff and its worse than an annoying log line.

**Comment by hrishin** [comment]
@ppitonak this is not causing any harm. Now with new `osio-pipeline` it will get removed eventually.

Putting this all, I'm clisng this issue for now. Feel free to open this again.
