### ISSUE TITLE
404 error while opening My Work Items from Profile page

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3868]
Steps:
- Go to My profile page
- then to My Workitem
- And click on workitem where you are not space owner but a collaborator
- throws 404 error

![404_error](https://user-images.githubusercontent.com/34271052/41956378-0c8fa84c-7a01-11e8-873f-bb6a4824b044.gif)

**Comment by aptmac** [comment]
That'll be because of the way the URL is structured - it uses `context.user.attributes.username` [0] so instead of building the URL with space owner's username it'll just use the username of the profile page you're viewing.

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/work-items/work-items.component.html#L42

**Comment by alexeykazakov** [comment]
@rohitkrai03 could you take a look please?

**Comment by rohitkrai03** [comment]
@alexeykazakov Sure.
