### ISSUE TITLE
Settings & Profile navigation selection should slide, not drop in

### ISSUE THREAD

**Issue by catrobson** [openshiftio/openshift.io#3889]
The Settings and Profile navigation has a blue selection state.  Today, the bar showing the selected tab drops in from top to bottom for the animation.  This should slide horizontally from tab to tab if we're going to animate it, not drop in.  Otherwise we should just remove the animation and follow the basic patternfly style of the tabs: http://www.patternfly.org/pattern-library/widgets/#tabs

Today:
![tabdropinanimation](https://user-images.githubusercontent.com/3739227/42173230-598232ac-7dec-11e8-9623-000924352d98.gif)

**Comment by andrewazores** [comment]
The secondary tab bar under the "Create" menu looks similar to these two but also differs in its hover state and animations, also varying from the Patternfly secondary tab standard. Notably, this one does not have a grey underline on hover, and the text label turns blue on hover rather than remaining grey. Should all three of these instances of secondary tab navigations follow the Patternfly standard you linked? Are there any other instances of secondary tab navs that need to be looked at?

**Comment by catrobson** [comment]
Well, as discussed in this issue https://github.com/openshiftio/openshift.io/issues/3858, we'd like to see two implementations of the secondary navigation.  We should standardize the animations, but the colors might need to be distinct.
