### ISSUE TITLE
Launcher : Creating new space by launcher and clicking cancel issue 

### ISSUE THREAD

**Issue by Raunak1203** [openshiftio/openshift.io#3936]
Steps:
- Click Create space from the drop-down.
- Select Development process
- Enter Space Name
- Click ok
- Wait until URL contains new space name
- Now click cancel
It doesn't work.

![launcher](https://user-images.githubusercontent.com/34271052/42432512-7d9252c2-8368-11e8-9081-1de394086910.gif)

**Comment by aptmac** [comment]
The bug is at `AppLauncherDependencyCheckService` [line 28 [0]](https://github.com/fabric8-ui/fabric8-ui/blob/6945bc98ba76fe4ba65adc75166ca942f5a41519/src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts#L28).
![error](https://user-images.githubusercontent.com/10425301/42527076-a978eac6-8445-11e8-94d9-c5fbfc4343e5.png)

This can be recreated if the user hasn't visited a page outside of the home page, because the `context.current` value will not be undefined.

[0] https://github.com/fabric8-ui/fabric8-ui/blob/6945bc98ba76fe4ba65adc75166ca942f5a41519/src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts#L28

**Comment by sanketpathak** [comment]
@Raunak1203 @vikram-raj  Not able to produce it so closing the issue

**Comment by bartoszmajsak** [comment]
@sanketpathak generally speaking we should ask issue creator to confirm that. @Raunak1203 could you try and see if that still affects the use case you described?

**Comment by Raunak1203** [comment]
Issue is fixed
Verified in production

**Comment by bartoszmajsak** [comment]
Thank you @Raunak1203
