### ISSUE TITLE
Closed workitems should not show up in the context of an 'iteration'

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#3943]
![planner-closed](https://user-images.githubusercontent.com/545280/42509054-bbdc57c8-845b-11e8-8e6d-ae19c86f6c2a.png)

https://openshift.io/openshiftio/Openshift_io/plan/detail/42

**Comment by sbose78** [comment]
@jarifibrahim , assigned it to you - feel free to change the assignment if you need to :)

**Comment by jarifibrahim** [comment]
This issue exists because `SDD (legacy.yaml` template has states
```
        - new
        - open
        - in progress
        - resolved
        - closed

```
while `Agile (agile.yaml)` template has
```
        - New
        - Open
        - In Progress
        - Resolved
        - Closed
```

The request made from frontend is
```
https://api.prod-preview.openshift.io/api/search?page[limit]=200&filter[expression]={%22$AND%22:[{%22space%22:{%22$EQ%22:%22f56d8c04-7acb-4c1a-82d2-dde459cb4a2d%22}},{%22typegroup.name%22:{%22$EQ%22:%22Work%20Items%22}},{%22state%22:{%22$NE%22:%22closed%22}},{%22state%22:{%22$NE%22:%22Done%22}},{%22state%22:{%22$NE%22:%22Removed%22}}],%22$OPTS%22:{%22tree-view%22:true}}
```

Observe that `{ state : { $NE : closed } }` has `closed` with lower case `c`.

@michaelkleinhenz @kwk What do we do? Should we update the yaml files or do we fix the search endpoint to consider `upper and lowercase` expressions as equal?

**Comment by sbose78** [comment]
> we fix the search endpoint to consider upper and lowercase expressions as equal?

This, please :)

**Comment by jarifibrahim** [comment]
Assigning it to @vikram-raj since we will be fixing this in the UI.

**Comment by vikram-raj** [comment]
This issue has been fixed.
