### ISSUE TITLE
Jenkins is Slow to boot at first boot

### ISSUE THREAD

**Issue by chmouel** [openshiftio/openshift.io#3956]
Jenkins is very much still slow to boot for the first time user. It takes over 6 minutes for a first boot

Try first to `oc rsh` into your jenkins pod and `rm -rf /var/lib/jenkins`, you then `oc scale dc/jenkins --replicas 0` to kill it and `oc scale dc/jenkins --replicas 1` to boot it again and you can properly the pain of our first time user trying on openshift.io.

Here is my full log: http://paste.openstack.org/raw/725567/

Logs: https://github.com/openshiftio/openshift.io/files/2245194/jenkins-2.log

**Comment by piyush1594** [comment]
@chmouel Adding it severity-2 tag please upgrade/ downgrade if does not look good.

**Comment by chmouel** [comment]
It seems that you have add a SEV-4 tho,

**Comment by hrishin** [comment]
![image](https://user-images.githubusercontent.com/28615674/43239901-ad02bb4a-90b1-11e8-9c6c-acf3f5f4584a.png)

Not only for first time but it alos happens during unideling case as well. 
As shown in the above graph Jenkins doesn't respond at for certain timeframe when its CPU workload reaches to given limits. Also its observed that rediness and liveness probs keep failing during the same timeframe.

In initial impression, possible reasons for such behavior could be 
- Set of Jenkins plugins that doing some CPU intensive tasks. e.g. Openshift Sync or Auth plugin
- Jenkins doing I/O bound operations but may require CPU due to underlying infra

Need more insights to identify root cause.

**Comment by piyush1594** [comment]
![jenkins](https://user-images.githubusercontent.com/19270240/43460272-caeb66c6-94ed-11e8-8a6d-a5871a69aeae.png)

**Comment by kishansagathiya** [comment]
The issue happened to us even though I was not a first time user. Plus in my case it's not just slow, It doesn't start at all.

**Comment by chmouel** [comment]
i only mentioned at first boot here cause it's a easy scenario to reproduce from scratch but yeah it's dead slow to start most of the time (sometime it's quick but that is quite rare these days), I have read that the Che people had IO issue on volume maybe thats the root cause?

**Comment by chmouel** [comment]
Any chance if we can have numbers of a couple of run it takes to first boot /unidle before closing this?
