### ISSUE TITLE
"Application is not available" on Microsoft Edge

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/openshift.io#40]
1. Use Edge.
2. Go to site
3. Get:

Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Works fine from Chrome on same desktop.

**Comment by pmuir** [comment]
Suggest we add a simple static page that links to http://lmgtfy.com/?q=how+to+switch+to+chrome+from+edge

**Comment by qodfathr** [comment]
As an alternative, may I recommend to you http://mnstr.me/2nqIypJ

**Comment by pmuir** [comment]
I *suspect* this was caused by caching as the homepage and app work fine for me on Edge 40.15063.0.0. I did hit some caching issues as well, and refreshing got me past them. I suspect Edge's implementation of service workers is different/broken somehow, as that is what normally causes our caching issues.

Can you retry after flushing your browser cache or in a new InPrivate window?

**Comment by qodfathr** [comment]
Verified as fixed.
