### ISSUE TITLE
Unable to see existing collaborators in a space

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#4010]
Log In as space owner (e.g. for OpenShift_io)
select settings (tab to the left of Analyze/Plan/Create
select Collaborators
only see 20 collaborators 
    randomly selected list sorted by first name

I have no way of knowing if a person is already added

**Comment by sbose78** [comment]
Just checked, the front-end makes an API call which looks like this https://api.openshift.io/api/spaces/67ec9059-b09d-4885-a8d1-bd25dedd8edc/collaborators?page[limit]=20

So, the default paginated limit of 20 collaborators is all we see.

**Comment by sbose78** [comment]
@rohitkrai03 , till we decide how we would wanna handle pagination in the front-end ( it would need UX involvement ) , could you bump up the default limit to 100 in the API call ?

CC: @sbryzak

**Comment by sbose78** [comment]
@lwrigh   @catrobson  The collaborators page by default lists 20 collaborators - without pagination support. For the sake of continuity of usage, I suggest we change the default to a higher number to 100 and show it all together. However, I have a concern that 71+ collaborators might be too long a list to look good.

Wondering if we should borrow something from the roles' design, and use it here?

What do you think ?

**Comment by catrobson** [comment]
Ideally we've been trying to do infinite scroll lists with progressive loading of more rows.  I'd want the collaborators list to work the same way so that we have a consistent list experience across OSIO.  I'm not sure what the initial load number is set to on other pages, but 20 for collaborators seems reasonable, and then load in sets of 20 as you scroll down the list.

**Comment by rohitkrai03** [comment]
@sbose78 @catrobson It seems like infinite scroll directive is being used in this component that is why the limit has been set to 20. The problem here is infinite scroll works on scroll event of the component or HTML element to be exact and since this element doesn't have a fixed height here scroll event never gets fired. 
- With a quick CSS fix i can make it working if i set the `max-height` for the component  and enable internal scroll for it just like `My Spaces` widget on profile page.
- For a better fix we should look into updating the infinite scroll directive which can take scroll events not just for the component but also overall parent component.

**Comment by catrobson** [comment]
@dlabrecq FYI

**Comment by rohitkrai03** [comment]
It would look something like this.

![collab-area](https://user-images.githubusercontent.com/6041994/42837325-6d34119a-8a1b-11e8-9fbb-de1e6f60c8ec.gif)

cc: @catrobson @sbose78

**Comment by rohitkrai03** [comment]
@catrobson @sbose78 It would look something like this.

![collaborators](https://user-images.githubusercontent.com/6041994/42837428-b42cb1e2-8a1b-11e8-9c37-eb47977ffb2e.gif)

**Comment by dlabrecq** [comment]
You need to fetch more than 20 items (people) so that the list height triggers the scrolling. (20 is the REST API default.) Without the ability to scroll, you cannot fetch more data.

**Comment by rohitkrai03** [comment]
20 is enough to trigger the scroll event but it doesn't trigger the event for the collaborators list component but for the whole container component which is why `fetchMore()` is never called.

**Comment by dlabrecq** [comment]
We shouldn't need to override the CSS max-height property -- we use infinite scroll in a few other areas. 

If fetching more than 20 items doesn't trigger the fetch event, perhaps the fetchThreshold and/or eachElementHeightInPx attributes are not set correctly for this particular almInfiniteScroll directive?

**Comment by rohitkrai03** [comment]
@dlabrecq The only two components that use infinite scroll in fabric8-ui are -
- https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/spaces/spaces.component.html

<img width="1680" alt="screen shot 2018-07-18 at 10 57 28 pm" src="https://user-images.githubusercontent.com/6041994/42897636-32ed2378-8ade-11e8-9952-8fbfb91af259.png">

- https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/overview/spaces/spaces.component.html

<img width="1680" alt="screen shot 2018-07-18 at 10 57 50 pm" src="https://user-images.githubusercontent.com/6041994/42897645-3c51705e-8ade-11e8-9cca-a99bb27c18c1.png">


And both of these components have fixed height and `overflow-y: scroll` to enable scroll inside the component. This is the reason they work. If we remove the internal scroll of these components infinite scroll directive won't work since it attaches the scroll event on particular components and not on document or any parent component.
So, this is what i am proposing for the solution. To have a fixed height and `overflow-y: scroll` set for collaborators component as well. With that fix infinite scroll works as intended.

**Comment by sbose78** [comment]
Thank you @rohitkrai03 @catrobson and @dlabrecq - the design discussion looks great.

**Comment by GeorgeActon** [comment]
@sbose78 @catrobson please tell me this list will be sorted by user name

**Comment by GeorgeActon** [comment]
@joshuawilson @nimishamukherjee why is this closed? I am in prod and I still can only see 20 random collaborators?

**Comment by GeorgeActon** [comment]
@rohitkrai03 Thanks.

**Comment by GeorgeActon** [comment]
This issue has resurfaced.
I was asked to remove some people as collaborators. I was unable to see them since we are back to a randomly selected list of 20. 
I was signed in as owner of Openshift_io.
Interesting that the home view shows a count of 20 collaborators as well:

![screen shot 2018-11-07 at 9 29 55 am](https://user-images.githubusercontent.com/19672343/48137363-e241a400-e26f-11e8-8641-db92312c829a.png)

**Comment by aptmac** [comment]
For the most part, this will be fixed when https://github.com/fabric8-ui/fabric8-ui/pull/3396 hits production. Note that the unsorted-ness of the collaborators is what's coming from the backend, so that will remain. However, you'll be able to see collaborating users in a pop-over element.

**Comment by GeorgeActon** [comment]
fixed by update of Prod by Joshua
