### ISSUE TITLE
Unable to add collaborators

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#4011]
Log In as owner of the space (e.g. Openshit_io)
Go to Collaborators
click on Add collaborators
Search for person
Select person
do this multiple times to add more than one person at a time in the same search box
the add button turns blue
Click the add button
    what does it mean when it does not react?
does it mean that person is already a collabrator?
      Which person is already a collaborator - no indicator 
Since I cannot see the list of existing collaborators I do not know who is the cuplrit
See related issue https://github.com/openshiftio/openshift.io/issues/4010

**Comment by sbose78** [comment]
@GeorgeActon , this happens when one of the choices you made was already a collaborator right?

**Comment by sbose78** [comment]
@rohitkrai03 , Could we populate the search results by leaving out existing collaborators ?

**Comment by joshuawilson** [comment]
I think the first is better, less annoying.

**Comment by sbose78** [comment]
> First one is just filter out already added collaborators from the search result.

I agree with @joshuawilson . Let's go ahead with the first one.

**Comment by rohitkrai03** [comment]
@sbose78 @joshuawilson I've raised a PR - https://github.com/fabric8-ui/fabric8-ui/pull/3179 according to the first approach. But I think there is some potential issue with both of the approaches - 
- Since, it is an infinite scroll not all the collaborators will be rendered most of the time.
- And we filter out the results based on the already added collaborators that are present and rendered in the list.
- So, there might be a case where someone searches a collaborator who is already added in the space but not rendered in the list because the list has been rendered only till 2nd page while his name is in 3rd page. This will cause the logic to break again and server would send a 500 response.
- I think we should look at a solution from backend where backend won't throw 500 when trying to add already added collaborator but silently ignore it or log it somewhere.

What do you guys think?

**Comment by joshuawilson** [comment]
I think we need @openshiftio/uxd-team involved. 

I like the last point, that way we could tell the user they are already added.

**Comment by sbose78** [comment]
@rohitkrai03 , That seems like a valid problem. We are discussing if changing the API would be the right thing to do. https://github.com/fabric8-services/fabric8-auth/issues/556 .

**Comment by catrobson** [comment]
@sbose78 @joshuawilson I would actually have recommended that we show all the users, all the time in the dropdown and then handle it correctly on the backend.  It really doesn't do 'harm' for the user to add a user multiple times from a UI perspective, and when someone doesn't show up in the list it often turns into wasted time/discussion on the user's end (they go to the user and say, "are you sure you're signed up for OpenShift.io" "yes! I am" admin goes back, searches through list, and then finally sees that yes, somewhere down on page 3, that user is listed).  That's a good 10 - 15 minutes of wasted time over us just allowing them to 'add the user again' which gives them a message that says something like "5 users added, 1 user already existed in this space" to confirm their action.

**Comment by sbose78** [comment]
@joshuawilson @catrobson Thanks, yes that sounds reasonable to me. Let me modify the API.
