### ISSUE TITLE
Space Dashboard Work Item Widget not displaying bar chart

### ISSUE THREAD

**Issue by aptmac** [openshiftio/openshift.io#4057]
The work item widget at https://openshift.io/openshiftio/openshift_io is not displaying the bar chart. The reason it is not rendering the chart is because the counters are not being incremented [[0]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts#L62). This is because for some reason the `system.state` in the `workItem.attributes` is a different case than the expected value, e.g., `Open` vs. `open` [[1]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts#L34). I'm wondering if this has something to do specifically with the way `agile scrum spaces` work, because this behaviour isn't present in `scenario driven development` spaces as far as I can tell.

This is what it looks like currently:
![observed](https://user-images.githubusercontent.com/10425301/43101436-66e2729e-8e96-11e8-89d5-24af8a054998.png)

Here's what it should look like:
![expected](https://user-images.githubusercontent.com/10425301/43101582-b774ed40-8e96-11e8-8313-d8b3cdcd01e2.png)

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts#L62
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts#L34

**Comment by andrewazores** [comment]
Yea, the `open` vs `Open` does seem to be the problem here. The responses coming back for `https://openshift.io/openshiftio/openshift_io` all look like `New`, `Closed`, `Resolved`, `In Progress`. The responses for `https://openshift.io/openshiftio/openshiftio` look like `new`, `closed`, `resolved`, `in progress`.

Whatever database these things come from should have these labels made the same, or else `WorkItemService` from the `fabric8-planner` module should make these things consistent for consumers.

**Comment by andrewazores** [comment]
A minimal hacky workaround on the `fabric8-ui` platform client side is as short as this:

```
diff --git a/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts b/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts
index 06baf7ba..80e3275b 100644
--- a/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts
+++ b/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts
@@ -57,8 +57,9 @@ export class WorkItemWidgetComponent implements OnInit {
     this._myWorkItems = this.workItemService.getWorkItems(100000, [])
       .map(val => val.workItems)
       .do(workItems => workItems.forEach(workItem => {
-          let state = workItem.attributes['system.state'];
+          let state: string = workItem.attributes['system.state'];
           if (state !== undefined) {
+            state = state.toLowerCase();
             if (state === this.STATE_OPEN) {
               this.myWorkItemsOpen++;
             } else if (state === this.STATE_IN_PROGRESS) {
```

but we should try to avoid such a solution.

**Comment by nimishamukherjee** [comment]
@sanbornsen please have a look

**Comment by GeorgeActon** [comment]
@nimishamukherjee Since you did not replace the severity, I assumed that the removal was accidental and re-added it.

If in future we are planning on allowing customer to customize states, I think we should be populating this overview with the states that exist in the database not a pre-determined list.

**Comment by divyanshiGupta** [comment]
@kwk @baijum can you please look at this issue? Can we fix this in backend and use same case for both the templates as it is causing a lot of issues?

**Comment by divyanshiGupta** [comment]
@andrewazores it cannot be fixed in backend as @kwk mentioned above that it is not easy and we should not fix this in `workItemService` as `updateWorkItems()` function uses `getWorkItems()` that returns an object with an array of workItems and we cannot change the returned value as this particular function is used in a lot of other places, and hence the returned value should be generic, so that it can be consumed in different ways in different places. Solution  :-

- We can use `state.toLowerCase()` or 
- We can have a new method in `WorkItemService` that can be used by `updateWorkItems()` to get the workItems with the states for both the templates in the same case.

I think its better to use `state.toLowerCase()` in `updateWorkitems()`  instead of creating a new method that returns that. @sanbornsen what do you think?

**Comment by andrewazores** [comment]
Okay, in light of that explanation then doing a simple case-insensitive comparison does seem to make sense for this widget. `toLowerCase()` isn't actually the right way to go though - see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare for a better way.

**Comment by divyanshiGupta** [comment]
Thanks, will have a look at it.
