### ISSUE TITLE
Workitem hierarchy not rendered properly

### ISSUE THREAD

**Issue by DhritiShikhar** [openshiftio/openshift.io#4075]
![screenshot_2018-07-11_16-23-58](https://user-images.githubusercontent.com/6303309/42567385-37b821d0-8527-11e8-8873-cedeae3df30a.png)

**Comment by sunilmalagi** [comment]
Here is the recommendations after discussing with Nimisha, Veethika and Sukhvir,

1. Optimising the indentation will help accommodating more level of WI's.
2. Increase the title column width after 6 levels
3. As the column width increases, auto-scroll the title column so that it focuses on the new work item being linked. (Such level of depth can be achieved only through the work item linking and not direct)

**Comment by sanbornsen** [comment]
> Optimising the indentation will help accommodating more level of WI's.

We can do this, but that has to be done from the upstream library. @sahil143 we discussed about an input property, did we ever work on that?

But wait, what are we talking about? **n level of work items**, is this ever going to happen. With option 1 we'll still have the problem, option 2 and option 3 requires a lot of effort and it's totally not worth taking to support crazy number of levels.

**Comment by sahil143** [comment]
>  @sahil143 we discussed about an input property, did we ever work on that?

@sanbornsen Yes, this was fixed in ngx-datatable but not in planner. I raised a Pr for the same.

**Comment by sahil143** [comment]
closing this as the PR merged to reduce the indentation in tree-view.
