### ISSUE TITLE
Known dependency count is 0 for POMs not in the vertx, springboot, wildfly ecosystem even if packages are in graph

### ISSUE THREAD

**Issue by rootAvish** [openshiftio/openshift.io#4179]
##### Issue Overview

When analysis is triggered for some pom.xml not in the vertx, springboot, wildfly ecosystems when analysis is triggered through the IDE extensions the known dependency count is 0 even if packages are present in graph and elsewhere. Also recommendations from Kronos are returned.

##### Expected Behaviour

Known dependency count should be > 0 when dependencies are known, recommendations in case where no known dependencies are present should be 0 instead of coming from Kronos.

##### Current Behaviour

Described in overview.

##### Steps To Reproduce

1. Trigger stack analysis through IDE extension for the repo: https://github.com/google/guava

/cc @samuzzal-choudhury There seem to be two bugs here.
/cc @sara-02 The second bug might be related to the backbone changes you did.

**Comment by sara-02** [comment]
@rootAvish it can be, I it worked as expected last two sprints. Some code changes this sprint triggered the bug.
Also, this can be replicated with other maven repos like twitter4j and incubator-dubbo

**Comment by samuzzal-choudhury** [comment]
@miteshvp @rootAvish @invincibleJai  A few observations after I tried out stack report generation for guava project:

1. Root level pom.xml for guava does not have any dependencies (_mercator is sane in parsing only 'dependencies' as confirmed by @msrb_) listed and contains the pointers to the modules of the application. So, the generated report for that pom.xml without any dependencies make sense. **But, insights on that without any dependencies do not**.
2. Generation of stack report for a module's pom.xml, generates the effective pom.xml but results in the following error 
![image](https://user-images.githubusercontent.com/17740190/44208461-06647c00-a17e-11e8-9e23-1a9ab31d32b3.png)
3. Using the same effective pom.xml to run stack analysis on PostMan generates a proper output with recommendation and dependency data.

@invincibleJai will you please check why the extension is not able to set the filePath parameter for the internal modules of guava (https://github.com/google/guava). IMO, that is the reason for not displaying stack reports for all the manifest files in that project when one tries to generate it at a workspace level.

@rootAvish is there any logic through which the kronos maven recommends some default companion components even when there are no dependencies sent to it?

**Comment by miteshvp** [comment]
@samuzzal-choudhury for point 1 above, I generated stack report for a single POM. It should not give us analyzed-deps and unknown-deps as empty. So backbone is receiving a wrong set of deps somewhere which makes sense because all the analyzed-deps and unknown-deps is empty for stack-aggregator and dummy recommendation as if no EPVs are passed from kronos. Something to debug between mercator and backbone for sure.

**Comment by samuzzal-choudhury** [comment]
@miteshvp my point was that, if you generate report for the top level pom.xml, you are not going to get dependencies listed in the report as that does not include dependencies, rather includes the list of modules in the project. @msrb confirmed and he can reconfirm that we should not look for dependencies in 'DependencyManagement' tag.

I get failures in generating stack report for the module specific pom.xml which I requested @invincibleJai to look into.

**Comment by sara-02** [comment]
> @rootAvish @sara-02 is there any logic through which the kronos maven recommends some default companion components even when there are no dependencies sent to it?

@samuzzal-choudhury yes, there is. If I understand you correctly then the server backbone is receiving an empty list of dependencies, right?  The logic which determines if Kronos or hpf is to be used defaults to Kronos if the original dependency list is empty. And within Kronos, since the input package list is empty, it returns a default set of companion recommendations.

**Comment by samuzzal-choudhury** [comment]
> And within Kronos, since the input package list is empty, it returns a default set of companion recommendations.

@sara-02 is this by design?

**Comment by sara-02** [comment]
Kind of, not deliberate design, actually we check if 50% or more of the dependencies are from vertex/spring-boot/Wlidfly ecosystem or not, and return a true or false accordingly, but if the length of the set is zero then false is returned, since None might break the flow, and the former might lead to division by zero. So to not break the flow I default to Kronos.

**Comment by samuzzal-choudhury** [comment]
@sara-02 don't you think that this could be better handled at the server-backbone level with a check? Can you please take an initiative to fix this and share the timeline for delivering that fix?

**Comment by sara-02** [comment]
Fixed from the backend in https://github.com/fabric8-analytics/f8a-server-backbone/pull/98
Working as expected on staging and prod via Postman.
@samuzzal-choudhury @rootAvish Can you guys verify if it is working as expected on VSCode, then we can close this issue.

**Comment by sara-02** [comment]
Seems to be working as expected in VSCode as well.
![screenshot from 2018-08-23 14-26-12](https://user-images.githubusercontent.com/7047079/44515622-9fe0e000-a6e0-11e8-90d8-0bbad460a698.png)

**Comment by rootAvish** [comment]
Works for me with Guava, thanks for the change @sara-02 🙂
