### ISSUE TITLE
Provide an easy starting point

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4189]
As part of the design thinking session around _Goal A - Improve Onboarding for novice_, **provide an easy starting point** was prioritized as an issue to address.  The following suggestions should help provide context on the design direction:

- Provide clear instruction before the user starts the application
- Provide an obvious flow on how to start a journey

**Comment by sdash-redhat** [comment]
This story is addressed in the following first draft wireframe/concept  
https://redhat.invisionapp.com/share/F9O152GZN8D
Related to the stories -- #4185, #4186, #4187 and #4189

**Comment by sbose78** [comment]
Hi @serenamarie125 ,

Wondering if the following could be addressed as part of the current work of providing an easy starting point.

CC: @bartoszmajsak 
- Should we create the space in the background and expose only 'Create app' to the user because a lot of users have asked "why do I need to create a space?" as an additional step. Example, users evaluating middleware might find the 'Create space' step a bit unnecessary. In very rare cases, people might just wanna create a space and do something else apart from creating an application.

- Should we also address if the 'dependencies' section should remain in the current form. The downsides of the section is : (1) might look like a lot to decide in an initial workflow (2) user might inadvertently choose an combo of dependencies which could lead to a build failure.

@sdash-redhat , I've added comments.

**Comment by muruGanesan** [comment]
@serenamarie125, We covered this issue in #4191 please review the same let me know if we can close this issue.
Here is the Invision link:
https://redhat.invisionapp.com/d/main#/projects/prototypes/15484761

NOTE: 
1) The above UX recommendation is under design review and it is NOT for implementation discussion.
2) Once it is ready for implementation, Serena will connect with the engineering team for further actions.

**Comment by serenamarie125** [comment]
Closing since this is a duplicate
