### ISSUE TITLE
Test VSCode extension for real-world Java and NodeJS projects

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#4224]
### Planner Issue
https://openshift.io/openshiftio/Openshift_io/plan/detail/458

### Tasks
- [x] Fix all the priority P1 and P2 issues reported in [the bug tracker spreadsheet](https://docs.google.com/spreadsheets/d/1nu9E-S2MdExIasHKD38OPtdYYidI22JM3F6cRpHvnK8/edit#gid=2071749690)

**Comment by miteshvp** [comment]
Looks like all the P1 and P2 along with some other issues are handled. 
1. https://github.com/openshiftio/openshift.io/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ateam%2Fanalytics+label%3Atype%2Fbug++is%3Aclosed+created%3A%3E2018-08-23+author%3ArootAvish+
2. https://github.com/openshiftio/openshift.io/issues?q=is%3Aissue+label%3Ateam%2Fanalytics+label%3Atype%2Fbug+is%3Aclosed+created%3A%3E2018-08-23+author%3Asamuzzal-choudhury

Taking the liberty of closing this issue. Please re-open if otherwise
