### ISSUE TITLE
Indentation of child work items in tree view is not working correctly

### ISSUE THREAD

**Issue by GeorgeActon** [openshiftio/openshift.io#4241]
##### 

Indentation of stories under epics does not line up correctly . If you do not notice then you can easily miss noticing a number of stories belong to the same parent in the tree view..

##### Steps To Reproduce

1. go to default work item view
2. https://openshift.io/openshiftio/Openshift_io/plan?q=(typegroup.name:Work%20Items%20$AND%20area:135ea9f5-b43a-4b44-9b11-d9a985d8fdc4%20$AND%20state:Closed)&showTree=true&showCompleted=true

![screen shot 2018-08-24 at 10 47 16 am](https://user-images.githubusercontent.com/19672343/44592135-b2652300-a78d-11e8-85e0-89286beb1eca.png)

**Comment by aptmac** [comment]
In the image you posted, it looks like the stories that aren't indenting (e.g., id#95, id#281) are because of the misalignment of the row due to work item title overflow. Note the displacement of the vertical dividers that are used to separate the categories (id/type/title/etc.). This would be similar to https://github.com/openshiftio/openshift.io/issues/4152, which has a fix in f8-planner but not in production at the moment.

**Comment by aptmac** [comment]
fixed in prod after planner update
