### ISSUE TITLE
Space dashboard lists work items from deleted spaces (beta feature)

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4283]
##### Issue Overview

"My Work Items" section of space dashboard lists work items not related to given space

##### Expected Behaviour

Space dashboard lists work items from given space assigned to me

##### Current Behaviour

Space dashboard lists all (?) work items assigned to me, multiple items point to the same URL, none of the links work

![osio_deleted_space_wi2](https://user-images.githubusercontent.com/445100/44983767-ae4db800-af7a-11e8-858a-998fa759ebd0.png)

##### Steps To Reproduce

1. create spaceA
2. create item1 in spaceA, assign it to yourself
3. navigate to "My spaces" and remove spaceA
4. create spaceB
5. open space dasboard (make sure that you have opted-in for beta features) 

##### Additional Information

The root cause seems to be the fact that the work items are not deleted together with space

**Comment by ppitonak** [comment]
@rgarg1 @Raunak1203 this seems to be a good test case for your new integration test suite

**Comment by aptmac** [comment]
This may be an issue with the f8-ui spaces service [[0]](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/spaces.service.ts#L36) rather than an issue with the planner. The spaces service is responsible for maintaining the list of `recent` spaces, however it has no mechanism for removing deleted spaces from the list. As a result, if you had deleted a space it was likely not removed from the list, and would have been used to populate the work-items widget. The spaces service deletion bug has been around for a while [[1]](https://github.com/openshiftio/openshift.io/issues/2196).

[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/shared/spaces.service.ts#L36
[1] https://github.com/openshiftio/openshift.io/issues/2196

**Comment by aptmac** [comment]
Related: https://github.com/openshiftio/openshift.io/issues/2646

**Comment by jiekang** [comment]
This is related to a regression commented on in https://github.com/fabric8-ui/fabric8-ui/pull/3282#issuecomment-416226814

The work items widget in the space dashboard should list work items for the space that the dashboard represents, not other spaces.

It looks like there hasn't been any response though. @sanbornsen Have you had any time to look at this?

**Comment by ppitonak** [comment]
@sanbornsen any update?

**Comment by ppitonak** [comment]
Closing in favor of #4381 and #4382
