### ISSUE TITLE
Volume mount/unmount failure stops Che workspace from loading

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#4285]
##### Issue Overview
Unable to start a Che workspace from the dashboard, on cluster `starter-us-east-2`
```
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedMount', 'Unable to mount volumes for pod "workspace038mn3pfvgvbvpwn.dockerimage-c67f8d65b-7jkl6_shbose-che(f324b8c9-af2f-11e8-867f-02d7377a4b17)": timeout expired waiting for volumes to attach or mount for pod "shbose-che"/"workspace038mn3pfvgvbvpwn.dockerimage-c67f8d65b-7jkl6". list of unmounted volumes=[claim-che-workspace]. list of unattached volumes=[claim-che-workspace default-token-b7hsw]', 'workspace038mn3pfvgvbvpwn.dockerimage-c67f8d65b-7jkl6'"
```

##### Steps To Reproduce

1. Visit che.openshift.io 
2. Add a new workspace using the Golang stack
3. Notice that the workspace doesn't start.

##### Additional Information
I've tried removing the volume claim, but looks like that is stuck as well.

```
persistentvolumeclaim "claim-che-workspace" is being deleted
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedScheduling', 'persistentvolumeclaim "claim-che-workspace" is being deleted', 'workspace038mn3pfvgvbvpwn.dockerimage-698d7d8f85-xtg6m'"
```

**Comment by ibuziuk** [comment]
@sbose78 original issue is related to https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2169 when workspace is failing to mount volume due to large amount of files in the PV. The only way to workaround it is remove `claim-che-workspace` either manually or via `Reset Environment`. 

`I've tried removing the volume claim, but looks like that is stuck as well.`

Could you please try to remove `claim-che-workspace` pvc completely from the *-che namespace and retry the workspace creation flow?

**Comment by waveywaves** [comment]
Me too 
![screenshot from 2018-09-07 12-46-44](https://user-images.githubusercontent.com/11972233/45204305-65f50980-b29c-11e8-8ca1-2317dcaada0b.png)

**Comment by ibuziuk** [comment]
I believe we should close this issue since it is a duplicate of  https://github.com/openshiftio/openshift.io/issues/4079
@waveywaves could you try removing `claim-che-workspace`  PVC  manually from *-che namespace ( (reset environment from user profile page on openshift.io would also re-create the pvc)) and try to create workspace from scratch ?

**Comment by sbose78** [comment]
Illya, unfortunately, "reset environment" isn't working for me :(

**Comment by sbose78** [comment]
Closing, because it's being tracked in #4079
