### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by ppitonak** [openshiftio/openshift.io#4348]
##### Issue Overview

Logout doesn't work

##### Expected Behaviour

When user logs out, he will be redirected to public page, login is necessary to access the platform again

![osio_logout2](https://user-images.githubusercontent.com/445100/45953997-0e7cca80-c00c-11e8-8b3a-2cf5d2f52775.png)

##### Current Behaviour

User sees some stub page and clicking on login brings him back without providing name and password

![osio_logout3](https://user-images.githubusercontent.com/445100/45954008-150b4200-c00c-11e8-8a4c-eaf26e87cc32.png)

##### Steps To Reproduce

1. log in
2. log out
3. log in again

##### Additional Information

1. **Updating the tenant or resetting the account fixes the issue**
2. Happens on both prod-preview and prod. 
3. Happens only on some accounts (e.g. Jenkins works ok, accounts of @ppitonak and @ljelinkova are broken, account of @ldimaggi works)
4. Not browser specific (we tried latest Firefox and latest Chrome on Linux)
5. Not a cache issue - we tried incognito mode

**Comment by aptmac** [comment]
I've been able to see this, but the problem seems to be with the home `work-item-widget.component`, so it will only occur if trying to logout from the home page. From skimming through the code for the component, it appears that on a logout the component attempts to load work items for the "logout" space .. which is undefined [0]. This was introduced in f8ui 3282 [1] when the component was updated to make use of the new filter service.

Error as observed in the console:
```
ERROR TypeError: Cannot read property 'trim' of undefined
    at FilterService.webpackJsonpac__name_../node_modules/fabric8-planner/app/services/filter.service.js.FilterService.queryBuilder (filter.service.ts:266)
    at MapSubscriber.project (work-item-widget.component.ts:75)
```
Gif of the error:
![logout-error](https://user-images.githubusercontent.com/10425301/45960389-22afd000-bfea-11e8-8f44-5073b0f7f8ca.gif)


[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/work-item-widget/work-item-widget.component.ts#L75
[1] https://github.com/fabric8-ui/fabric8-ui/pull/3282

**Comment by alexeykazakov** [comment]
@aptmac is this something you can take care of?
cc @rohitkrai03

**Comment by hrishin** [comment]
@rohitkrai03 Is's closed accidentally?

**Comment by rohitkrai03** [comment]
@hrishin Sorry.

**Comment by rohitkrai03** [comment]
@alexeykazakov PR raised - https://github.com/fabric8-ui/fabric8-ui/pull/3338/files
