### ISSUE TITLE
Builds in the waiting queue won't start

### ISSUE THREAD

**Issue by kishansagathiya** [openshiftio/openshift.io#4406]
1. Create any projects in OSIO. 
2. Make a bunch of commits.
3. Since we can perform only one build at least recent commit(for which the build has not been performed before) will trigger a build, and rest will go in some waiting queue.
4. Let the build reach `Approve` stage.
5. Do not approve. Wait forever(I waited for a day, I don't know what is the minima here).
6. Approve.
7. Current build finishes and next build starts (but only for openshift)
8. Next build forever keeps on `Setting up your build server.
This may take several minutes to complete.`
9. The build is not triggered (Go to jenkins you won't find build that openshift is trying to trigger)

![screenshot from 2018-10-11 10-40-41](https://user-images.githubusercontent.com/10185999/46782339-7ee15680-cd43-11e8-9db7-33175c7d2811.png)
This has been going on since about an hour.

**Comment by kishansagathiya** [comment]
At this point, I can't cancel build. Only option I have is reset environment.

**Comment by joshuawilson** [comment]
cc @pradeepto @bartoszmajsak

**Comment by bartoszmajsak** [comment]
![giphy](https://user-images.githubusercontent.com/719616/46834226-1d54d280-cdab-11e8-97e8-548b2ee7bea0.gif)

**Comment by chmouel** [comment]
This seems to be our issue with the storage, it was waiting too long to release the PVC, this could be  the AWS  EBS storage timing out or gluster who was doign some operations timing out,

I am going to close this issue since we don't have any `oc get ev` and gluster new version should be better with this, we can reopen this if this shows up again,
