### ISSUE TITLE
Package name in the wizard is ignored in the generated code

### ISSUE THREAD

**Issue by siamaksade** [openshiftio/openshift.io#449]
Specifying the top level package name sets the group name in `pom.xml` but the generated code is still based on the default `io.openshift.booster`.

<img width="895" alt="screen shot 2017-08-01 at 08 24 29" src="https://user-images.githubusercontent.com/1174934/28825132-026fa49c-7693-11e7-9c91-9daf1ed0871e.png">

The generated code is structure is:
```
.
`-- src
    |-- licenses
    |   `-- content
    |-- main
    |   |-- fabric8
    |   |-- java
    |   |   `-- io
    |   |       `-- openshift
    |   |           `-- booster
    |   `-- resources
    |       `-- webroot
    `-- test
        `-- java
            `-- io
                `-- openshift
                    `-- booster
```

**Comment by joshuawilson** [comment]
Thanks for pointing that out.

@gastaldi can you please confirm what is supposed to happen.

**Comment by gastaldi** [comment]
We have removed the package name input from our wizard. You need to update to our latest launchpad-addon version.

**Comment by joshuawilson** [comment]
Thanks @gastaldi

**Comment by siamaksade** [comment]
The expected outcome is to have the sample Java classes generated in the same package as specified in the wizard like this:

```
.
`-- src
    |-- licenses
    |   `-- content
    |-- main
    |   |-- fabric8
    |   |-- java
    |   |   `-- com
    |   |       `-- osio
    |   |           `-- example
    |   |               `-- vertexicator
    |   `-- resources
    |       `-- webroot
    `-- test
        `-- java
            `-- com
                `-- osio
                    `-- example
                        `-- vertexicator
```

How can I update to the latest launchpad-addon?

**Comment by gastaldi** [comment]
@siamaksade You need to update the pom.xml in the fabric8-forge-addon to launchpad-addon 9.

As I beforementioned, this input was removed and the package name is no longer changed. 

We have https://github.com/openshiftio/appdev-planning/issues/34 to track this, but it may be closed since we haven't seen any real demand in this feature

**Comment by siamaksade** [comment]
@gastaldi Not sure I understand. I logged in to openshift.io, created a space and created new quickstart project and ran into the issue above. What do I need to update?

When using start.spring.io, user can specify a top level package name and then it's used as the `groupId` in `pom.xml` and also the java package name for the generated sample classes in the project.

**Comment by gastaldi** [comment]
That requires changes in the backend deployment descriptor.

This input will disappear and you don't need to specify the package name
anymore. The package name is no longer an option when creating a booster.

Em 1 de ago de 2017 11:55, "Siamak Sadeghianfar" <notifications@github.com>
escreveu:

@gastaldi <https://github.com/gastaldi> Not sure I understand. I logged in
to openshift.io, created a space and created new quickstart project and ran
into the issue above. What do I need to update?

When using start.spring.io, user can specify a top level package name and
then it's used as the groupId in pom.xml and also the java package name for
the generated sample classes in the project.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshiftio/openshift.io/issues/449#issuecomment-319395348>,
or mute the thread

**Comment by jstrachan** [comment]
FWIW we now use the latest launchpad-addon which does not have a package name input any more. If folks do wanna be able to specify a package name (which TBH sounds reasonable to me ;) - then openshiftio/appdev-planning#34 is the issue to track & vote up
