### ISSUE TITLE
Iterate on the Che Marketplace Designs

### ISSUE THREAD

**Issue by serenamarie125** [openshiftio/openshift.io#4560]
Given the initial designs provided in [this design](https://redhat.invisionapp.com/share/WQP3OKNK7HZ#/331199240_Che-MarketPlace-0-1-pdf_1), create a new Invision file focusing on pp. 3-9 addressing the comments which were provided from the initial review.

**Comment by sdash-redhat** [comment]
This story is next step from #4411

**Comment by sdash-redhat** [comment]
Based on the feedback on the [previous draft of mockup](https://redhat.invisionapp.com/share/WQP3OKNK7HZ) and details scope , have updated the mockups (not final VD) here. https://redhat.invisionapp.com/share/T7P78MK3V8E#/332254181_Title
@serenamarie125 @slemeur @catrobson @SriKrishnaPaparaju  
Please review and add your feedback in comments.

**Comment by slemeur** [comment]
At first (and at the stage we are) the submission of a plugin will be handled by a github PR on the plugin-registry.

**Comment by sdash-redhat** [comment]
Thanks, @serenamarie125, and @slemeur.

**Comment by sdash-redhat** [comment]
Here is an updated version 0.3
https://redhat.invisionapp.com/share/9DPAAHAYKZA#/333225269_Title
Apart from implementing the feedback, I also added 2 screens showing an option that the catalog appearing inside the Che. 

Please review @serenamarie125 @slemeur @catrobson

**Comment by slemeur** [comment]
Thanks @sdash-redhat

**Comment by sdash-redhat** [comment]
Based on the feedback and the discussion with the dev team, here are the updates 
**https://redhat.invisionapp.com/share/YJPC9T776ZW**

Please review @serenamarie125 @catrobson @slemeur   

Highlights of the change: 
1. No authentication happens in the marketplace site ...so no user details on the market place nav bar etc. 
2. Need to Add a call to action for preview instead of Install. 
3. the flow for preview till install/enablement of the plugin to user's workspaces. - 3 options are ideated   

- The user once in preview inside Che can have another action button that would say something like "enable/install this plugin " which once clicked can take the user to his account in che.openshift.io to enable that 
- The user can preview in Che and if he is happy he can come back to plugin page to click another call to action from that page that would say something like "enable/install this plugin " which once clicked can take the user to his account in che.openshift.io to enable that.
-  In the plugin page there would be a message on how to enable it in the workspace..

**Comment by sdash-redhat** [comment]
Based on the feedback from Brad, Serena and the team, updated the mockups (0.4.1). 
https://redhat.invisionapp.com/share/YJPC9T776ZW#/334584779_Title

The changes include: 
1. tags are removed from the card. 
2. left hand nav bar is removed as there is only one catalog. 

Please review @serenamarie125 @slemeur @catrobson @sivaavkd

**Comment by sdash-redhat** [comment]
Based on yesterday's standup review and other feedback, have updated the mockups (0.4.2) 
**https://redhat.invisionapp.com/share/GKPFLJIP583**
Highlights of the change: 
1. Removed 'View Details' button from the card 
2. Removed Kebab menu from the card
3. In details page, added the hint to provide the link for info on how to enable the plugin , this replaced the earlier link about the same. 
4. The option 3 of enablement of plugin flow is kept other 2 options are removed. 

HAve asked VD to provide the specs. 
@serenamarie125 @slemeur @sivaavkd  @sunilmalagi

**Comment by sdash-redhat** [comment]
Agree. looking at the current amount of content if we take out screenshots I belive we can put that in the hint itself. 

![1 1 5](https://user-images.githubusercontent.com/27761023/49486247-b06a3000-f863-11e8-8aec-c9568c47725e.png)



Have a updated the flow. @serenamarie125  @slemeur  @sivaavkd  please review. . 
**https://redhat.invisionapp.com/share/J8PGG7D7TFP**

**Comment by sunilmalagi** [comment]
Here is the invision link with Visuals and Specification

Option 1: (Hint without steps)
https://redhat.invisionapp.com/share/GKPFLJIP583#/335161034_1-1-1_Visuals

Option 2: (Hint with steps)
https://redhat.invisionapp.com/share/J8PGG7D7TFP#/335166344_0-4-3_Visuals

**Comment by sdash-redhat** [comment]
Based on the review discussion in standup on 10th, the option 2 was selected. 
The only change was to rename the title of the page as "Browse Plugins" - that was updated in the same Invision link **https://redhat.invisionapp.com/share/J8PGG7D7TFP** 
High fidelity of VD was provided already (https://redhat.invisionapp.com/share/J8PGG7D7TFP#/335166344_0-4-3_Visuals). 

@serenamarie125 @slemeur @sivaavkd

**Comment by sunilmalagi** [comment]
@serenamarie125 @sdash-redhat Updated the visuals with new page title 'Browse Plugins'

**Comment by sdash-redhat** [comment]
Marking as completed. 
This story can be considered to be closed.

**Comment by serenamarie125** [comment]
Closing out the story since this is completed.

**Comment by slemeur** [comment]
Confirming that the mockups are good for me.
