### ISSUE TITLE
Stack-analyses GET call returns null for some Projects

### ISSUE THREAD

**Issue by invincibleJai** [openshiftio/openshift.io#4642]
Issue Overview : 

Tried stack analyses on https://github.com/fabric8io/kubernetes-client, POST was success with stackID: 4fbfcfab8a1a403e9b7124b8dfba2977.

On GET stack-analyses getting null in response as well as in

```
{
    "finished_at": null,
    "version": null,
    "started_at": null,
    "release": null,
    "request_id": "4fbfcfab8a1a403e9b7124b8dfba2977",
    "result": []
}
```

Expected Behaviour: 

It should show details stack analyses for all the dependencies.

**Comment by samuzzal-choudhury** [comment]
Root cause:
1. [Mercator could not find the value of 'type'](https://github.com/fabric8-analytics/mercator-go/blob/master/handlers/java_handler/src/main/java/mercator/MavenUtils.java#L231) in [the effective POM](https://gist.githubusercontent.com/samuzzal-choudhury/053b34771da9d542abac8fd4e7f53402/raw/c2f5945803bc3b35b7f93a33bf99fe375406c48e/pom.xml) and forms a structure `groupid:artifactid:type:classifier version`. In the case of the failure, that became `io.fabric8:openshift-client::bundle 4.0-SNAPSHOT` as `type` was missing in the POM.
2. Bayesian Core API Server forms the resolved dependency name as `"io.fabric8:openshift-client::bundle` and calls the backbone /stack_aggregator service.
3. Backbone server forms the EPV data for that dependency with a delimiter '::' (Bad Choice :-( ) which results in `maven::io.fabric8:kubernetes-client::bundle::4.0-SNAPSHOT`
4. That EPV data resulted in a ValueError in the [stack_aggregator code logic](https://github.com/fabric8-analytics/f8a-server-backbone/blob/master/src/stack_aggregator.py#L462)  as the code was expecting 3 values from the EPV split whereas it got 4.

**Comment by miteshvp** [comment]
Looks like `type=bundle` would solve the case. Guess, fix should be done at mercator level. WDYT @samuzzal-choudhury ?

**Comment by msrb** [comment]
mercator is actually right here: `io.fabric8:openshift-client::bundle` is a valid package name. It's equal to `io.fabric8:openshift-client:jar:bundle` (type `jar` is default).

**Comment by msrb** [comment]
We have [`MavenCoordinates`](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/utils.py#L320) class in worker that can help with this.

**Comment by msrb** [comment]
Yeah, I think backbone should not assume that there are no extra `::` pairs in the package name. If we want to keep using `::` as a delimiter in backbone, then we should rewrite the split logic and only consider the left most part to be ecosystem, right-most part to be version, and keep everything in between untouched.

**Comment by miteshvp** [comment]
@msrb @samuzzal-choudhury - the actual ingestion creates package-name as `io.fabric8:openshift-client:bundle` . Still this will fail even with whatever Michal proposed because it will translate package-name to `io.fabric8:openshift-client::bundle` Note extra `:`

**Comment by msrb** [comment]
> the actual ingestion creates package-name as io.fabric8:openshift-client:bundle

I'd expect ingestion pipeline to fail as there is no such package in Maven Central.

**Comment by msrb** [comment]
There are data for the package in S3 (with the incorrect name), but all of them are from June 2017.

**Comment by ravsa** [comment]
I am facing the same error for other ecosystems(pypi, npm). even after replacing delimeter `::` to `|`. I was geting `null` and I noticed that when we send version as `float` or other types than string it raises an exception 
```python
TypeError: Can't convert 'float' object to str implicitly"
``` 
it occurs here https://github.com/fabric8-analytics/f8a-server-backbone/blob/master/src/stack_aggregator.py#L372-L377 and that solved the problem for me.

**Comment by miteshvp** [comment]
This is interesting. @ravsa - can you please share those versions being sent as float? That is something we may have to handle at client side then. cc @invincibleJai @samuzzal-choudhury

**Comment by stevengutz** [comment]
I don't understand how this qualifies as a SEV2 bug.  I would argue it's a SEV3

**Comment by invincibleJai** [comment]
reopening it as it's still being observed.

**Comment by invincibleJai** [comment]
Closing it as has been fixed.
