### ISSUE TITLE
We need a Maven cache for running within Che

### ISSUE THREAD

**Issue by burrsutter** [openshiftio/openshift.io#496]
It takes too long to "download the internet" with each Che Workspace start/creation.

**Comment by burrsutter** [comment]
In theory, it might be possible to share the maven artifacts from the Jenkins content-repository

**Comment by jstrachan** [comment]
is this only an issue for the first time you open a workspace? I thought they used a PV for the local mvn repo

is the local mvn repo PV shared between workspaces? i.e. does it only affect the first workspace a new user creates?

**Comment by benoitf** [comment]
For speeding up codenvy factories, for example the .m2 cache is stored inside the docker image.

For example we could store all maven vert.x dependencies in the vert.x docker image.

**Comment by cctrieloff** [comment]
Think this should be a central cache so we don't duplicate jars etc for each tenant. I.e. Have SD team setup it up and tenants just use the central cache.

**Comment by bmicklea** [comment]
Who can work on this - it will be critical for JavaOne workshops and demos. Upgrading to P1

**Comment by bmicklea** [comment]
@gorkem who owns the Quick Start Che dockerfiles and could add the .m2 cache appropriate for each QS?

**Comment by benoitf** [comment]
I will add the cache in docker images like we do on che factories

**Comment by benoitf** [comment]
@gorkem it's preloading docker images with maven dependencies

**Comment by l0rd** [comment]
For vert.x and spring boot stacks maven dependencies are already pre-installed (see [vertx](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/centos_vertx/install-vertx-dependencies.sh) and [spring-boot](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/centos_spring_boot/install_spring_boot_dependencies.sh)). What I think would help here is:

- [ ] As suggested by @benoitf `git clone` and `mvn clean install` the quickstart during the build of the image
- [ ] Increase the frequency of the stack images build so that images have fresh dependencies updates. Currently builds are triggered after a change in the Dockerfile (i.e. images can be 2 months old or more).

**Comment by bmicklea** [comment]
Can't we have a set of CI jobs that rebuild those images with latest deps every night?

**Comment by l0rd** [comment]
@bmicklea I've opened a PR to trigger the CI job daily (https://github.com/almighty/almighty-jobs/pull/297). 

@benoitf I will let you open the PR to preload the quickstarts dependencies.

**Comment by benoitf** [comment]
@l0rd I've created PR

**Comment by benoitf** [comment]
images for vertx/springboot with M2 dependencies are now available on openshift.io so we don't "download internet" anymore for the quickstart examples.
issue could be closed.
