### ISSUE TITLE
Created workspace does not appear in Codebases page

### ISSUE THREAD

**Issue by rhopp** [openshiftio/openshift.io#514]
I've created workspace for my codebase successfully, but on Codebases page in OSIO I still see only "Create workspace" button (instead of drop-down list with already created workspaces).
I've gone through Burr's demo twice and this happened both times.

![image](https://user-images.githubusercontent.com/1215011/29119640-3e11a520-7d07-11e7-8941-f349057e672a.png)

**Comment by joshuawilson** [comment]
@dlabrecq can you try this please and see if this is related to anything we did recently.

**Comment by dlabrecq** [comment]
There have not been any changes here that I know of. 

There are two possible scenarios that the user may be seeing.

1. A new workspace was created, but Che failed to start it. For some reason, our workspace API won't provide the newly created workspace, unless Che successfully started it.

2. The user created a workspace using the kebab Vs of the select menu. If the select menu were used instead, we poll the API for new workspaces until the page updates with the newly added codebase. I don't believe we do that with the kebab?

I'm guessing the issue is with the kebab, but we can add polling there as well.

**Comment by rhopp** [comment]
I created the workspace using create workspace link/button, not kebab menu. I tried it again today and the workspace appeared after refreshing browser window.
I tried again create workspace using kebab menu and the workspace again appeared correctly in UI after page refres.
```"For some reason, our workspace API won't provide the newly created workspace, unless Che was able to successfully start it."``` @dlabrecq Is this bug reported somewhere? I'd like to subscribe to that ;-)

**Comment by joshuawilson** [comment]
@ibuziuk @dlabrecq do you think this has anything to do with CheStarter? The issue appears to be on the Codebases page, not in Che. Is that correct @rhopp?

**Comment by ibuziuk** [comment]
@joshuawilson do not think it is coupled with CheStarter since it just returns list of workspaces based on github repo (no extra logic here). cc: @aslakknutsen 

> The user created a workspace using the kebab Vs of the select menu. If the select menu were used instead, we poll the API for new workspaces until the page updates with the newly added codebase. I don't believe we do that with the kebab?

dlabrecq do not really know what kebab means in terms of OSIO, but if a new workspace was created and started UI simply is not aware of it with disabled polling

**Comment by dlabrecq** [comment]
If Che has not started, the polling may simply timeout because it took too long. If you try creating a second workspace, you may find that the page updates.

I'll have to experiment with the polling timer. If it does not match the Che timeout, it should be adjusted.

Now that we have the Che start API, it's possible we can do something else to update that menu.

**Comment by l0rd** [comment]
Removing `area/che` label because it's codebase related

**Comment by joshuawilson** [comment]
I added the area/che label because the issue is the integration point between codebases and che. Do you disagree?

**Comment by l0rd** [comment]
I'm restoring `area/che` label and removing `team/che`

**Comment by ibuziuk** [comment]
@rhopp is it still reproducible? Codebases UX has been significantly changed with https://github.com/fabric8-ui/fabric8-ui/issues/1825 and I was not able to repro it

**Comment by rhopp** [comment]
I have not seen this recently. Feel free to close this issue.
