### ISSUE TITLE
Date based codebase filters treat dates as strings, not as dates

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#578]
If a user filters codebases based on commit or create dates, the user must enter the dates as strings.

For example, a filter of "Aug 15, 2017" will return codebases created today, but a filter of "8/15/2017" will not.

It would be better if date related selection fields would enable the user to select dates from a calendar. 

![screenshot 68](https://user-images.githubusercontent.com/642621/29319440-158f6dae-81a2-11e7-81d0-b11a0d3adb09.png)
![screenshot 69](https://user-images.githubusercontent.com/642621/29319438-158c7cd4-81a2-11e7-85ad-149997ca87e1.png)
![screenshot 70](https://user-images.githubusercontent.com/642621/29319441-158f4c66-81a2-11e7-97ad-1a17630ace0f.png)
![screenshot 71](https://user-images.githubusercontent.com/642621/29319439-158d7c88-81a2-11e7-8bf4-1e2ffd51745b.png)

## Impacts
- [ ] #1936 Codebases and Workspaces UI

**Comment by qodfathr** [comment]
I cannot get date-based filtering to work at all, even if I treat it as a string. I'm not sure what the use case is here, especially since it's limited to filtering to a particular date and not a date range. Moreover, date selections should have a calendar control, etc. etc.

@catrobson UX thoughts on this? I'm prepared to remove date-based filtering from the Codebases screen at this point in time. We can bring it back later if we've got better designs.

**Comment by catrobson** [comment]
Yes, this should enable a calendar control.  Agree that we should remove it until we build that capability into PatternFly-ng filters. @joshuawilson should Anna’s team remove this or would you like for me to assign to Dan?

**Comment by joshuawilson** [comment]
we should have @ashumilova take care of it if her team is able to

**Comment by ldimaggi** [comment]
This is still an open issue as of June 7, 2018.

**Comment by joshuawilson** [comment]
Platform team has been maintaining this page. I missed it due to original labels.

**Comment by jiekang** [comment]
The date-based filter has been removed as per comments above to be brought back in a future design.

**Comment by joshuawilson** [comment]
Closing since it has been removed.
