### ISSUE TITLE
Environments view lists Test, Stage, Run - but no "Test" project exists in OpenShift Online user account

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#580]
See attached screenshot - We dropped the Test project a while ago:

![screenshot 72](https://user-images.githubusercontent.com/642621/29320787-51cec6e4-81a6-11e7-82c2-44212996ad89.png)

**Comment by jstrachan** [comment]
Environments have logical names (Test, Stage, Run) that map to physical namespaces. The UI is designed so that users don't need to know or care too much what the physical namespaces are.

The users main namespace `${ID}` is used for the `Test` environment; then `${ID}-stage` for `Stage` and `${ID}-run` for `Run`. 

If you click the `Test` link it'll take you to the associated project in the OpenShift console to show you what the namespace it maps to (ditto for any other environments like `Stage` and `Run`
