### ISSUE TITLE
Codebases list displays github icon that appears to be a link, but is not

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#582]
See attached screenshot - the blue text is a live link to the codebase's github repo, but the blue highlighted github icon is not. This may be confusing for users. 

![capture 2](https://user-images.githubusercontent.com/642621/29322861-0d9f11a2-81ad-11e7-8c65-31c4943fc055.PNG)

**Comment by joshuawilson** [comment]
@catrobson @dlabrecq what do you think we should do?

**Comment by ldimaggi** [comment]
For the very short-term, we could remove the icon.

For the longer term, when we want to support repos at places in addition to github, I'd recommend making the icon part of the live link.

**Comment by dlabrecq** [comment]
I don't believe the icon was ever intended to be a link? The highlighting and mouse cursor don't change on hover. 

It's not even the same color blue; although, the screen shot looks similar. The link is actually a darker blue than that.

![screen shot 2017-08-15 at 2 18 26 pm](https://user-images.githubusercontent.com/17481322/29329686-acdb13e4-81c4-11e7-8909-45723e8d3b2d.png)

**Comment by catrobson** [comment]
@ldimaggi thanks for pointing out your confusion.  We're the the middle of redesigning this page, so let's just factor this into the redesign.  Redesign happening here:  https://github.com/fabric8-ui/fabric8-ux/issues/599#issuecomment-323048674

Would you be OK with closing this issue since I'm putting some information into that design effort about this?

**Comment by ldimaggi** [comment]
Yup! Just close it now - thx!
