### ISSUE TITLE
Usernames with underscore can't be provisioned properly

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#619]
It was discovered during our first early access workshop that OSIO usernames that include an underscore ("_") character foul the provisioning of the tenant. Underscores are hard to avoid because today the username is generated by stripping "." and "@" from email addresses.

We need a way to either handle underscores or generate the username via some other method.

### Impact
We have 4 users who are waiting to do the workshop that need a fix for this issue before they can participate. **We are currently planning on running the workshop the week of Aug-28**.

**Comment by bmicklea** [comment]
@aslakknutsen has done some work on this already connected to https://github.com/openshiftio/openshift.io/issues/283

**Comment by maxandersen** [comment]
In a perfect world it would be nice if the vanity name used in openshift.io urls i.e. `openshift.io/maxandersen` would be what we could use as base for all default naming of "things" such as namespace, urls etc.

Unfortunately reality is slightly more complicated:

a) we have users (especially old users) in RHD that has invalid characters like `@` and `_` in their user account - and due to legacy reasons in older backend systems we cannot rename/avoid them. 
b) even if we got all names cleaned up so we would have nice unique and clean vanity names we cannot guarantee that this name is available in the clusters we will run against. There is not a global namespace of openshift clusters - thus our code must not rely on namespaces following the pattern `<vanity name>-(jenkins|che|...)`

Thus proposed solution is that we get a service (`showTenant`) that will provide the *actual* namespace names to use. This will allow our code to get decoupled from whatevername is used and in short term we'll generate a unique name i.e. (`qewrt35erk3`) to be used as base.

Once that is done and known to be working we can look into generate names based on the vanity name if that is deemed important.

@aslakknutsen can you confirm if I got that right and what you got in progress on #283 ?

**Comment by aslakknutsen** [comment]
That sounds correct. There is also the added 'bonus' option of changing the username in OSiO which then would be != OSO/RHD username.

showTenant is available in prod via GET /api/user/services data.attribute.namespaces[]{type:che, name:xxx, ++}

**Comment by aslakknutsen** [comment]
Related https://github.com/fabric8-ui/fabric8-ui/pull/1911

**Comment by bmicklea** [comment]
@aslakknutsen based on yesterday's workshop it looks like this is fixed, do you agree?

**Comment by aslakknutsen** [comment]
@bmicklea Yes, agree. 

1) It's not much more intelligent atm then replace 'more'. Need a change in CheHost Auth to go fully 'random'.
2) No test case as we currently can't reproduce is end-2-end.
