### ISSUE TITLE
[3] Slow rendering of Stack Analysis Page at VSCode extension

### ISSUE THREAD

**Issue by krishnapaparaju** [openshiftio/openshift.io#624]
1) After receiving response from Analytics API, there is quite a lag before the complete page (HTML) is rendered. 

2) Traversing thru multiple tabs of VSCode does take a long time to render the Stack analysis report when the tab for 'Stack analysis report' is highlighted.

@GeorgeActon, please take a look at this bug.

**Comment by invincibleJai** [comment]
@arunkumars08 FYI , i guess it's due to load time. will caching be of any help , at least second point it should be able to handle.

**Comment by arunkumars08** [comment]
@invincibleJai Yes. I guess it could be. 
There are a few pointer to note.
Once you hit the GET url for seeing the View,

1. The view actually has to make a call to the API server to get the data. As our whole view depends on data, it has a lag to load.

We can think of some preloading view to let the user know something is happening. It is some kind of initial paint to browser.

And regarding caching, since call has to be made every time, I don't think it could be of greater help.

**Comment by invincibleJai** [comment]
@arunkumars08 got it , let's try preloading view once.

**Comment by krishnapaparaju** [comment]
What is the resolution on this bug ?

**Comment by invincibleJai** [comment]
@krishnapaparaju Arun was looking into this. As per my discussion with him , we can't reduce the load time further as all the resources rendered in browser are already compressed and minified , the delay is due to time taken by angular to bootstrap the app and the API call to stack-analysis which we are making on load itself. So during the lag user views blank white screen , we thought of having some initial paint and in parallel to making call to stack-analysis which will avoid white blank screen

CC @arunkumars08

**Comment by arunkumars08** [comment]
@invincibleJai If you could verify by checking in the IDE, this issue can be closed.

**Comment by invincibleJai** [comment]
@arunkumars08 can see a loader icon on page load. 

Closing it if you feel otherwise feel free to reopen.
