### ISSUE TITLE
the cleanup screen is nice but ambigious

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#625]
![cleanup_-_openshift_io](https://user-images.githubusercontent.com/54129/29505801-a9169d54-8648-11e7-806d-2eb538f1d11d.png)

The text says "the following ... will be removed ..." and the first thing that is listed is your account causing at least for me a to rethink a few times if I wanted to click "Erase" - I only did as I could guess from code what it would do.

I suggest to list the spaces first with their *full* osio name (i.e. `manderse@redhat.com/test`) and then the account stating its tenant setup will be reset (the account itself is NOT reset afaics).

Also, the hollow circle on spaces but grey in account makes it look like the elements are NOT selected and that I need to select them.
 
Suggest something like:

The following spaces will be erased:
  - [x] manderse@redhat.com/test
  - [x] manderse@redhat.com/my_space

This account tenant services will be reset:
  - [x] manderse@redhat.com

**Comment by joshuawilson** [comment]
@catrobson Can you take a look at this please.
cc @dgutride

**Comment by catrobson** [comment]
@maxandersen We'll be removing the circles that make it look like you can select them, there was a UX feedback on review of the Visual Design to remove these for that reason but we were also implementing at the same time.  :) . Small oversight, Dana is working on it now.

"Account tenant services" will make no sense to a user that isn't familiar with OpenShift.  The goal of the product is that users should not have to understand terms like "tenant" from OpenShift.  We purposefully obfuscated at the UI layer to tell the user that we're resetting their account, because for most users this is really all they need to know.  

The most important part here is really that we're going to reset your account, which is why we put it higher on the page than the spaces.  Knowing what spaces you are going to reset is just further validation making sure that the user *really* wants to do this in case they see a space name that makes them double think that choice.

Regarding showing full OSIO name - the name with email really isn't shown anywhere to the user in the UI, so I'm not sure why we would suddenly surface the e-mail version of the username here?  Can you explain more what you think this provides?  We could put username/space, but that's probably an overall conversation about org/username in front of space that we need to have site-wide which is why I left if off of this design for now - I'd like to establish the visual pattern for that as a separate story and then apply it everywhere needed.

**Comment by joshuawilson** [comment]
Closing as the page has been updated. Please reopen if there are still concerns.

**Comment by maxandersen** [comment]
> Regarding showing full OSIO name - the name with email really isn't shown anywhere to the user in the UI, so I'm not sure why we would suddenly surface the e-mail version of the username here?

sorry i missed this - but to be clear: manderse@redhat.com *is* my username; not just the email.
