### ISSUE TITLE
"View all Spaces" fails to display more spaces after spaces are deleted

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#631]
Steps to recreate:
* Create 20+ new spaces
* Navigate to "View all Spaces"
* Delete the spaces 
* Navigate to "View all Spaces"
* Observe that spaces are not displayed
* Navigate to "Account Home"
* Navigate to "View all Spaces"
* Observe that spaces are displayed

**Comment by ldimaggi** [comment]
Screencast:
https://drive.google.com/a/redhat.com/file/d/0B1s-ZoxD8FjUbnNwX3ZlLUZuM1k/view?usp=sharing

**Comment by joshuawilson** [comment]
This has to do with how we are calling the list of spaces. It is not infinite scroll as far as I know.

**Comment by ldimaggi** [comment]
The scroll bar implies, well, scrolling. Can we remove the scroll bar?

**Comment by joshuawilson** [comment]
We are redesigning the whole page and moving it. That is covered under https://github.com/openshiftio/openshift.io/issues/477

**Comment by joshuawilson** [comment]
@dlabrecq please keep this in mind for the new design

**Comment by dlabrecq** [comment]
Yes, the view all spaces page does use an infinite scroll and believe it fetches 40 spaces initially. You need to scroll for it to fetch more.

I cannot tell from the video (didn't see the original spaces), but are you absolutely certain the same spaces show up again? Perhaps you had more spaces than you deleted? 

When I deleted the 40 spaces shown in my page, they remained deleted. However, there were 10 spaces that had not been deleted because they were never shown in the page. I never scrolled to fetch more than the initial 40 spaces.

The thing I've noticed is that the controller won't fetch more data if you don't actually scroll. As you delete all your spaces, and the scroll bar goes away, you no longer have the ability to fetch more data. When I returned to page, it simply fetched the next 10 spaces.

Although this page is going through a redesign, it won't necessarily address the issues with infinite scroll component. That's used in many places, so we may want to take a closer look at that component?

**Comment by joshuawilson** [comment]
That was my concern as well. I believe we will likely use the same logic and APIs with the new design. That would mean this issue will persist in the new design too.

**Comment by qodfathr** [comment]
Two things.

1. @ldimaggi, the above discussion may explain why you still saw Spaces -- perhaps you did delete a bunch, but there were more that you didn't see (due to a bug). Can you please re-verify? If you agree that you observed the display bug, then I'd recommend closing this issue and...
2. ... @joshuawilson , can we open a new issue for the infinite-scroll-component-not-fetching-when-rows-deleted bug and xref from here to there?

**Comment by ldimaggi** [comment]
I think that we can close this one - these steps are now successful:

Steps to recreate:
* Create 20+ new spaces
* Navigate to "View all Spaces"
* Delete the spaces 
* Navigate to "View all Spaces"
* Observe that spaces are not displayed
* Navigate to "Account Home"
* Observe that spaces are not displayed

**Comment by joshuawilson** [comment]
@ldimaggi did you try it with more then 40? The initial fetch is for 40. Do you have a test that can create them?
