### ISSUE TITLE
Move firehose service to production

### ISSUE THREAD

**Issue by msrb** [openshiftio/openshift.io#669]
# Description

We have a service which listens for events about new releases (https://github.com/fabric8-analytics/fabric8-analytics-firehose-fetcher). It's been running in staging environment for quite some time, but it's not running in production yet. We want to move this service to production. This will require changes in CI/CD configuration in https://github.com/almighty/almighty-jobs.

# Acceptance criteria
- [x] docker image for the service is built, tested and pushed to the devshift registry via CentOS CI
- [x] the service is running in production

**Comment by krishnapaparaju** [comment]
How does the performance side of things look like ? Did we test the limit on messages that Fabric8 Analytics platform would be comfortable to handle ? Documentation around traversal of these messages coming from firehose would be useful.

@pkajaba

**Comment by pkajaba** [comment]
Firehose fetcher is still not deployed in production. I will be focusing on it right after I finish gathering Maven tags.

However, If there were too many messages we might introduce new queue (instead of ingestion). There would be dedicated workers, so it won't be a problem for ingestion queue. We will see after this service is deployed in production.

**Comment by pkajaba** [comment]
- [ ] Add cico scripts

- [ ] open PR for saas-analytics

- [ ] open PR for almighty-jobs

**Comment by krishnapaparaju** [comment]
Diagram covering the data flow that comes out of firehose would be quite useful + We wanna cover gather performance metrics, estimated / max. throughput that we can handle at production would give close ask on resources side (if any)

@kbsingh

**Comment by pkajaba** [comment]
Hello @krishnapaparaju, here is the diagram how are data processed from libraries.io: [firehose-fetcher diagram.pdf](https://github.com/openshiftio/openshift.io/files/1287116/firehose-fetcher.diagram.pdf)

First of all firehose-fetcher is rather lightweight so you don't have worry about performance. In Openshift template, there is a limit set to 256MB: https://github.com/fabric8-analytics/fabric8-analytics-firehose-fetcher/blob/master/openshift/template.yaml#L100

The only issue which might occur is that there will be too many new releases so queue will be full. Note that this is not an issue on firehose-fetcher side but on the queue/worker side since there will be more analysis.

**Comment by pkajaba** [comment]
Firehose-fetcher is deployed and running in production. 

It does not schedule new analysis at this point. Here is PR which enables this behavior: https://github.com/openshiftio/saas-analytics/pull/84

**Comment by fridex** [comment]
Closing, as done.
