### ISSUE TITLE
Integrate git commit message with work item

### ISSUE THREAD

**Issue by rafabene** [openshiftio/openshift.io#718]
Based on customer's feedback in the workshop, the work item ID should be communicated to Che so that the commit message can include the work item ID. The commit should then be reflected in the work item as a comment / event.

This will simplify tracking between the codebase changes and the work items.

**Comment by rgarg1** [comment]
This will be a handy functionality to provide cross linking between OSIO and GitHub or any other source management system.

**Comment by rgarg1** [comment]
@catrobson Assigning to you so that you can get Product Management perspective and priority on this. If you think this should be assigned to someone else, pls let me know.

**Comment by joshuawilson** [comment]
Unassigning @catrobson since you are just asking her a question and she isn't doing the work.

**Comment by joshuawilson** [comment]
@rgarg1 While Cat can ask PM, this type of thing is either addressed directly by PM (since they read the issues too) or the dev leads would ask PM. (Note: @bmicklea is on the PM team and he read it and added a label, so PM at least knows about it)

**Comment by joshuawilson** [comment]
@qodfathr what do you think? Do you agree that we should integrate the work item ID into the commit message?

**Comment by qodfathr** [comment]
Crazy late response, I know -- but, in essence, I agree that the commit message should related back to the work item in some form. However, right now, we don't have an implemented workflow which communicates to Che about what work the user is doing. That's part of some of the design work that is happening. 

I am going to assign this to myself, so that I eventually return to this issue and link it to a newly created Scenario which ultimately covers this request -- at which point I'll close this issue as a reverse dupe.

**Comment by ibuziuk** [comment]
Closing as outdated
