### ISSUE TITLE
Remove generator-backend fork

### ISSUE THREAD

**Issue by corinnekrych** [openshiftio/openshift.io#740]
The [generator-backend](https://github.com/fabric8io/generator-backend) was originally forked from [launchpad-backend](https://github.com/openshiftio/launchpad-backend). 
- [ ] adjust fabric8-add to not load all forge addon
- [ ] the generator-backend use version `1.0.0.CR3` of forge service. The service is now in `1.0.1.Final`. This stable version has changed the way addon are loaded.
- [ ] uncomment/add arquillian testings

@bartoszmajsak I've captured the chat we had but could you add more insight/task to it pls.
cc @gastaldi @jstrachan any more tasks for it?

**Comment by bartoszmajsak** [comment]
There are several things to care of here. Sadly it's not a matter of simple merge.

 1. We cannot simply switch to upstream, as there were several changes made in the fork:
     * we have [`fabric8-generator`](https://github.com/fabric8io/fabric8-generator/) addon
     * we introduced [`OpenShiftServiceResource`](https://github.com/fabric8io/generator-backend/blob/eeb15127728348eb55607841ecacd09e2069ff3e/src/main/java/org/obsidiantoaster/generator/rest/OpenShiftServiceResource.java)
 2. Changes in the way how upstream loads addons leads to [failed deployment](https://gist.github.com/bartoszmajsak/305ce1c4b6d257b30dfab6ad1dc6f6eb#file-obsidianresourceit-java-L341)
 
##### Ad 1. 

We should provide a solution which will bundle all those things together and ship as one uber-jar of Wildfly Swarm. `OpenShiftServiceResource` could be extracted as a partial jar.

##### Ad 2.

At the point of forking Forge Addons were put in `WEB-INF/addon` and during the startup of Forge container there were scanned and loaded into the isolated classloader. Currently, upstream backend adds every addon as regular JAR to `WEB-INF/lib` which results in CDI container scanning the JARs and [blowing up]((https://gist.github.com/bartoszmajsak/305ce1c4b6d257b30dfab6ad1dc6f6eb#file-obsidianresourceit-java-L341))

We have to simplify dependencies of [`fabric8-generator`](https://github.com/fabric8io/fabric8-generator/) addon, as it gets too many unused addons as transitive dependencies from `forge-core` addon. The problematic addon failing the deployment in the shared gist is `forge-scaffolding` which pulls in `metawidget` without spring dependencies on the classpath. I suspect that with `WEB-INF/addon` approach, as this addon was never explicitly used by Forge, it was never loaded and thus not leading to this failure (@gastadli please correct me if my reasoning is wrong).

Easy fix would be to exclude problematic addons by specifing packages to be not scanned by CDI container during startup:

```xml
 <beans xmlns="http://java.sun.com/xml/ns/javaee" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:weld="http://jboss.org/schema/weld/beans">
   <weld:scan>
     <weld:exclude name="org.jboss.forge.addon.scaffold.**"/>
   </weld:scan>
 </beans>
```

But I would rather clean-up the Fabric8 addon itself rather than doing such an ad-hoc hack.

**Comment by bartoszmajsak** [comment]
Old tests have been re-enabled https://github.com/fabric8io/generator-backend/pull/50. More to come as a contract PoC.

**Comment by gastaldi** [comment]
+1 on simplifying deps on the fabric8 addon. Also as part of this merge, it would be nice to introduce a maven profile containing a dependency to the fabric8 addon, as this won't be used by the launch app

**Comment by bartoszmajsak** [comment]
Yeah, profile could be one way of `Ad. 1`

**Comment by gastaldi** [comment]
This issue looks outdated. It can be closed now
