### ISSUE TITLE
UI issue - Che workspaces appear in the wrong place

### ISSUE THREAD

**Issue by bmicklea** [openshiftio/openshift.io#797]
When creating multiple spaces in your account you will see the new space's project (springbasic in the example below) in the old space's Codebases tab beside the old space's project (springboot in the example below). This is confusing because that new project is not actually part of that space.

<img width="1028" alt="screen shot 2017-09-12 at 11 03 47 am" src="https://user-images.githubusercontent.com/7644938/30334215-eb4ec28a-97ac-11e7-800f-b3ed78ddf7d5.png">

### To Reproduce
1. Create a space with a quick start project inside
1. Create the Che workspace for that project
1. Open then stop the Che workspace and return to the Codebases dashboard
1. Create a new space from the spaces dropdown (so you remain on the Codebases tab)
1. Go through the forge wizard
When the wizard completes you will still be in the old space (we should probably take people to the new space) but now you will see the second project under the original first project.

Going to view my spaces page and selecting the new space will correct this.

### Environment
OSIO with Chrome (incognito) on OSX
Che 2.0.17
Jenkins 4.0.12

Confirmed by @darrenratcliffe

**Comment by bmicklea** [comment]
@joshuawilson please add the correct tags for team (UX?)

**Comment by joshuawilson** [comment]
@dlabrecq can you take a look at this when you get a minute.

**Comment by dlabrecq** [comment]
The UI is only displaying the workspaces returned by the back-end API -- if the user is still in the current space, then that would be expected. 

Note that the codebases page has little to do with the "create space" functionality in the main menu or the Forge wizard.

I agree that the user should be navigated to the newly created space. However, this may be more of an issue with the Forge wizard? That is, it's the Forge wizard that is creating the new space.

**Comment by catrobson** [comment]
@dlabrecq - If you follow the steps here it looks like the second codebase added should be added to the new space [which the user creates through the main menu], not the old space.  I think that is the primary issue of this, and navigating to the new space upon creation is a secondary problem.  

The Forge wizard might be not accurately adding the new codebase to the new space - @corinnekrych can you take a look as well and help identify if Forge is adding codebases to a new space in this situation?  @dlabrecq can you confirm that the API you're getting is filtering codebases by space correctly?

**Comment by dlabrecq** [comment]
Yes, the API is returning the correct codebases for the given space. 

Please keep in mind that codebases and planner are shown in the content of a given space. To work with a different space, the user must navigate to that space.

The underlying problem is that the user is still in the same space after the Forge wizard creates a new one.

Note that planner encounters the same issue. You can create a new space, but you have not navigated away from the current one. Thus, any work items created are not added to the new space.

**Comment by dlabrecq** [comment]
The Forge wizard provides a "take me to the dashboard" button, but users don't have to navigate away from the current space.

**Comment by dlabrecq** [comment]
Ok, I've found the culprit in the Forge wizard.

The Forge wizard is broadcasting a 'codebaseAdded' event, which adds the newly created codebase to the page. See:

./space/wizard/services/fabric8-app-generator.client.ts: this._broadcaster.broadcast('codebaseAdded', codebase);

This particular event was added specifically for the 'Add Codebase' functionality in the codebases page. That is, the slide-out component uses this event to add the newly created codebases to the list shown in the main page. Otherwise, we would need to refresh the entire page just to update the list of codebases.

Note that this was not intended for the Forge wizard, especially if it's creating a codebase in a new space.

**Comment by bmicklea** [comment]
If a user creates a new space they will want to move to that new space
immediately in >90% of the cases. So that should be our default path - are
there technical challenges to doing this?

**Comment by catrobson** [comment]
@bmicklea I would expect it to bring them to the dashboard for that space.  Do you agree?  I think this is not happening because we just recently put in some code to make it so that if you are creating a new project or importing code from within the same space, it doesn't navigate you back to the dashboard in those cases (and remove the user from their current context). 

Due to the way that the Forge Wizard is tightly coupled with the Space creation right now, I'm not sure if there are technical issues with us treating these two use cases separately.  To be clear, these are the two use cases then:

- If I created a new space, always navigate me to the dashboard of that new space after I get through the wizard.
- If I am adding something to this existing space, keep me in context of where I am adding content to the project (don't navigate to dashboard).

@corinnekrych @joshuawilson could you comment?

**Comment by dgutride** [comment]
@bmicklea - we should be able to update the wizard to handle being smarter about whether or not they were started in response to existing space configuration or space creation.  A change was made recently to not lose the space context if the user opened the wizard which likely resulted in what you are seeing for the user not being redirected.

**Comment by bmicklea** [comment]
@dgutride thanks for the clarifications.

@catrobson agree on the two scenarios and behaviors of each, let's make sure @qodfathr does too.

**Comment by joshuawilson** [comment]
@catrobson what @dgutride said is right.

**Comment by corinnekrych** [comment]
@catrobsonI think @dlabrecq found the problem, it's a notification issue. with my OSIO account the codebase broadcast never works (wierd) therefore the codebase widget never get updated with the repo but if i go to codebase tab I can see the newly created repo. I can not reproduce the issue describe in this ticket. For me, the repo are created on the relevant space. @dlabrecq are you suggesting we should just remove this line:
https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/wizard/services/fabric8-app-generator.client.ts#L459 ?

**Comment by corinnekrych** [comment]
@dgutride @catrobson which recent change are you referring to? link to PR will help

**Comment by dlabrecq** [comment]
Yes, I believe that should be removed. Unless the forge wizard is truly adding a codebase to the current space?

I'm thinking we should also modify the codebases page to reload the entire list whenever the 'codebaseAdded' event is received. It would be less efficient considering we've already retrieved the new codebase from the back-end. However, this would ensure we only display codebases for the current space, regardless of what forge wizard does.

**Comment by corinnekrych** [comment]
+1 @dlabrecq
