### ISSUE TITLE
[5] Getting 500 in stack-analysis-v2 on get call after successfully getting stack ID for analysis

### ISSUE THREAD

**Issue by samuzzal-choudhury** [openshiftio/openshift.io#850]
_From @invincibleJai on August 25, 2017 7:7_

1) uploaded single manifest file (requirements.txt) with contents : 
`click==6.7`
`httpie==0.9.9`
`parsimonious==0.7.0`
`pygments==2.2.0`
`six==1.10.0`
`wheel==0.30.0a0`
`setuptools==36.0.1`

2) got Stack ID `25ea680bdf4241e88be8490856840f72` get call works fine

3) add one more component(invalid one) to above requirements.txt
`click==6.7`
`httpie==0.9.9`
`parsimonious==0.7.0`
`pygments==2.2.0`
`six==1.10.0`
`wheel==0.30.0a0`
`setuptools==36.0.1`
`setupjai==36.0.1`

3) got stack ID `9b37c93b5ee14dea93ee31bc17b050c6` , get call gives 500 now with error message 
`{
    "error": "Invalid manifest file(s) received. Please submit valid manifest files for stack analysis"
}`

_Copied from original issue: fabric8-analytics/fabric8-analytics-server#132_

**Comment by GeorgeActon** [comment]
@samuzzal-choudhury was this introduced as a result of v2?
the error message seems correct bt it would be better if we could determine which line is in error so they knew what to change

**Comment by samuzzal-choudhury** [comment]
@GeorgeActon Not really.  It's actually a failure on the worker side when the manifest contents are processed. We need to investigate more to figure out the component in fault.

**Comment by jpopelka** [comment]
I began to look at this and I must admit I don't understand what's the issue.

As far as I understand it:
When you post a request to `/stack-analyses` it returns success & ID and asynchronously starts `stackApiGraphFlow`, which runs `GraphAggregatorTask`, which processes the manifest files.
When you then access `/stack-analyses/<external_request_id>`, we check result of `GraphAggregatorTask` and when we see it failed, we return the error you are seeing.

In this case `GraphAggregatorTask` fails because of the non-existent component (`setupjai==36.0.1`) in requirements.txt and GET call returns the error.
George is right that it'd be nice to have at least some indication of what's failed, but such information is not stored in db, we just know that `GraphAggregatorTask` failed, so we can't give more details. I guess it should be doable, but that's for another ticket.

**Comment by jpopelka** [comment]
As I stated in previous comment the behaviour seems correct to me so unless somebody ( @samuzzal-choudhury @invincibleJai ) explains to me what's wrong I'm going to close this thicket.
