### ISSUE TITLE
Space is recreated after delete on logout

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#925]
_From @ldimaggi on April 28, 2017 2:35_

Steps to recreate:
* Create a new space
* In that space create one or more workitems
* Delete the space
* Logout and login to refresh all menus/lists of spaces
* The space is still there, but its workitems are gone
* The space can now be deleted

_Copied from original issue: fabric8-ui/fabric8-ui#1197_

**Comment by joshuawilson** [comment]
Cool feature! I was wanting to do that earlier today.

**Comment by joshuawilson** [comment]
_From @aslakknutsen on July 19, 2017 2:36_

I just noticed the same. This is my debug info:

Create a space, Go anywhere, Go to View All spaces, Delete created space. The rest api DELETE space is called. Logout. Notification '"SpaceName" was created!" appear. It somehow manages to call POST spaces with the same space during logout for some absurd reason. Log back in and the space is there. This time you can delete it.

**Comment by qodfathr** [comment]
This is actually pretty concerning, as it does not look to be just a caching/display issue. The deleted Space really does seem to still exist.

**Comment by aslakknutsen** [comment]
@qodfathr It only 'seems' to exist. It is actually deleted, but for whatever silly reason a new one is created with the same name. Some integrations only match on SpaceName which is why you can see 'old' data still in the same, but the Space actually has a different ID.

**Comment by jiekang** [comment]
https://github.com/openshiftio/openshift.io/issues/2206

addressed the issue of spaces being created when logging out. I think this touches upon what occurred here; since the space was deleted, the request was successful whereas in 2206, since the space exists already, it was unsuccessful. The bug where a http request is made to create a space when a user logs out should be fixed and so I think this issue can be closed.

If otherwise, feel free to comment and reopen.
