### ISSUE TITLE
ngx-widgets build failure

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#947]
Currently I'm unable to get the master for ngx-widgets to build and release. 

I can build it locally and the PR builds pass.

Here is the repo and jenkins page:
https://github.com/fabric8-ui/ngx-widgets/commits/master
https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/ngx-widgets/job/master/3/console

I don't know if this is related to the dependency changes that were made in the code or if they are external configurations.

**Comment by joshuawilson** [comment]
@rawlingsj can you please take a look at this?

**Comment by rawlingsj** [comment]
The reason CI passes is because CI (https://github.com/fabric8-ui/ngx-widgets/blob/master/release.groovy#L4) doesn't run the `npm run build` that the CD pipeline run https://github.com/fabric8-ui/ngx-widgets/blob/master/release.groovy#L21

I don't know this library or particularly familiar with node but will try and help when I get a chance.

**Comment by rawlingsj** [comment]
So it's definitely the `npm run build` step that fails in the pipeline and I'm not sure why yet.  If I pause the pipeline after `npm install` and `kubectl exec` into the build pod to manually run `npm run build` it works!  It doesn't seem to be timing as I've tried adding a sleep between the two commands and it also still fails if I run it as one inline command i.e. `npm install && npm run build`

I'm not familiar with what this component does, what the `npm run build` aims to do or if it's required but if it is not 100% needed then to unblock the release I've added this PR https://github.com/fabric8-ui/ngx-widgets/pull/96.  It catches the error and allows the CI + release to carry on until we figure out what's wrong.

Passing CI https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/ngx-widgets/view/change-requests/job/PR-96/

So depending on how urgent a release of ngx-widgets is we can merge thats PR and unblock development.  @michaelkleinhenz @joshuawilson any other ideas? If not lets merge?

**Comment by joshuawilson** [comment]
`npm run build` creates the files that get released, so it can't be skipped. I'll try doing a manual build and release and see if that resets things.

**Comment by joshuawilson** [comment]
I did a manual release and then merged a PR and the build failed again.

**Comment by rawlingsj** [comment]
After spending 4 hours resorting to basic investigation on a project I have no idea about, npm plugins I've not used before and an unfamiliar build process I have a fix in place https://github.com/fabric8-ui/ngx-widgets/pull/97.

Also I have to say adding a label of `severity/blocker` when you have a manual work around is incorrect.  Please let's not abuse the use of this label.

Also just because something fails in a CI environment shouldn't mean it's up to the pipeline team to investigate and fix.  With basic investigation of trial and error I was able to narrow down where the error was happening and was able to try a few things in the package.json to resolve it, which IMO could have bene done by most folks in dev tools (note this was not a failure introduced by our CI infra).  I certainly don't mind helping but when we're scaling to hundreds of repos then I'd like to encourage more analysis before raising these type of "blocking" issues and assigning to the build team. 

From now on if the build-cd team label is added (for a CI or CD pipeline failure) I'd like there to be sufficient investigation done before hand, along with explanations of what's been tried which helps discussion and knowledge sharing.

**Comment by joshuawilson** [comment]
I've change the severity from blocker to P1, since as you say we have a manual work around. 

I have done all that I know to fix this issue, that is why I raised it. I agree that building the modules should not be the CI/CD team's responsibility. It sounds like you are saying we should shift all the builds back to @kbsingh and his team to run con centos.ci so they can support it.

I think the CI/CD should not have to worry about supporting other teams builds, that falls under the SD team.

**Comment by rawlingsj** [comment]
> It sounds like you are saying we should shift all the builds back to @kbsingh and his team to run con centos.ci so they can support it.

No I did not say anything like that :) I'm saying someone (you) other than the build team (me) could have done exactly what I did.  I have no knowledge of this repo so it took me a few hours, but I think you could have tried breaking down the npm steps as I did and you'd have found the same issue + resolution as me :)

**Comment by rawlingsj** [comment]
PR merged and build is working.
